# Generated by Django 6.0.1 on 2026-01-24 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PadletBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='설정 이름')),
                ('system_prompt', models.TextField(verbose_name='시스템 프롬프트')),
                ('welcome_message', models.TextField(blank=True, verbose_name='환영 메시지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '패들릿 봇 설정',
                'verbose_name_plural': '패들릿 봇 설정 목록',
            },
        ),
        migrations.CreateModel(
            name='PadletDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문서 제목')),
                ('file', models.FileField(upload_to='padlet_bot/docs/', verbose_name='파일')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='파일 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_processed', models.BooleanField(default=False, verbose_name='벡터DB 처리 완료')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_padlet_docs', to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '패들릿 문서',
                'verbose_name_plural': '패들릿 문서 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
