# Generated by Django 6.0.1 on 2026-01-24 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedPadletBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=100, unique=True, verbose_name='보드 ID')),
                ('board_url', models.URLField(blank=True, verbose_name='패들릿 URL')),
                ('title', models.CharField(max_length=200, verbose_name='보드 제목')),
                ('description', models.TextField(blank=True, verbose_name='보드 설명')),
                ('post_count', models.IntegerField(default=0, verbose_name='게시물 수')),
                ('is_processed', models.BooleanField(default=False, verbose_name='벡터DB 처리 완료')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='마지막 동기화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='연동일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_padlet_boards', to=settings.AUTH_USER_MODEL, verbose_name='연동한 사용자')),
            ],
            options={
                'verbose_name': '연동된 패들릿',
                'verbose_name_plural': '연동된 패들릿 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
