# Generated by Django 6.0.1 on 2026-01-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet_bot', '0002_linkedpadletboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedpadletboard',
            name='board_id',
            field=models.CharField(max_length=100, verbose_name='보드 ID'),
        ),
    ]
