# Generated by Django 6.0.1 on 2026-02-17 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HSClassroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='학급 이름')),
                ('school_name', models.CharField(blank=True, max_length=100, verbose_name='학교명')),
                ('slug', models.SlugField(unique=True, verbose_name='공개 정원 슬러그')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '교실',
                'verbose_name_plural': '교실 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HSBehaviorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='코드')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('icon', models.CharField(default='🌱', max_length=10, verbose_name='아이콘')),
                ('seeds_reward', models.IntegerField(default=1, verbose_name='씨앗 보상')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_categories', to='happy_seed.hsclassroom')),
            ],
            options={
                'verbose_name': '행동 카테고리',
                'verbose_name_plural': '행동 카테고리 목록',
                'ordering': ['display_order'],
                'unique_together': {('classroom', 'code')},
            },
        ),
        migrations.CreateModel(
            name='HSActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('threshold_score', models.IntegerField(default=80, verbose_name='기준 점수')),
                ('extra_bloom_count', models.IntegerField(default=1, verbose_name='추가 블룸 수')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='happy_seed.hsclassroom')),
            ],
            options={
                'verbose_name': '활동',
                'verbose_name_plural': '활동 목록',
            },
        ),
        migrations.CreateModel(
            name='HSClassroomConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeds_per_bloom', models.IntegerField(default=10, verbose_name='블룸 전환 기준')),
                ('base_win_rate', models.IntegerField(default=5, verbose_name='기본 당첨 확률(%)')),
                ('group_draw_count', models.IntegerField(default=1, verbose_name='모둠 성공 시 랜덤 인원수')),
                ('balance_mode_enabled', models.BooleanField(default=False, verbose_name='따뜻한 균형 모드')),
                ('balance_epsilon', models.FloatField(default=0.05, verbose_name='보정 계수')),
                ('balance_lookback_days', models.IntegerField(default=30, verbose_name='보정 기간(일)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='happy_seed.hsclassroom')),
            ],
            options={
                'verbose_name': '교실 설정',
                'verbose_name_plural': '교실 설정 목록',
            },
        ),
        migrations.CreateModel(
            name='HSPrize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='보상 이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('total_quantity', models.IntegerField(blank=True, help_text='비워두면 무제한', null=True, verbose_name='총 수량')),
                ('remaining_quantity', models.IntegerField(blank=True, null=True, verbose_name='남은 수량')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='happy_seed.hsclassroom')),
            ],
            options={
                'verbose_name': '보상',
                'verbose_name_plural': '보상 목록',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HSStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('number', models.IntegerField(default=0, verbose_name='번호')),
                ('seed_count', models.IntegerField(default=0, verbose_name='현재 씨앗')),
                ('ticket_count', models.IntegerField(default=0, verbose_name='현재 보유 티켓 수')),
                ('total_wins', models.IntegerField(default=0, verbose_name='총 당첨 횟수')),
                ('pending_forced_win', models.BooleanField(default=False, verbose_name='다음 회 강제 당첨')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='happy_seed.hsclassroom')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생 목록',
                'ordering': ['number', 'name'],
                'unique_together': {('classroom', 'number')},
            },
        ),
        migrations.CreateModel(
            name='HSInterventionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('forced_win_immediate', '즉시 강제 당첨'), ('forced_win_next', '다음 회 강제 당첨'), ('seed_grant', '씨앗 부여'), ('seed_deduct', '씨앗 차감')], max_length=25, verbose_name='개입 유형')),
                ('detail', models.TextField(blank=True, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_logs', to='happy_seed.hsclassroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_logs', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '교사 개입 로그',
                'verbose_name_plural': '교사 개입 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HSGuardianConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('approved', '동의완료'), ('rejected', '거부'), ('expired', '만료'), ('withdrawn', '철회')], default='pending', max_length=10, verbose_name='동의 상태')),
                ('external_url', models.URLField(blank=True, verbose_name='외부 전자서명 링크')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='동의 요청 시각')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='동의 완료 시각')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '보호자 동의',
                'verbose_name_plural': '보호자 동의 목록',
            },
        ),
        migrations.CreateModel(
            name='HSBloomDraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_win', models.BooleanField(verbose_name='당첨 여부')),
                ('input_probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='투입 확률(%)')),
                ('balance_adjustment', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='균형모드 보정값')),
                ('effective_probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='최종 적용 확률(%)')),
                ('is_forced', models.BooleanField(default=False, verbose_name='교사 개입 여부')),
                ('force_reason', models.CharField(blank=True, max_length=200, verbose_name='개입 사유')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='멱등성 키')),
                ('celebration_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='축하 화면 토큰')),
                ('celebration_closed', models.BooleanField(default=False, verbose_name='축하 화면 닫힘')),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_draws', to=settings.AUTH_USER_MODEL)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_results', to='happy_seed.hsprize')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloom_draws', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '추첨 결과',
                'verbose_name_plural': '추첨 결과 목록',
                'ordering': ['-drawn_at'],
            },
        ),
        migrations.CreateModel(
            name='HSBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('seeds_awarded', models.IntegerField(default=0, verbose_name='부여 씨앗')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='happy_seed.hsbehaviorcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_behavior_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '행동 기록',
                'verbose_name_plural': '행동 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HSStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='모둠 이름')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='happy_seed.hsclassroom')),
                ('members', models.ManyToManyField(blank=True, related_name='student_groups', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '모둠',
                'verbose_name_plural': '모둠 목록',
            },
        ),
        migrations.CreateModel(
            name='HSSeedLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(verbose_name='변동량')),
                ('reason', models.CharField(choices=[('no_win', '미당첨 보상'), ('behavior', '행동 인정'), ('recovery', '회복'), ('bloom_convert', '블룸 전환'), ('teacher_grant', '교사부여')], max_length=20, verbose_name='사유')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='상세')),
                ('balance_after', models.IntegerField(verbose_name='변동 후 잔액')),
                ('request_id', models.UUIDField(default=uuid.uuid4, verbose_name='멱등성 키')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_ledger', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '씨앗 원장',
                'verbose_name_plural': '씨앗 원장 목록',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'request_id')},
            },
        ),
        migrations.CreateModel(
            name='HSActivityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('bloom_granted', models.BooleanField(default=False, verbose_name='블룸 부여됨')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='happy_seed.hsactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_scores', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '활동 점수',
                'verbose_name_plural': '활동 점수 목록',
                'unique_together': {('activity', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HSTicketLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('participation', '성실참여'), ('achievement', '우수성취'), ('seed_accumulation', '씨앗누적'), ('group_draw', '모둠추첨'), ('teacher_grant', '교사부여')], max_length=20, verbose_name='원천')),
                ('amount', models.IntegerField(verbose_name='변동량')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='상세')),
                ('balance_after', models.IntegerField(verbose_name='변동 후 잔액')),
                ('request_id', models.UUIDField(default=uuid.uuid4, verbose_name='멱등성 키')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_ledger', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '티켓 원장',
                'verbose_name_plural': '티켓 원장 목록',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'request_id')},
            },
        ),
    ]
