# Generated by Django 6.0.1 on 2026-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsprize',
            name='win_rate_percent',
            field=models.DecimalField(decimal_places=2, default=100, help_text='당첨 시 이 보상이 선택되는 상대 확률입니다. (예: 70, 20, 10)', max_digits=5, verbose_name='보상 선택 확률(%)'),
        ),
    ]
