# Generated by Django 6.0.1 on 2026-02-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0002_hsprize_win_rate_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSClassEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('TOKEN_GRANTED_DILIGENT', '성실참여 꽃피움권 지급'), ('TOKEN_GRANTED_SCORE_BONUS', '우수성취 추가 꽃피움권 지급'), ('SEED_GRANTED_MANUAL', '교사 수동 씨앗 지급'), ('DRAW_EXECUTED', '꽃피움 실행'), ('DRAW_WIN', '꽃피움 당첨'), ('DRAW_LOSE', '꽃피움 미당첨'), ('SEED_AUTO_FROM_LOSS', '미당첨 씨앗 자동적립'), ('TOKEN_AUTO_FROM_SEEDS_THRESHOLD', '씨앗 누적 자동 전환'), ('TEACHER_OVERRIDE_SET', '교사 개입 예약'), ('TEACHER_OVERRIDE_USED', '교사 개입 사용'), ('WARM_BALANCE_MODE_TOGGLED', '균형모드 토글'), ('CONSENT_REQUEST_SENT', '동의 요청 발송'), ('CONSENT_SIGNED', '동의 완료')], max_length=40, verbose_name='유형')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='부가정보')),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='happy_seed.hsclassroom', verbose_name='반')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='happy_seed.hsstudentgroup')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='happy_seed.hsstudent')),
            ],
            options={
                'verbose_name': '반 이벤트 로그',
                'verbose_name_plural': '반 이벤트 로그 목록',
                'ordering': ['-timestamp'],
            },
        ),
    ]
