# Generated by Django 6.0.1 on 2026-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0003_hsclasseventlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsclasseventlog',
            name='type',
            field=models.CharField(choices=[('TOKEN_GRANTED_DILIGENT', '성실참여 꽃피움권 지급'), ('TOKEN_GRANTED_SCORE_BONUS', '우수성취 추가 꽃피움권 지급'), ('SEED_GRANTED_MANUAL', '교사 수동 씨앗 지급'), ('DRAW_EXECUTED', '꽃피움 실행'), ('DRAW_WIN', '꽃피움 당첨'), ('DRAW_LOSE', '꽃피움 미당첨'), ('SEED_AUTO_FROM_LOSS', '미당첨 씨앗 자동적립'), ('TOKEN_AUTO_FROM_SEEDS_THRESHOLD', '씨앗 누적 자동 전환'), ('TEACHER_OVERRIDE_SET', '교사 개입 예약'), ('TEACHER_OVERRIDE_USED', '교사 개입 사용'), ('GROUP_MISSION_REWARD', '모둠 미션 랜덤 지급'), ('WARM_BALANCE_MODE_TOGGLED', '균형모드 토글'), ('CONSENT_REQUEST_SENT', '동의 요청 발송'), ('CONSENT_SIGNED', '동의 완료')], max_length=40, verbose_name='유형'),
        ),
    ]
