# Generated by Django 6.0.1 on 2026-03-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0002_handoffrostermember_affiliation_and_more'),
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsclassroom',
            name='shared_roster_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hs_classrooms', to='handoff.handoffrostergroup', verbose_name='공용 명부'),
        ),
        migrations.AddField(
            model_name='hsstudent',
            name='shared_roster_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='happy_seed_students', to='handoff.handoffrostermember'),
        ),
    ]
