# Generated by Django 6.0.1 on 2026-02-26 15:51

import django.db.models.deletion
import django.utils.timezone
import parentcomm.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(choices=[('parent', '학부모 요청'), ('teacher', '교사 요청'), ('system', '시스템 전환')], default='parent', max_length=20)),
                ('reason', models.TextField()),
                ('escalation_reason', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('requested', '요청됨'), ('reviewing', '검토 중'), ('proposed', '교사 제안 완료'), ('awaiting_parent', '학부모 선택 대기'), ('confirmed', '일정 확정'), ('declined', '거절됨'), ('completed', '완료'), ('canceled', '취소')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '상담 요청',
                'verbose_name_plural': '상담 요청',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('allowed_methods', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', '제안됨'), ('accepted', '수락됨'), ('declined', '거절됨'), ('canceled', '취소됨'), ('expired', '만료됨')], default='proposed', max_length=20)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_proposals', to=settings.AUTH_USER_MODEL)),
                ('consultation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='parentcomm.consultationrequest')),
            ],
            options={
                'verbose_name': '상담 제안',
                'verbose_name_plural': '상담 제안',
                'ordering': ['-proposed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('chat', '채팅 상담'), ('phone', '전화 상담'), ('visit', '방문 상담')], max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('location_note', models.CharField(blank=True, default='', max_length=200)),
                ('channel_hint', models.CharField(blank=True, default='', max_length=120)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parentcomm.consultationproposal')),
            ],
            options={
                'verbose_name': '상담 제안 시간',
                'verbose_name_plural': '상담 제안 시간',
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='selected_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_requests', to='parentcomm.consultationslot'),
        ),
        migrations.CreateModel(
            name='ParentCommunicationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_parent_messages_per_thread', models.PositiveSmallIntegerField(default=3)),
                ('max_open_threads_per_parent', models.PositiveSmallIntegerField(default=1)),
                ('office_hours_start', models.TimeField(default=parentcomm.models.default_office_start)),
                ('office_hours_end', models.TimeField(default=parentcomm.models.default_office_end)),
                ('auto_escalate_on_critical', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comm_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학부모 소통 정책',
                'verbose_name_plural': '학부모 소통 정책',
            },
        ),
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=80)),
                ('student_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('student_classroom', models.CharField(blank=True, default='', max_length=20)),
                ('parent_name', models.CharField(max_length=80)),
                ('relationship', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('emergency_access_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학부모 연락처',
                'verbose_name_plural': '학부모 연락처',
                'ordering': ['student_name', 'parent_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='parent_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='parentcomm.parentcontact'),
        ),
        migrations.CreateModel(
            name='ParentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_label', models.CharField(blank=True, default='', max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림장',
                'verbose_name_plural': '알림장',
                'ordering': ['-is_pinned', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParentNoticeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='parentcomm.parentnotice')),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_receipts', to='parentcomm.parentcontact')),
            ],
            options={
                'verbose_name': '알림장 수신 기록',
                'verbose_name_plural': '알림장 수신 기록',
            },
        ),
        migrations.CreateModel(
            name='ParentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(default='general', max_length=50)),
                ('status', models.CharField(choices=[('open', '진행 중'), ('waiting_parent', '학부모 답변 대기'), ('waiting_teacher', '교사 답변 대기'), ('needs_consult', '상담 전환 필요'), ('closed', '종료')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('normal', '일반'), ('important', '중요'), ('critical', '긴급')], default='normal', max_length=20)),
                ('parent_message_limit', models.PositiveSmallIntegerField(default=3)),
                ('parent_message_count', models.PositiveSmallIntegerField(default=0)),
                ('teacher_message_count', models.PositiveSmallIntegerField(default=0)),
                ('last_parent_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_teacher_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='parentcomm.parentcontact')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학부모 문의 스레드',
                'verbose_name_plural': '학부모 문의 스레드',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='thread',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_request', to='parentcomm.parentthread'),
        ),
        migrations.CreateModel(
            name='ParentThreadMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('parent', '학부모'), ('teacher', '교사'), ('system', '시스템')], max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='parentcomm.parentthread')),
            ],
            options={
                'verbose_name': '학부모 문의 메시지',
                'verbose_name_plural': '학부모 문의 메시지',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParentUrgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('late', '지각'), ('absent', '결석'), ('early_leave', '조퇴'), ('other', '기타')], default='other', max_length=20)),
                ('short_message', models.CharField(max_length=20)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_alerts', to='parentcomm.parentcontact')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_urgent_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학부모 긴급 안내',
                'verbose_name_plural': '학부모 긴급 안내',
                'ordering': ['is_acknowledged', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='consultationproposal',
            index=models.Index(fields=['consultation_request', 'status'], name='parentcomm__consult_9b9023_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['proposal', 'starts_at'], name='parentcomm__proposa_988a46_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationslot',
            index=models.Index(fields=['method', 'starts_at'], name='parentcomm__method_22199b_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultationslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='parentcomm_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='parentcontact',
            index=models.Index(fields=['teacher', 'student_name'], name='parentcomm__teacher_8d6eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcontact',
            index=models.Index(fields=['teacher', 'is_active'], name='parentcomm__teacher_29db78_idx'),
        ),
        migrations.AddIndex(
            model_name='parentnotice',
            index=models.Index(fields=['teacher', '-published_at'], name='parentcomm__teacher_7ca28e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentnoticereceipt',
            unique_together={('notice', 'parent_contact')},
        ),
        migrations.AddIndex(
            model_name='parentthread',
            index=models.Index(fields=['teacher', 'status'], name='parentcomm__teacher_9c4ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='parentthread',
            index=models.Index(fields=['parent_contact', 'status'], name='parentcomm__parent__4d2d54_idx'),
        ),
        migrations.AddIndex(
            model_name='parentthread',
            index=models.Index(fields=['teacher', 'severity'], name='parentcomm__teacher_10f52d_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['teacher', 'status'], name='parentcomm__teacher_273a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['parent_contact', 'status'], name='parentcomm__parent__3ea971_idx'),
        ),
        migrations.AddIndex(
            model_name='parenturgentalert',
            index=models.Index(fields=['teacher', 'is_acknowledged', '-created_at'], name='parentcomm__teacher_c5ba38_idx'),
        ),
        migrations.AddIndex(
            model_name='parenturgentalert',
            index=models.Index(fields=['parent_contact', '-created_at'], name='parentcomm__parent__727702_idx'),
        ),
    ]
