# Generated by Django 6.0.1 on 2026-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentcomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentthread',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': '학부모 쪽지 대화', 'verbose_name_plural': '학부모 쪽지 대화'},
        ),
        migrations.AlterModelOptions(
            name='parentthreadmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': '학부모 쪽지 메시지', 'verbose_name_plural': '학부모 쪽지 메시지'},
        ),
        migrations.AddField(
            model_name='parentnotice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='parentcomm/notices/'),
        ),
        migrations.AlterField(
            model_name='parentthread',
            name='category',
            field=models.CharField(default='기타', max_length=50),
        ),
    ]
