# Generated by Django 6.0.1 on 2026-02-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentcomm', '0002_alter_parentthread_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcontact',
            name='contact_email',
        ),
    ]
