# Generated by Django 6.0.1 on 2026-02-25 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffRosterGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_roster_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', 'name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffRosterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='handoff.handoffrostergroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HandoffSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roster_group_name', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', '진행중'), ('closed', '마감')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_sessions', to=settings.AUTH_USER_MODEL)),
                ('roster_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='handoff.handoffrostergroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name_snapshot', models.CharField(max_length=100)),
                ('member_order_snapshot', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', '미수령'), ('received', '수령완료')], default='pending', max_length=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('handoff_type', models.CharField(choices=[('self', '본인 수령'), ('proxy', '대리 수령'), ('placed', '자리 비치')], default='self', max_length=10)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_receipt_updates', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='handoff.handoffrostermember')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='handoff.handoffsession')),
            ],
            options={
                'ordering': ['member_order_snapshot', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='handoffrostergroup',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='handoff_roster_group_owner_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='handoffreceipt',
            constraint=models.UniqueConstraint(fields=('session', 'member'), name='handoff_receipt_session_member_unique'),
        ),
    ]
