# Generated by Django 6.0.1 on 2026-03-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoffrostermember',
            name='affiliation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='handoffrostermember',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='handoffrostermember',
            name='phone_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='handoffrostermember',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
