# Generated by Django 6.0.1 on 2026-04-05 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='새 법률 상담', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_message_at', '-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LegalChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI')], max_length=16)),
                ('body', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('normalized_question', models.CharField(blank=True, default='', max_length=500)),
                ('is_quick_question', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='teacher_law.legalchatsession')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LegalCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(max_length=255)),
                ('law_id', models.CharField(blank=True, default='', max_length=32)),
                ('mst', models.CharField(blank=True, default='', max_length=32)),
                ('article_label', models.CharField(blank=True, default='', max_length=120)),
                ('quote', models.TextField()),
                ('source_url', models.URLField(blank=True, default='')),
                ('fetched_at', models.DateTimeField()),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='teacher_law.legalchatmessage')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LegalQueryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_question', models.TextField()),
                ('normalized_question', models.CharField(blank=True, default='', max_length=500)),
                ('topic', models.CharField(blank=True, default='', max_length=60)),
                ('scope_supported', models.BooleanField(default=True)),
                ('risk_flags_json', models.JSONField(blank=True, default=list)),
                ('candidate_queries_json', models.JSONField(blank=True, default=list)),
                ('selected_laws_json', models.JSONField(blank=True, default=list)),
                ('search_attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('search_result_count', models.PositiveSmallIntegerField(default=0)),
                ('detail_fetch_count', models.PositiveSmallIntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_audits', to='teacher_law.legalchatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_audits', to='teacher_law.legalchatsession')),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_audits', to='teacher_law.legalchatmessage')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='legalchatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='teacher_law_unique_active_session_per_user'),
        ),
    ]
