# Generated by Django 6.0.3 on 2026-04-17 12:55

import django.db.models.deletion
import django.utils.timezone
import doccollab.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version_manager', '0003_alter_documentversion_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', '편집 중'), ('archived', '보관')], default='active', max_length=20)),
                ('source_file', models.FileField(upload_to=doccollab.models.room_source_upload_to)),
                ('source_name', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_rooms', to=settings.AUTH_USER_MODEL)),
                ('mirrored_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doccollab_room', to='version_manager.document')),
            ],
            options={
                'ordering': ['-last_activity_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=doccollab.models.revision_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('export_format', models.CharField(choices=[('source_hwpx', '원본 HWPX'), ('hwp_export', '협업 저장본 HWP')], default='hwp_export', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_revisions', to=settings.AUTH_USER_MODEL)),
                ('mirrored_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doccollab_revisions', to='version_manager.documentversion')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='doccollab.docroom')),
            ],
            options={
                'ordering': ['-revision_number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=80)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('role', models.CharField(choices=[('owner', '소유자'), ('editor', '편집'), ('viewer', '보기')], default='viewer', max_length=20)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_presences', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='doccollab.docroom')),
            ],
            options={
                'ordering': ['display_name', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_kind', models.CharField(choices=[('auto', '자동'), ('manual', '수동')], default='auto', max_length=20)),
                ('command_count', models.PositiveIntegerField(default=0)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_snapshots', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='doccollab.docrevision')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='doccollab.docroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', '운영 중'), ('archived', '보관')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='docroom',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='doccollab.docworkspace'),
        ),
        migrations.CreateModel(
            name='DocMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '소유자'), ('editor', '편집'), ('viewer', '보기')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('active', '활성'), ('disabled', '비활성')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_doc_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='doccollab.docworkspace')),
            ],
            options={
                'ordering': ['workspace__name', 'user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='docrevision',
            index=models.Index(fields=['room', 'created_at'], name='doccollab_d_room_id_b8dbc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docrevision',
            unique_together={('room', 'revision_number')},
        ),
        migrations.AddIndex(
            model_name='docpresence',
            index=models.Index(fields=['room', 'is_connected'], name='doccollab_d_room_id_bf6c14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docpresence',
            unique_together={('room', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='docsnapshot',
            index=models.Index(fields=['room', 'created_at'], name='doccollab_d_room_id_354354_idx'),
        ),
        migrations.AddIndex(
            model_name='docworkspace',
            index=models.Index(fields=['created_by', 'status'], name='doccollab_d_created_fdba5a_idx'),
        ),
        migrations.AddIndex(
            model_name='docroom',
            index=models.Index(fields=['workspace', 'status'], name='doccollab_d_workspa_c9998b_idx'),
        ),
        migrations.AddIndex(
            model_name='docroom',
            index=models.Index(fields=['created_by', 'status'], name='doccollab_d_created_2f8574_idx'),
        ),
        migrations.AddIndex(
            model_name='docmembership',
            index=models.Index(fields=['user', 'status'], name='doccollab_d_user_id_d51243_idx'),
        ),
        migrations.AddIndex(
            model_name='docmembership',
            index=models.Index(fields=['workspace', 'status'], name='doccollab_d_workspa_934714_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docmembership',
            unique_together={('workspace', 'user')},
        ),
    ]
