# Generated by Django 6.0.3 on 2026-04-17 13:22

import doccollab.models
import version_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrevision',
            name='file',
            field=models.FileField(storage=version_manager.models.get_raw_storage, upload_to=doccollab.models.revision_upload_to),
        ),
        migrations.AlterField(
            model_name='docroom',
            name='source_file',
            field=models.FileField(storage=version_manager.models.get_raw_storage, upload_to=doccollab.models.room_source_upload_to),
        ),
    ]
