# Generated by Django 6.0.3 on 2026-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0002_alter_docrevision_file_alter_docroom_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docroom',
            name='source_format',
            field=models.CharField(choices=[('hwp', 'HWP'), ('hwpx', 'HWPX')], default='hwpx', max_length=10),
        ),
        migrations.AlterField(
            model_name='docrevision',
            name='export_format',
            field=models.CharField(choices=[('source_hwp', '원본 HWP'), ('source_hwpx', '원본 HWPX'), ('hwp_export', '협업 저장본 HWP')], default='hwp_export', max_length=20),
        ),
    ]
