# Generated by Django 6.0.3 on 2026-04-17 22:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0003_docroom_source_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocEditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.CharField(blank=True, default='', max_length=80)),
                ('command_type', models.CharField(max_length=40)),
                ('display_name', models.CharField(blank=True, default='', max_length=80)),
                ('summary', models.CharField(max_length=200)),
                ('command_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_events', to='doccollab.docrevision')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_events', to='doccollab.docroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_edit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='doccollab_d_room_id_dcd800_idx'), models.Index(fields=['room', 'command_id'], name='doccollab_d_room_id_11108e_idx'), models.Index(fields=['user', 'created_at'], name='doccollab_d_user_id_f744e8_idx')],
            },
        ),
    ]
