# Generated by Django 6.0.3 on 2026-04-21 04:55

import django.db.models.deletion
import doccollab.models
import version_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0005_alter_docrevision_file_alter_docroom_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docroom',
            name='origin_kind',
            field=models.CharField(choices=[('upload', '업로드'), ('generated_worksheet', '학습지 생성')], default='upload', max_length=30),
        ),
        migrations.AlterField(
            model_name='docroom',
            name='source_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=version_manager.models.get_raw_storage, upload_to=doccollab.models.room_source_upload_to),
        ),
        migrations.AlterField(
            model_name='docroom',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='docroom',
            name='source_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='DocWorksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('summary_text', models.CharField(blank=True, default='', max_length=200)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('search_text', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='deepseek', max_length=30)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('latest_page_count', models.PositiveIntegerField(default=0)),
                ('bootstrap_status', models.CharField(choices=[('pending', '대기'), ('building', '생성 중'), ('ready', '준비 완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('is_library_published', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet', to='doccollab.docroom')),
                ('source_worksheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_worksheets', to='doccollab.docworksheet')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['bootstrap_status', 'is_library_published'], name='doccollab_d_bootstr_cdbfad_idx'), models.Index(fields=['created_at'], name='doccollab_d_created_93b45f_idx')],
            },
        ),
    ]
