# Generated by Django 6.0.3 on 2026-04-24 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0006_docroom_origin_kind_alter_docroom_source_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', '정리 중'), ('ready', '정리 완료'), ('failed', '정리 실패')], default='processing', max_length=20)),
                ('engine', models.CharField(blank=True, default='', max_length=40)),
                ('raw_markdown', models.TextField(blank=True, default='')),
                ('parse_payload', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_analyses', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='doccollab.docroom')),
                ('source_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='doccollab.docrevision')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocAssistantQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('normalized_question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True, default='')),
                ('citations_json', models.JSONField(blank=True, default=list)),
                ('has_insufficient_evidence', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='doccollab-local-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='doccollab.docanalysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doc_assistant_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='docanalysis',
            index=models.Index(fields=['room', 'status'], name='doccollab_d_room_id_55a02d_idx'),
        ),
        migrations.AddIndex(
            model_name='docanalysis',
            index=models.Index(fields=['source_revision', 'status'], name='doccollab_d_source__29ae9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='docanalysis',
            constraint=models.UniqueConstraint(fields=('room', 'source_revision'), name='uniq_doc_analysis_room_revision'),
        ),
        migrations.AddIndex(
            model_name='docassistantquestion',
            index=models.Index(fields=['analysis', 'created_at'], name='doccollab_d_analysi_d931f5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docassistantquestion',
            unique_together={('analysis', 'normalized_question', 'provider')},
        ),
    ]
