# Generated by Django 6.0.3 on 2026-04-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0007_docanalysis_docassistantquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docroom',
            name='origin_kind',
            field=models.CharField(choices=[('upload', '업로드'), ('generated_worksheet', '학습지 생성'), ('ai_draft', 'AI 초안')], default='upload', max_length=30),
        ),
        migrations.CreateModel(
            name='DocGeneratedDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('notice', '안내문'), ('home_letter', '가정통신문'), ('plan', '계획안'), ('minutes', '회의록'), ('report', '보고서'), ('freeform', '자유 문서')], default='freeform', max_length=30)),
                ('request_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('building', '생성 중'), ('ready', '준비 완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(blank=True, default='deepseek', max_length=40)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('latest_page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_draft', to='doccollab.docroom')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'document_type'], name='doccollab_d_status_04d6bd_idx'), models.Index(fields=['created_at'], name='doccollab_d_created_5dbefb_idx')],
            },
        ),
    ]
