# Generated by Django 6.0.3 on 2026-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccollab', '0008_alter_docroom_origin_kind_docgenerateddraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docrevision',
            name='export_format',
            field=models.CharField(choices=[('source_hwp', '원본 HWP'), ('source_hwpx', '원본 HWPX'), ('hwp_export', '협업 저장본 HWP'), ('hwpx_export', '협업 저장본 HWPX')], default='hwpx_export', max_length=20),
        ),
    ]
