# Generated by Django 6.0.1 on 2026-02-21 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeGenerationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('target', models.CharField(choices=[('student_low', '저학년'), ('student_high', '고학년'), ('parent', '학부모')], db_index=True, max_length=20)),
                ('tone', models.CharField(choices=[('formal', '정중'), ('warm', '다정'), ('clear', '명확')], db_index=True, max_length=20)),
                ('topic', models.CharField(choices=[('activity', '활동'), ('event', '행사'), ('safety', '안전'), ('notice', '알림장')], db_index=True, max_length=20)),
                ('keywords_norm', models.TextField()),
                ('context_norm', models.TextField(blank=True)),
                ('signature', models.TextField(db_index=True)),
                ('result_text', models.TextField()),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['target', 'topic', 'tone'], name='noticegen_n_target_1981bc_idx'), models.Index(fields=['prompt_version', 'target', 'topic', 'tone'], name='noticegen_n_prompt__afe217_idx')],
            },
        ),
        migrations.CreateModel(
            name='NoticeGenerationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target', models.CharField(choices=[('student_low', '저학년'), ('student_high', '고학년'), ('parent', '학부모')], db_index=True, max_length=20)),
                ('tone', models.CharField(choices=[('formal', '정중'), ('warm', '다정'), ('clear', '명확')], db_index=True, max_length=20)),
                ('topic', models.CharField(choices=[('activity', '활동'), ('event', '행사'), ('safety', '안전'), ('notice', '알림장')], db_index=True, max_length=20)),
                ('key_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('charged', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('validation_fail', 'Validation Fail'), ('limit_blocked', 'Limit Blocked'), ('cache_hit', 'Cache Hit'), ('llm_requested', 'LLM Requested'), ('llm_success', 'LLM Success'), ('llm_fail', 'LLM Fail')], max_length=32)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noticegen_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'charged'], name='noticegen_n_created_ed4733_idx'), models.Index(fields=['session_key', 'created_at'], name='noticegen_n_session_074c3d_idx'), models.Index(fields=['user', 'created_at'], name='noticegen_n_user_id_94d019_idx')],
            },
        ),
    ]
