# Generated by Django 6.0.3 on 2026-04-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticegen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNoticeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateField(db_index=True, unique=True)),
                ('topic_key', models.CharField(db_index=True, max_length=64)),
                ('context_label', models.CharField(blank=True, max_length=120)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('result_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('fallback', 'Fallback')], db_index=True, default='generating', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('served_count', models.PositiveIntegerField(default=0)),
                ('last_served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recommendation_date'],
                'indexes': [models.Index(fields=['recommendation_date', 'status'], name='noticegen_d_recomme_b12431_idx'), models.Index(fields=['topic_key', 'recommendation_date'], name='noticegen_d_topic_k_4bd581_idx'), models.Index(fields=['content_hash', 'recommendation_date'], name='noticegen_d_content_98afac_idx')],
            },
        ),
    ]
