# Generated by Django 6.0.1 on 2026-01-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('school', '학교 (관리자 및 정교사)'), ('instructor', '강사 (기간제, 돌봄, 늘봄 등)'), ('company', '교육행사업체')], max_length=20, null=True, verbose_name='역할'),
        ),
    ]
