# Generated by Django 6.0.1 on 2026-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='padlet_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Padlet API Key'),
        ),
    ]
