# Generated by Django 6.0.1 on 2026-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 주소')),
                ('visit_date', models.DateField(auto_now_add=True, verbose_name='방문 날짜')),
            ],
            options={
                'verbose_name': '방문자 기록',
                'verbose_name_plural': '방문자 기록',
                'unique_together': {('ip_address', 'visit_date')},
            },
        ),
    ]
