# Generated by Django 6.0.1 on 2026-02-02 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='방문 날짜'),
        ),
    ]
