# Generated by Django 6.0.1 on 2026-02-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_visitorlog_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='visit_date',
            field=models.DateField(auto_now_add=True, verbose_name='방문 날짜'),
        ),
    ]
