# Generated by Django 6.0.1 on 2026-02-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_updated_at_post_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='이메일 (선택)')),
                ('category', models.CharField(choices=[('bug', '버그 신고'), ('suggestion', '제안/건의'), ('other', '기타')], default='other', max_length=20, verbose_name='카테고리')),
                ('message', models.TextField(max_length=1000, verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='처리 완료')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text', models.CharField(blank=True, default='', max_length=200, verbose_name='배너 텍스트')),
                ('banner_active', models.BooleanField(default=False, verbose_name='배너 활성화')),
                ('banner_color', models.CharField(default='#7c3aed', max_length=7, verbose_name='배너 색상 (HEX)')),
                ('banner_link', models.URLField(blank=True, default='', verbose_name='배너 링크 URL')),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
