# Generated by Django 6.0.1 on 2026-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_feedback_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='봇 여부'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
