# Generated by Django 6.0.1 on 2026-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visitorlog_is_bot_visitorlog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='notebook_manual_url',
            field=models.URLField(blank=True, default='', verbose_name='NotebookLM 매뉴얼 URL'),
        ),
    ]
