# Generated by Django 6.0.1 on 2026-02-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_siteconfig_notebook_manual_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='notebook_manual_url',
        ),
    ]
