# Generated by Django 6.0.1 on 2026-02-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_siteconfig_notebook_manual_url'),
        ('products', '0027_servicemanual_manualsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='featured_manuals',
            field=models.ManyToManyField(blank=True, help_text='홈 화면이나 리스트 상단에 노출할 매뉴얼을 선택하세요.', to='products.servicemanual', verbose_name='추천 이용방법'),
        ),
    ]
