# Generated by Django 6.0.1 on 2026-02-16 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_siteconfig_featured_manuals'),
        ('products', '0032_add_v2_home_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('launch', '서비스 실행'), ('search', '검색 클릭'), ('quick_action', '퀵 액션'), ('modal_open', '모달 열기')], default='launch', max_length=20)),
                ('source', models.CharField(choices=[('home_quick', '홈 퀵 액션'), ('home_section', '홈 목적별 섹션'), ('home_game', '홈 게임 배너'), ('home_grid', '홈 전체 서비스'), ('search', '검색 모달'), ('other', '기타')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '서비스 사용 기록',
                'verbose_name_plural': '서비스 사용 기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_produc_user_id_0799f3_idx'), models.Index(fields=['user', 'product'], name='core_produc_user_id_de4d2f_idx')],
            },
        ),
    ]
