# Generated by Django 6.0.1 on 2026-02-25 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_product_usage_log'),
        ('products', '0051_dtsettings_spotlight_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '서비스 즐겨찾기',
                'verbose_name_plural': '서비스 즐겨찾기',
                'ordering': ['pin_order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'pin_order'], name='core_produc_user_id_ac05ec_idx'), models.Index(fields=['user', '-created_at'], name='core_produc_user_id_621bda_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='core_productfavorite_user_product_unique')],
            },
        ),
    ]
