# Generated by Django 6.0.1 on 2026-02-25 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productfavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('privacy', '개인정보/실명 노출'), ('abuse', '욕설/비하'), ('hate', '혐오/차별'), ('spam', '광고/도배'), ('off_topic', '주제 이탈'), ('other', '기타')], default='other', max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '댓글 신고',
                'verbose_name_plural': '댓글 신고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='소스 이름')),
                ('source_type', models.CharField(choices=[('gov', '기관/정부'), ('institute', '교육기관'), ('media', '언론'), ('aggregator', '집계')], default='media', max_length=20, verbose_name='소스 유형')),
                ('url', models.URLField(unique=True, verbose_name='RSS/API URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '뉴스 수집 소스',
                'verbose_name_plural': '뉴스 수집 소스',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('comment', '댓글만 제한'), ('all', '전체 제한')], default='comment', max_length=20)),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='제한 만료일시')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사용자 제재',
                'verbose_name_plural': '사용자 제재',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden_reason',
            field=models.CharField(blank=True, choices=[('', '해당 없음'), ('reports', '신고 누적'), ('admin', '관리자 처리'), ('policy', '운영 정책')], default='', max_length=20, verbose_name='숨김 사유'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='숨김 여부'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 수'),
        ),
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, default='', verbose_name='정규화 링크'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description',
            field=models.TextField(blank=True, default='', verbose_name='OG 설명'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image_url',
            field=models.URLField(blank=True, default='', verbose_name='OG 이미지 링크'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='OG 제목'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('general', '일반'), ('news_link', '뉴스 링크')], default='general', max_length=20, verbose_name='게시글 유형'),
        ),
        migrations.AddField(
            model_name='post',
            name='primary_tag',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='기본 태그'),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='기사 발행일'),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='매체/출처'),
        ),
        migrations.AddField(
            model_name='post',
            name='ranking_score',
            field=models.FloatField(default=0.0, verbose_name='랭킹 점수'),
        ),
        migrations.AddField(
            model_name='post',
            name='secondary_tag',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='보조 태그'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_type',
            field=models.CharField(choices=[('user', '사용자'), ('gov', '기관/정부'), ('institute', '교육기관'), ('media', '언론'), ('aggregator', '집계')], default='user', max_length=20, verbose_name='콘텐츠 출처 유형'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='원문 링크'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['is_hidden', '-created_at'], name='core_commen_is_hidd_737c1e_idx'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_entries', to='core.comment'),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='news_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.newssource'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-created_at'], name='core_post_post_ty_03e4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-ranking_score'], name='core_post_post_ty_ce2cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['publisher', '-created_at'], name='core_post_publish_b5c871_idx'),
        ),
        migrations.AddField(
            model_name='usermoderation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_moderations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermoderation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['reason', '-created_at'], name='core_commen_reason_69edbb_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['comment', '-created_at'], name='core_commen_comment_e8e61f_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reporter'), name='core_commentreport_comment_reporter_unique'),
        ),
        migrations.AddIndex(
            model_name='usermoderation',
            index=models.Index(fields=['user', 'scope'], name='core_usermo_user_id_dc32c7_idx'),
        ),
        migrations.AddIndex(
            model_name='usermoderation',
            index=models.Index(fields=['until'], name='core_usermo_until_9af8dc_idx'),
        ),
    ]
