# Generated by Django 6.0.1 on 2026-02-25 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_commentreport_newssource_usermoderation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approval_status',
            field=models.CharField(choices=[('approved', '게시중'), ('pending', '검토 대기'), ('rejected', '반려')], default='approved', max_length=20, verbose_name='게시 승인 상태'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토 일시'),
        ),
        migrations.AddField(
            model_name='post',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='RSS/API URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='정규화 링크'),
        ),
        migrations.AlterField(
            model_name='post',
            name='og_image_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='OG 이미지 링크'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000, verbose_name='원문 링크'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['approval_status', '-created_at'], name='core_post_approva_3fa794_idx'),
        ),
    ]
