# Generated by Django 6.0.1 on 2026-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_post_approval_status_post_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='켜면 관리자(superuser) 외 사용자에게 점검 페이지(503)를 표시합니다.', verbose_name='점검 모드'),
        ),
    ]
