# Generated by Django 6.0.1 on 2026-02-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_siteconfig_maintenance_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('general', '일반'), ('notice', '공지'), ('news_link', '뉴스 링크')], default='general', max_length=20, verbose_name='게시글 유형'),
        ),
    ]
