# Generated by Django 6.0.7 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='상단 노출 시작'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='상단 노출 종료'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['featured_from', 'featured_until'], name='core_post_feature_8fcae1_idx'),
        ),
    ]
