# Generated by Django 6.0.1 on 2026-03-14 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_productworkbenchbundle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolicyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='direct', max_length=32, verbose_name='로그인 제공사')),
                ('terms_version', models.CharField(max_length=32, verbose_name='이용약관 버전')),
                ('privacy_version', models.CharField(max_length=32, verbose_name='개인정보처리방침 버전')),
                ('agreed_at', models.DateTimeField(verbose_name='동의 일시')),
                ('agreement_source', models.CharField(choices=[('social_first_login', '소셜 첫 로그인'), ('social_reconsent', '소셜 재동의'), ('required_gate', '필수 동의 게이트')], default='required_gate', max_length=32, verbose_name='동의 경로')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '정책 동의 기록',
                'verbose_name_plural': '정책 동의 기록',
                'ordering': ['-agreed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='userpolicyconsent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userpolicyconsent',
            index=models.Index(fields=['user', '-agreed_at'], name='core_userpo_user_id_73d398_idx'),
        ),
        migrations.AddIndex(
            model_name='userpolicyconsent',
            index=models.Index(fields=['provider', '-agreed_at'], name='core_userpo_provide_b51272_idx'),
        ),
        migrations.AddIndex(
            model_name='userpolicyconsent',
            index=models.Index(fields=['terms_version', 'privacy_version'], name='core_userpo_terms_v_87d1b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpolicyconsent',
            constraint=models.UniqueConstraint(fields=('user', 'terms_version', 'privacy_version'), name='core_policyconsent_user_terms_privacy_unique'),
        ),
    ]
