# Generated by Django 6.0.1 on 2026-03-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_post_notice_pin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='pinned_notice_expanded',
            field=models.BooleanField(default=False, verbose_name='상단 고정 공지 펼침 상태'),
        ),
    ]
