# Generated by Django 6.0.1 on 2026-03-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userprofile_pinned_notice_expanded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key',
        ),
    ]
