# Generated by Django 6.0.1 on 2026-03-20 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_userprofile_gemini_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMarketingEmailConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_version', models.CharField(default='2026-03-20.1', max_length=32, verbose_name='동의 문구 버전')),
                ('consented_at', models.DateTimeField(verbose_name='동의 시각')),
                ('consent_source', models.CharField(choices=[('social_signup', '소셜 가입'), ('admin_update', '관리자 수정')], default='social_signup', max_length=32, verbose_name='동의 경로')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='철회 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_email_consent', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이메일 안내 수신 동의',
                'verbose_name_plural': '이메일 안내 수신 동의',
                'ordering': ['-consented_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='usermarketingemailconsent',
            index=models.Index(fields=['revoked_at', '-consented_at'], name='core_userma_revoked_5d3478_idx'),
        ),
        migrations.AddIndex(
            model_name='usermarketingemailconsent',
            index=models.Index(fields=['consent_source', '-consented_at'], name='core_userma_consent_a201ae_idx'),
        ),
    ]
