# Generated by Django 6.0.1 on 2026-03-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_marketing_email_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recent_reservation_school_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='최근 연 학교 예약판'),
        ),
    ]
