# Generated by Django 6.0.1 on 2026-04-05 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_visitorlog_identity_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBuddyDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('point_total', models.PositiveIntegerField(default=0)),
                ('awarded_section_keys', models.JSONField(blank=True, default=list)),
                ('first_launch_awarded', models.BooleanField(default=False)),
                ('draw_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '교실 메이트 일일 진행',
                'verbose_name_plural': '교실 메이트 일일 진행',
            },
        ),
        migrations.CreateModel(
            name='TeacherBuddyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_buddy_key', models.CharField(blank=True, default='', max_length=60)),
                ('starter_granted_at', models.DateTimeField(blank=True, null=True)),
                ('draw_token_count', models.PositiveIntegerField(default=0)),
                ('total_points_earned', models.PositiveIntegerField(default=0)),
                ('collection_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_home_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '교실 메이트 상태',
                'verbose_name_plural': '교실 메이트 상태',
            },
        ),
        migrations.CreateModel(
            name='TeacherBuddyUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddy_key', models.CharField(max_length=60)),
                ('rarity', models.CharField(max_length=20)),
                ('obtained_via', models.CharField(choices=[('starter', '시작 지급'), ('draw', '뽑기')], max_length=20)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '교실 메이트 언락',
                'verbose_name_plural': '교실 메이트 언락',
            },
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='core_post_feature_433f55_idx',
            old_name='core_post_feature_8fcae1_idx',
        ),
        migrations.RenameIndex(
            model_name='productworkbenchbundle',
            new_name='core_produc_user_id_7babf2_idx',
            old_name='core_produc_user_id_5e220c_idx',
        ),
        migrations.RenameIndex(
            model_name='productworkbenchbundle',
            new_name='core_produc_user_id_07634a_idx',
            old_name='core_produc_user_id_f8fddb_idx',
        ),
        migrations.AlterField(
            model_name='productusagelog',
            name='source',
            field=models.CharField(choices=[('home_quick', '홈 퀵 액션'), ('home_section', '홈 목적별 섹션'), ('home_game', '홈 게임 배너'), ('home_grid', '홈 전체 서비스'), ('home_mini', '홈 미니 앱'), ('search', '검색 모달'), ('other', '기타')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherbuddydailyprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_buddy_daily_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherbuddystate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_buddy_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherbuddyunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_buddy_unlocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacherbuddydailyprogress',
            index=models.Index(fields=['user', '-activity_date'], name='core_teache_user_id_7545d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherbuddydailyprogress',
            constraint=models.UniqueConstraint(fields=('user', 'activity_date'), name='core_teacherbuddydailyprogress_user_date_unique'),
        ),
        migrations.AddIndex(
            model_name='teacherbuddyunlock',
            index=models.Index(fields=['user', '-obtained_at'], name='core_teache_user_id_9d6c81_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherbuddyunlock',
            index=models.Index(fields=['user', 'rarity'], name='core_teache_user_id_d4e8bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherbuddyunlock',
            constraint=models.UniqueConstraint(fields=('user', 'buddy_key'), name='core_teacherbuddyunlock_user_buddy_unique'),
        ),
    ]
