# Generated by Django 6.0.3 on 2026-04-07 04:39

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_teacherbuddy_phase4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBuddyGiftCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.generate_teacher_buddy_coupon_code, max_length=24, unique=True, verbose_name='쿠폰 코드')),
                ('normalized_code', models.CharField(editable=False, max_length=24, unique=True, verbose_name='정규화 쿠폰 코드')),
                ('token_amount', models.PositiveIntegerField(default=1, verbose_name='지급 뽑기권 수')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 가능')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시각')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='사용 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_teacher_buddy_coupons', to=settings.AUTH_USER_MODEL, verbose_name='발급자')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_teacher_buddy_coupons', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '교실 메이트 선물 쿠폰',
                'verbose_name_plural': '교실 메이트 선물 쿠폰',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teacherbuddygiftcoupon',
            index=models.Index(fields=['normalized_code'], name='core_teache_normali_6b9754_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherbuddygiftcoupon',
            index=models.Index(fields=['is_active', '-created_at'], name='core_teache_is_acti_195ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherbuddygiftcoupon',
            index=models.Index(fields=['redeemed_at'], name='core_teache_redeeme_ffcd79_idx'),
        ),
    ]
