# Generated by Django 6.0.3 on 2026-04-10 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_teacherbuddygiftcoupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('category', models.CharField(choices=[('daily_login', '일일 로그인'), ('service_use', '메뉴/서비스 사용'), ('request_sent', '서명·동의 요청 발송')], max_length=32)),
                ('source_key', models.CharField(max_length=120)),
                ('points', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_backfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '교사 활동 지수 이벤트',
                'verbose_name_plural': '교사 활동 지수 이벤트',
                'ordering': ['-activity_date', '-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherActivityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('active_day_count', models.PositiveIntegerField(default=0)),
                ('last_earned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '교사 활동 지수 프로필',
                'verbose_name_plural': '교사 활동 지수 프로필',
            },
        ),
        migrations.AddField(
            model_name='teacheractivityevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacheractivityprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activity_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacheractivityevent',
            index=models.Index(fields=['user', '-activity_date'], name='core_teache_user_id_2ec935_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheractivityevent',
            index=models.Index(fields=['user', 'category', '-activity_date'], name='core_teache_user_id_b5a95f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheractivityevent',
            index=models.Index(fields=['user', 'source_key'], name='core_teache_user_id_17a0ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacheractivityevent',
            constraint=models.UniqueConstraint(fields=('user', 'activity_date', 'category', 'source_key'), name='core_teacheractivityevent_user_date_category_source_unique'),
        ),
    ]
