# Generated by Django 6.0.3 on 2026-04-10 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_teacherbuddygiftcoupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(db_index=True, max_length=80, verbose_name='방문 식별자')),
                ('identity_type', models.CharField(choices=[('user', '로그인 사용자'), ('session', '브라우저 세션'), ('bot', '봇'), ('ip', '기존 IP')], default='session', max_length=20, verbose_name='식별 기준')),
                ('is_bot', models.BooleanField(default=False, verbose_name='봇 여부')),
                ('path', models.CharField(max_length=255, verbose_name='경로')),
                ('route_name', models.CharField(blank=True, max_length=120, verbose_name='라우트 이름')),
                ('view_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='조회 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_view_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '페이지 조회 기록',
                'verbose_name_plural': '페이지 조회 기록',
            },
        ),
        migrations.AddIndex(
            model_name='pageviewlog',
            index=models.Index(fields=['view_date', 'is_bot'], name='core_pagevi_view_da_0f6d04_idx'),
        ),
        migrations.AddIndex(
            model_name='pageviewlog',
            index=models.Index(fields=['route_name', 'view_date'], name='core_pagevi_route_n_15a7bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageviewlog',
            constraint=models.UniqueConstraint(fields=('view_date', 'visitor_key', 'path'), name='core_unique_page_view_per_day'),
        ),
    ]
