# Generated by Django 6.0.3 on 2026-04-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_pageviewlog'),
        ('core', '0038_teacheractivityevent_teacheractivityprofile_and_more'),
    ]

    operations = [
    ]
