# Generated by Django 6.0.3 on 2026-04-18 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260410_2049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAgentQuotaBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveIntegerField(default=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('source_thread_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI 교무비서 한도 증액',
                'verbose_name_plural': 'AI 교무비서 한도 증액',
                'ordering': ['-ends_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HomeAgentQuotaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_limit_reached_at', models.DateTimeField(blank=True, null=True)),
                ('prompt_dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 교무비서 한도 상태',
                'verbose_name_plural': 'AI 교무비서 한도 상태',
            },
        ),
        migrations.CreateModel(
            name='HomeAgentUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField(db_index=True)),
                ('mode_key', models.CharField(blank=True, default='', max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI 교무비서 사용 기록',
                'verbose_name_plural': 'AI 교무비서 사용 기록',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='teacherbuddyskinunlock',
            options={'verbose_name': '교실 메이트 스킨 언락', 'verbose_name_plural': '교실 메이트 스킨 언락'},
        ),
        migrations.RemoveConstraint(
            model_name='teacherbuddyskinunlock',
            name='uniq_teacher_buddy_skin_unlock',
        ),
        migrations.RenameIndex(
            model_name='teacherbuddyskinunlock',
            new_name='core_teache_user_id_0faa55_idx',
            old_name='core_tb_skin_user_buddy_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherbuddyskinunlock',
            new_name='core_teache_user_id_03d85b_idx',
            old_name='core_tb_skin_user_time_idx',
        ),
        migrations.AlterField(
            model_name='teacherbuddyskinunlock',
            name='obtained_via',
            field=models.CharField(choices=[('dust', '스타일 조각')], default='dust', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='teacherbuddyskinunlock',
            constraint=models.UniqueConstraint(fields=('user', 'skin_key'), name='core_teacherbuddyskinunlock_user_skin_unique'),
        ),
        migrations.AddField(
            model_name='homeagentquotaboost',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_home_agent_quota_boosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeagentquotaboost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_agent_quota_boosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeagentquotastate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_agent_quota_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homeagentusagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_agent_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='homeagentquotaboost',
            index=models.Index(fields=['user', 'ends_at'], name='core_homeag_user_id_885043_idx'),
        ),
        migrations.AddIndex(
            model_name='homeagentquotaboost',
            index=models.Index(fields=['user', '-created_at'], name='core_homeag_user_id_57f238_idx'),
        ),
        migrations.AddIndex(
            model_name='homeagentusagelog',
            index=models.Index(fields=['user', 'usage_date'], name='core_homeag_user_id_1a66b7_idx'),
        ),
        migrations.AddIndex(
            model_name='homeagentusagelog',
            index=models.Index(fields=['user', '-created_at'], name='core_homeag_user_id_2b28c7_idx'),
        ),
    ]
