# Generated by Django 6.0.1 on 2026-01-25 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English name e.g. Ja', max_length=10)),
                ('character', models.CharField(help_text='Hanja e.g. 子', max_length=2)),
                ('polarity', models.CharField(choices=[('yang', 'Yang'), ('yin', 'Yin')], max_length=10)),
                ('element', models.CharField(choices=[('wood', 'Wood'), ('fire', 'Fire'), ('earth', 'Earth'), ('metal', 'Metal'), ('water', 'Water')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English name e.g. Gap', max_length=10)),
                ('character', models.CharField(help_text='Hanja e.g. 甲', max_length=2)),
                ('polarity', models.CharField(choices=[('yang', 'Yang'), ('yin', 'Yin')], max_length=10)),
                ('element', models.CharField(choices=[('wood', 'Wood'), ('fire', 'Fire'), ('earth', 'Earth'), ('metal', 'Metal'), ('water', 'Water')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SajuProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date_gregorian', models.DateTimeField(help_text='Gregorian Birth Date and Time')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('birth_city', models.CharField(help_text='City of Birth for Time Correction', max_length=100)),
                ('longitude', models.FloatField(help_text='Longitude for True Solar Time calculation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saju_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SixtyJiazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English name e.g. GapJa', max_length=20)),
                ('na_yin_element', models.CharField(blank=True, help_text='Na-Yin Element (납음오행)', max_length=20, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fortune.branch')),
                ('stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fortune.stem')),
            ],
            options={
                'verbose_name_plural': 'Sixty Jiazi',
            },
        ),
        migrations.CreateModel(
            name='NatalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_master_strength', models.CharField(choices=[('ExtremeWeak', 'ExtremeWeak'), ('Weak', 'Weak'), ('Balanced', 'Balanced'), ('Strong', 'Strong'), ('ExtremeStrong', 'ExtremeStrong')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_branches', to='fortune.branch')),
                ('hour_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_branches', to='fortune.branch')),
                ('month_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_branches', to='fortune.branch')),
                ('year_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_branches', to='fortune.branch')),
                ('saju_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natal_charts', to='fortune.sajuprofile')),
                ('day_stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_stems', to='fortune.stem')),
                ('hour_stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_stems', to='fortune.stem')),
                ('month_stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month_stems', to='fortune.stem')),
                ('year_stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_stems', to='fortune.stem')),
            ],
        ),
    ]
