# Generated by Django 6.0.1 on 2026-01-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpretationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('TEN_GOD', 'Ten Gods Interaction'), ('DM_STRENGTH', 'Day Master Strength'), ('GANJI', 'Specific Pillar')], max_length=20)),
                ('element_1', models.CharField(blank=True, help_text='Subject (e.g. Day Master)', max_length=50)),
                ('element_2', models.CharField(blank=True, help_text='Object (e.g. Month Branch or Ten God)', max_length=50)),
                ('condition_json', models.JSONField(blank=True, default=dict, help_text="e.g. {'strength': 'Weak'}")),
                ('base_interpretation', models.TextField(help_text='Core fact for LLM')),
                ('advice_template', models.TextField(blank=True)),
                ('severity_score', models.IntegerField(default=5)),
            ],
        ),
    ]
