# Generated by Django 6.0.1 on 2026-01-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0002_interpretationrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('teacher', '교사 모드'), ('general', '일반 모드'), ('daily', '일진 모드')], max_length=20)),
                ('natal_chart', models.JSONField(help_text='저장 당시의 사주 원국 간지')),
                ('result_text', models.TextField(help_text='AI가 생성한 분석 결과 내용')),
                ('target_date', models.DateField(blank=True, help_text='일진 모드인 경우 해당 날짜', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_fortunes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
