# Generated by Django 6.0.1 on 2026-02-03 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0004_zooresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSajuProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(help_text='프로필 이름 (예: 나, 엄마, 친구)', max_length=20)),
                ('person_name', models.CharField(help_text='실제 이름', max_length=20)),
                ('gender', models.CharField(choices=[('male', '남자'), ('female', '여자')], max_length=10)),
                ('birth_year', models.IntegerField()),
                ('birth_month', models.IntegerField()),
                ('birth_day', models.IntegerField()),
                ('birth_hour', models.IntegerField(blank=True, null=True)),
                ('birth_minute', models.IntegerField(blank=True, null=True)),
                ('calendar_type', models.CharField(choices=[('solar', '양력'), ('lunar', '음력')], default='solar', max_length=10)),
                ('natal_chart', models.JSONField(blank=True, help_text='계산된 사주 팔자', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='기본 프로필 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saju_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
                'unique_together': {('user', 'profile_name')},
            },
        ),
        migrations.CreateModel(
            name='DailyFortuneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_logs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fortune.usersajuprofile')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(help_text='날짜 라벨 (예: 시험일, 생일)', max_length=50)),
                ('memo', models.TextField(blank=True, help_text='메모')),
                ('color', models.CharField(default='indigo', help_text='UI 색상', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_dates', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_dates', to='fortune.usersajuprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date', 'label')},
            },
        ),
    ]
