# Generated by Django 6.0.1 on 2026-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0005_usersajuprofile_dailyfortunelog_favoritedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortuneresult',
            name='natal_hash',
            field=models.CharField(blank=True, db_index=True, help_text='사주 명식 고유 해시 (캐싱용)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fortuneresult',
            name='topic',
            field=models.CharField(blank=True, choices=[('total', '전체'), ('personality', '성격'), ('wealth', '재물'), ('career', '직업'), ('compatibility', '연애/인연'), ('daily', '일진')], help_text='분석 주제', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fortuneresult',
            name='mode',
            field=models.CharField(choices=[('teacher', '교사 모드'), ('general', '일반 모드'), ('daily', '일진 모드')], default='general', max_length=20),
        ),
    ]
