# Generated by Django 6.0.1 on 2026-02-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0006_fortuneresult_natal_hash_fortuneresult_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortuneresult',
            name='topic',
            field=models.CharField(blank=True, choices=[('total', '전체'), ('personality', '성격'), ('wealth', '재물'), ('career', '직업'), ('teacher', '교직 운세'), ('compatibility', '연애/인연'), ('daily', '일진')], help_text='분석 주제', max_length=20, null=True),
        ),
    ]
