# Generated by Django 6.0.1 on 2026-02-03 11:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0007_alter_fortuneresult_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fortuneresult',
            unique_together={('user', 'natal_hash', 'topic')},
        ),
    ]
