# Generated by Django 6.0.1 on 2026-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0008_clear_old_fortune_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortuneresult',
            name='natal_hash',
        ),
        migrations.RemoveField(
            model_name='fortuneresult',
            name='topic',
        ),
        migrations.AlterField(
            model_name='fortuneresult',
            name='mode',
            field=models.CharField(choices=[('teacher', '교사 모드'), ('general', '일반 모드'), ('daily', '일진 모드')], max_length=20),
        ),
    ]
