# Generated by Django 6.0.1 on 2026-02-04 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0008_alter_fortuneresult_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fortuneresult',
            name='user_context_hash',
            field=models.CharField(blank=True, db_index=True, help_text='이름+성별+생년월일시 포함 해시 (개인화 캐싱용)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fortuneresult',
            name='mode',
            field=models.CharField(choices=[('teacher', '교사 모드'), ('general', '일반 모드'), ('daily', '일진 모드')], db_index=True, default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyFortuneCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natal_hash', models.CharField(db_index=True, help_text='사주 명식 고유 해시', max_length=64)),
                ('mode', models.CharField(choices=[('teacher', '교사 모드'), ('general', '일반 모드')], db_index=True, help_text='모드별로 다른 일진 프롬프트 사용', max_length=20)),
                ('target_date', models.DateField(db_index=True, help_text='해당 날짜')),
                ('result_text', models.TextField(help_text='AI 생성 일진 분석 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_fortune_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'natal_hash', 'mode', 'target_date'], name='fortune_dai_user_id_05b7c4_idx')],
                'unique_together': {('user', 'natal_hash', 'mode', 'target_date')},
            },
        ),
    ]
