# Generated by Django 6.0.1 on 2026-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0009_enhance_cache_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfortunecache',
            name='mode',
            field=models.CharField(choices=[('teacher', '교사 모드'), ('general', '일반 모드')], db_index=True, help_text='분석 모드 (교사/일반)', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyfortunecache',
            name='result_text',
            field=models.TextField(help_text='AI 생성 일진 결과'),
        ),
        migrations.AlterField(
            model_name='dailyfortunecache',
            name='target_date',
            field=models.DateField(db_index=True, help_text='일진 날짜'),
        ),
    ]
