# Generated by Django 6.0.1 on 2026-03-12 01:47

import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


def cleanup_legacy_personal_fortune_data(apps, schema_editor):
    FavoriteDate = apps.get_model('fortune', 'FavoriteDate')
    DailyFortuneLog = apps.get_model('fortune', 'DailyFortuneLog')
    FortuneResult = apps.get_model('fortune', 'FortuneResult')
    ChatMessage = apps.get_model('fortune', 'ChatMessage')
    ChatSession = apps.get_model('fortune', 'ChatSession')
    UserSajuProfile = apps.get_model('fortune', 'UserSajuProfile')
    NatalChart = apps.get_model('fortune', 'NatalChart')
    SajuProfile = apps.get_model('fortune', 'SajuProfile')

    FavoriteDate.objects.exclude(profile=None).update(profile=None)
    DailyFortuneLog.objects.exclude(profile=None).update(profile=None)

    line_patterns = (
        re.compile(r'^\s*-?\s*생일\s*[:：].*$', re.IGNORECASE),
        re.compile(r'^\s*Birth Datetime\s*:\s*.*$', re.IGNORECASE),
        re.compile(r'^\s*-?\s*[년월일시]주\s*[:：].*$', re.IGNORECASE),
        re.compile(r'^\s*-?\s*(사주|팔자|원국|명식)\s*[:：].*$', re.IGNORECASE),
    )
    inline_patterns = (
        re.compile(r'\d{4}\s*년\s*\d{1,2}\s*월\s*\d{1,2}\s*일(?:\s*\([^)]*\))?(?:\s*\d{1,2}\s*시(?:\s*\d{1,2}\s*분)?)?'),
        re.compile(r'\d{4}-\d{2}-\d{2}(?:\s+\d{2}:\d{2})?'),
        re.compile(r'([년월일시]주)\s*[:：]?\s*[갑을병정무기경신임계][자축인묘진사오미신유술해]'),
        re.compile(r'(?:[甲乙丙丁戊己庚辛壬癸갑을병정무기경신임계][子丑寅卯辰巳午未申酉戌亥자축인묘진사오미신유술해]\s*){2,4}'),
    )

    for result in FortuneResult.objects.all():
        lines = []
        for raw_line in (result.result_text or '').splitlines():
            if any(pattern.match(raw_line) for pattern in line_patterns):
                continue
            cleaned = raw_line
            for pattern in inline_patterns:
                cleaned = pattern.sub('[비공개]', cleaned)
            lines.append(cleaned)
        scrubbed_text = re.sub(r'\n{3,}', '\n\n', '\n'.join(lines)).strip()
        if scrubbed_text:
            result.result_text = scrubbed_text
            result.natal_chart = None
            result.save(update_fields=['result_text', 'natal_chart'])
        else:
            result.delete()

    ChatMessage.objects.all().delete()
    ChatSession.objects.all().delete()
    UserSajuProfile.objects.all().delete()
    NatalChart.objects.all().delete()
    SajuProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0010_chatsession_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedate',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_dates', to='fortune.usersajuprofile'),
        ),
        migrations.AlterField(
            model_name='fortuneresult',
            name='natal_chart',
            field=models.JSONField(blank=True, help_text='레거시 필드(개인정보 비저장 전환 후 사용 안 함)', null=True),
        ),
        migrations.CreateModel(
            name='FortunePseudonymousCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('full', '전체 사주'), ('daily', '일진')], max_length=10)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result_text', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_pseudonymous_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='fortune_for_expires_ab440d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'purpose', 'fingerprint'), name='fortune_cache_user_purpose_fingerprint_uniq')],
            },
        ),
        migrations.RunPython(cleanup_legacy_personal_fortune_data, migrations.RunPython.noop),
    ]
