# Generated by Django 6.0.1 on 2026-02-14 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='diff_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='diff_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='diff_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='missing_protected_phrases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='DocumentShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_share_links', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='version_manager.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProtectedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protected_phrases', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_phrases', to='version_manager.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'phrase'), name='uniq_document_protected_phrase')],
            },
        ),
    ]
