# Generated by Django 6.0.1 on 2026-02-14 14:40

import version_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manager', '0002_documentversion_diff_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='upload',
            field=models.FileField(storage=version_manager.models.get_raw_storage, upload_to=version_manager.models.document_version_upload_to),
        ),
    ]
