# Generated by Django 6.0.3 on 2026-04-18 14:32

import version_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_manager', '0003_alter_documentversion_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='upload',
            field=models.FileField(max_length=500, storage=version_manager.models.get_raw_storage, upload_to=version_manager.models.document_version_upload_to),
        ),
    ]
