# Generated by Django 6.0.1 on 2026-01-30 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SsambtiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(help_text='e.g. ENFP', max_length=4)),
                ('animal_name', models.CharField(help_text='e.g. 해달', max_length=50)),
                ('result_text', models.TextField(help_text='AI가 생성한 분석 결과 내용')),
                ('answers_json', models.JSONField(blank=True, help_text='사용자가 선택한 답변들', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssambti_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '쌤BTI 결과',
                'verbose_name_plural': '쌤BTI 결과 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
