# Generated by Django 6.0.1 on 2026-02-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0002_eventexternalmap_googleaccount_googlesyncstate'),
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start_time', 'id']},
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('class_readonly', '학급 공유'), ('teacher_only', '교사 전용')], default='class_readonly', max_length=20),
        ),
        migrations.AddField(
            model_name='eventexternalmap',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_maps', to='classcalendar.googleaccount'),
        ),
        migrations.AddField(
            model_name='eventexternalmap',
            name='google_calendar_id',
            field=models.CharField(default='primary', max_length=255),
        ),
        migrations.AddField(
            model_name='googlesyncstate',
            name='google_calendar_id',
            field=models.CharField(default='primary', max_length=255),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('local', '로컬'), ('google', '구글')], default='local', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventexternalmap',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_maps', to='classcalendar.calendarevent'),
        ),
        migrations.AlterField(
            model_name='eventexternalmap',
            name='google_event_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='credentials',
            field=models.JSONField(default=dict, help_text='OAuth2 credentials dict'),
        ),
        migrations.AlterField(
            model_name='googlesyncstate',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_states', to='classcalendar.googleaccount'),
        ),
        migrations.AlterField(
            model_name='googlesyncstate',
            name='sync_token',
            field=models.TextField(blank=True, help_text='Token for incremental sync', null=True),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['author', 'start_time'], name='classcalend_author__fe5b4e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['classroom', 'start_time'], name='classcalend_classro_bf579b_idx'),
        ),
        migrations.AddIndex(
            model_name='googlesyncstate',
            index=models.Index(fields=['account', 'last_sync'], name='classcalend_account_7feea4_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventexternalmap',
            constraint=models.UniqueConstraint(fields=('account', 'google_calendar_id', 'google_event_id'), name='uniq_google_event_map'),
        ),
        migrations.AddConstraint(
            model_name='eventexternalmap',
            constraint=models.UniqueConstraint(fields=('event', 'account', 'google_calendar_id'), name='uniq_event_calendar_map'),
        ),
        migrations.AddConstraint(
            model_name='googlesyncstate',
            constraint=models.UniqueConstraint(fields=('account', 'google_calendar_id'), name='uniq_google_sync_state_per_calendar'),
        ),
    ]
