# Generated by Django 6.0.1 on 2026-02-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0003_alter_calendarevent_options_calendarevent_visibility_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventexternalmap',
            name='uniq_google_event_map',
        ),
        migrations.RemoveConstraint(
            model_name='eventexternalmap',
            name='uniq_event_calendar_map',
        ),
        migrations.RemoveField(
            model_name='googleaccount',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='googlesyncstate',
            name='classcalend_account_7feea4_idx',
        ),
        migrations.RemoveConstraint(
            model_name='googlesyncstate',
            name='uniq_google_sync_state_per_calendar',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('local', '로컬')], default='local', max_length=20),
        ),
        migrations.RemoveField(
            model_name='googlesyncstate',
            name='account',
        ),
        migrations.DeleteModel(
            name='EventExternalMap',
        ),
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
        migrations.DeleteModel(
            name='GoogleSyncState',
        ),
    ]
