# Generated by Django 6.0.1 on 2026-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0004_remove_eventexternalmap_uniq_google_event_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('class_readonly', '학급 공유'), ('teacher_only', '교사 전용')], default='teacher_only', max_length=20),
        ),
    ]
