# Generated by Django 6.0.1 on 2026-02-22 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0005_alter_calendarevent_visibility'),
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='integration_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='integration_source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['author', 'integration_source'], name='classcalend_author__28518d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['author', 'integration_source', 'integration_key'], name='classcalend_author__a6abf9_idx'),
        ),
    ]
