# Generated by Django 6.0.1 on 2026-02-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classcalendar", "0006_calendarevent_integration_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarIntegrationSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("collect_deadline_enabled", models.BooleanField(default=True)),
                ("consent_expiry_enabled", models.BooleanField(default=True)),
                ("reservation_enabled", models.BooleanField(default=True)),
                ("signatures_training_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_integration_setting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "캘린더 연동 설정",
                "verbose_name_plural": "캘린더 연동 설정",
            },
        ),
    ]
