# Generated by Django 6.0.1 on 2026-02-25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcalendar", "0007_calendarintegrationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarintegrationsetting",
            name="share_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendarintegrationsetting",
            name="share_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
