# Generated by Django 6.0.1 on 2026-02-25 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0008_calendarintegrationsetting_share_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_collaborators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '캘린더 협업자',
                'verbose_name_plural': '캘린더 협업자',
                'constraints': [models.CheckConstraint(condition=models.Q(('owner', models.F('collaborator')), _negated=True), name='calendar_collaborator_owner_not_self')],
                'unique_together': {('owner', 'collaborator')},
            },
        ),
    ]
