# Generated by Django 6.0.1 on 2026-03-04 14:15

import classcalendar.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0010_calendarintegrationsetting_retention_notice_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMessageCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('source_hint', models.CharField(blank=True, default='unknown', max_length=30)),
                ('parse_status', models.CharField(choices=[('parsed', 'Parsed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='needs_review', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extracted_title', models.CharField(blank=True, default='', max_length=200)),
                ('extracted_start_time', models.DateTimeField(blank=True, null=True)),
                ('extracted_end_time', models.DateTimeField(blank=True, null=True)),
                ('extracted_is_all_day', models.BooleanField(default=False)),
                ('extracted_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='', max_length=10)),
                ('extracted_todo_summary', models.TextField(blank=True, default='')),
                ('parse_payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(default=classcalendar.models._default_idempotency_key, max_length=64)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_message_captures', to=settings.AUTH_USER_MODEL)),
                ('committed_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_captures', to='classcalendar.calendarevent')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarMessageCaptureAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='classcalendar/message_capture_attachments/%Y/%m/%d')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('is_selected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classcalendar.calendarmessagecapture')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_message_capture_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='classcalendar/event_attachments/%Y/%m/%d')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='classcalendar.calendarevent')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event_attachments', to=settings.AUTH_USER_MODEL)),
                ('source_capture_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attachments', to='classcalendar.calendarmessagecaptureattachment')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventSyncTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('sheetbook_schedule', 'Sheetbook Schedule')], default='sheetbook_schedule', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('target_ref', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='classcalendar.calendarevent')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='classcalend_status_5d40d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'target_type'), name='calendar_event_sync_task_unique_event_target')],
            },
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapture',
            index=models.Index(fields=['author', 'created_at'], name='classcalend_author__d1cd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapture',
            index=models.Index(fields=['author', 'parse_status', 'created_at'], name='classcalend_author__d46400_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarmessagecapture',
            constraint=models.UniqueConstraint(fields=('author', 'idempotency_key'), name='calendar_message_capture_unique_idempotency_per_author'),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecaptureattachment',
            index=models.Index(fields=['capture', 'created_at'], name='classcalend_capture_c23696_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventattachment',
            index=models.Index(fields=['event', 'sort_order'], name='classcalend_event_i_cf4273_idx'),
        ),
    ]
