# Generated by Django 6.0.1 on 2026-03-08 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0011_calendarmessagecapture_and_more'),
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='confirmed_item_type',
            field=models.CharField(blank=True, choices=[('event', 'Event'), ('task', 'Task'), ('manual_skip', 'Manual Skip')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='decision_source',
            field=models.CharField(choices=[('rule', 'Rule'), ('rule_ml', 'Rule + ML'), ('manual', 'Manual')], default='rule', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='edit_diff_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='final_commit_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='initial_extract_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='llm_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='ml_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='predicted_item_type',
            field=models.CharField(choices=[('event', 'Event'), ('task', 'Task'), ('ignore', 'Ignore'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='rule_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.CreateModel(
            name='CalendarTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('has_time', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=10)),
                ('integration_source', models.CharField(blank=True, default='', max_length=40)),
                ('integration_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tasks', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_tasks', to='happy_seed.hsclassroom')),
            ],
            options={
                'ordering': ['due_at', 'created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='committed_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_captures', to='classcalendar.calendartask'),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapture',
            index=models.Index(fields=['author', 'predicted_item_type', 'created_at'], name='classcalend_author__d1e652_idx'),
        ),
        migrations.AddIndex(
            model_name='calendartask',
            index=models.Index(fields=['author', 'due_at'], name='classcalend_author__0cce35_idx'),
        ),
        migrations.AddIndex(
            model_name='calendartask',
            index=models.Index(fields=['author', 'status', 'due_at'], name='classcalend_author__c33a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendartask',
            index=models.Index(fields=['classroom', 'due_at'], name='classcalend_classro_0b5d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendartask',
            index=models.Index(fields=['author', 'integration_source'], name='classcalend_author__dcfbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='calendartask',
            index=models.Index(fields=['author', 'integration_source', 'integration_key'], name='classcalend_author__4e02d4_idx'),
        ),
    ]
