# Generated by Django 6.0.1 on 2026-03-10 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0012_calendarmessagecapture_confirmed_item_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMessageCaptureCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('candidate_kind', models.CharField(choices=[('event', 'Event'), ('deadline', 'Deadline'), ('prep', 'Prep')], default='event', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_recommended', models.BooleanField(default=True)),
                ('needs_check', models.BooleanField(default=False)),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('evidence_payload', models.JSONField(blank=True, default=dict)),
                ('commit_status', models.CharField(choices=[('pending', 'Pending'), ('saved', 'Saved'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='content_cache_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapture',
            index=models.Index(fields=['author', 'content_cache_key'], name='classcalend_author__1a19df_idx'),
        ),
        migrations.AddField(
            model_name='calendarmessagecapturecandidate',
            name='capture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='classcalendar.calendarmessagecapture'),
        ),
        migrations.AddField(
            model_name='calendarmessagecapturecandidate',
            name='committed_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_capture_candidates', to='classcalendar.calendarevent'),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapturecandidate',
            index=models.Index(fields=['capture', 'sort_order'], name='classcalend_capture_2e5f47_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapturecandidate',
            index=models.Index(fields=['capture', 'commit_status'], name='classcalend_capture_621970_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarmessagecapturecandidate',
            constraint=models.UniqueConstraint(fields=('capture', 'sort_order'), name='calendar_message_capture_candidate_unique_sort_order'),
        ),
    ]
