# Generated by Django 6.0.1 on 2026-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcalendar", "0013_calendarmessagecapturecandidate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarmessagecapture",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
