# Generated by Django 6.0.1 on 2026-03-14 01:13

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from datetime import datetime


def _parse_linked_for_at(raw_value):
    value = raw_value
    if not value:
        return None
    if isinstance(value, datetime):
        parsed = value
    else:
        text = str(value).strip()
        if not text:
            return None
        try:
            parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
        except ValueError:
            try:
                parsed = datetime.strptime(text, "%Y-%m-%d")
            except ValueError:
                return None
    if timezone.is_naive(parsed):
        parsed = timezone.make_aware(parsed, timezone.get_current_timezone())
    return timezone.localtime(parsed)


def backfill_message_capture_follow_up_state(apps, schema_editor):
    CalendarMessageCapture = apps.get_model("classcalendar", "CalendarMessageCapture")

    for capture in CalendarMessageCapture.objects.all().iterator():
        parse_payload = capture.parse_payload if isinstance(capture.parse_payload, dict) else {}
        linked_for_at = _parse_linked_for_at(parse_payload.get("manual_date"))
        if capture.completed_at:
            follow_up_state = "done"
        elif str(capture.parse_status or "").strip() in {"needs_review", "failed"}:
            follow_up_state = "needs_check"
        else:
            follow_up_state = "pending"

        CalendarMessageCapture.objects.filter(id=capture.id).update(
            linked_for_at=linked_for_at,
            follow_up_state=follow_up_state,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0014_calendarmessagecapture_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='follow_up_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_check', 'Needs Check'), ('done', 'Done')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarmessagecapture',
            name='linked_for_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapture',
            index=models.Index(fields=['author', 'linked_for_at'], name='classcalend_author__608244_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarmessagecapture',
            index=models.Index(fields=['author', 'follow_up_state', 'linked_for_at'], name='classcalend_author__a01e97_idx'),
        ),
        migrations.RunPython(backfill_message_capture_follow_up_state, migrations.RunPython.noop),
    ]
