# Generated by Django 6.0.1 on 2026-01-21 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='주제')),
                ('source_type', models.CharField(choices=[('topic', '주제 입력'), ('file', '파일 업로드')], default='topic', max_length=50)),
                ('content_summary', models.TextField(blank=True, verbose_name='요약 내용')),
                ('full_text', models.TextField(blank=True, verbose_name='전체 텍스트')),
                ('ppt_file', models.FileField(blank=True, null=True, upload_to='autoarticle/ppt/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='autoarticle/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
