# Generated by Django 6.0.1 on 2026-01-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoarticle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='일시'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='행사명'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='참여 학년'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, verbose_name='해시태그'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='이미지 경로 리스트'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='keywords',
            field=models.TextField(blank=True, verbose_name='주요 활동 내용'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='장소'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='school_name',
            field=models.CharField(default='서울디지털초등학교', max_length=100, verbose_name='학교명'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='생성된 제목'),
        ),
        migrations.AddField(
            model_name='generatedarticle',
            name='tone',
            field=models.CharField(blank=True, max_length=100, verbose_name='기사 톤'),
        ),
        migrations.AlterField(
            model_name='generatedarticle',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='주제'),
        ),
    ]
