# Generated by Django 6.0.1 on 2026-02-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autoarticle", "0003_generatedarticle_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedarticle",
            name="school_name",
            field=models.CharField(default="스쿨잇 초등학교", max_length=100, verbose_name="참여 학교명"),
        ),
    ]
