# Generated by Django 6.0.1 on 2026-02-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('notebook_url', models.URLField(verbose_name='NotebookLM 링크')),
                ('is_active', models.BooleanField(default=True, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NotebookLM 항목',
                'verbose_name_plural': 'NotebookLM 항목',
                'ordering': ['-created_at'],
            },
        ),
    ]
