# Generated by Django 6.0.3 on 2026-04-28 11:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BambooConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_consent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BambooStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('anon_handle', models.CharField(max_length=20)),
                ('input_masked', models.TextField()),
                ('fable_output', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('is_hidden_by_report', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BambooReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bamboo_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_reports', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bamboo.bamboostory')),
            ],
        ),
        migrations.CreateModel(
            name='BambooLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_likes', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='bamboo.bamboostory')),
            ],
        ),
        migrations.AddIndex(
            model_name='bamboostory',
            index=models.Index(fields=['-created_at'], name='bamboo_bamb_created_d2a21e_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboostory',
            index=models.Index(fields=['is_public', 'is_hidden_by_report', '-created_at'], name='bamboo_bamb_is_publ_42e52b_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboostory',
            index=models.Index(fields=['author', '-created_at'], name='bamboo_bamb_author__89fe9d_idx'),
        ),
        migrations.AddIndex(
            model_name='bambooreport',
            index=models.Index(fields=['story', '-created_at'], name='bamboo_bamb_story_i_7c3975_idx'),
        ),
        migrations.AddConstraint(
            model_name='bambooreport',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='unique_bamboo_report'),
        ),
        migrations.AddIndex(
            model_name='bamboolike',
            index=models.Index(fields=['story', 'user'], name='bamboo_bamb_story_i_8dd4d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='bamboolike',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='unique_bamboo_like'),
        ),
    ]
