# Generated by Django 6.0.3 on 2026-04-28 12:06

import re
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_story_titles(apps, schema_editor):
    story_model = apps.get_model('bamboo', 'BambooStory')
    title_re = re.compile(r'^\s*##\s*제목\s*:\s*(?P<title>[^\n]+)', re.MULTILINE)
    for story in story_model.objects.all().only('id', 'title', 'fable_output'):
        match = title_re.search(story.fable_output or '')
        if not match:
            continue
        title = re.sub(r'\s+', ' ', match.group('title') or '').strip().strip('〈〉<> ')
        if title:
            story.title = title[:100]
            story.save(update_fields=['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BambooComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_handle', models.CharField(max_length=20)),
                ('body_masked', models.TextField()),
                ('is_hidden_by_report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BambooCommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bamboostory',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bamboostory',
            name='title',
            field=models.CharField(default='이름 없는 숲의 우화', max_length=100),
        ),
        migrations.AddField(
            model_name='bamboostory',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_story_titles, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='bamboostory',
            index=models.Index(fields=['-like_count', '-created_at'], name='bamboo_bamb_like_co_d3ab64_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboostory',
            index=models.Index(fields=['-comment_count', '-created_at'], name='bamboo_bamb_comment_958ad1_idx'),
        ),
        migrations.AddField(
            model_name='bamboocomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bamboocomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bamboo.bamboostory'),
        ),
        migrations.AddField(
            model_name='bamboocommentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bamboo.bamboocomment'),
        ),
        migrations.AddField(
            model_name='bamboocommentreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bamboo_comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bamboocommentreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bamboocomment',
            index=models.Index(fields=['story', 'is_hidden_by_report', 'created_at'], name='bamboo_bamb_story_i_420585_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboocomment',
            index=models.Index(fields=['author', '-created_at'], name='bamboo_bamb_author__e1fefa_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboocommentreport',
            index=models.Index(fields=['comment', '-created_at'], name='bamboo_bamb_comment_c11674_idx'),
        ),
        migrations.AddConstraint(
            model_name='bamboocommentreport',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_bamboo_comment_report'),
        ),
    ]
