# Generated by Django 6.0.3 on 2026-04-28 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0002_board_v1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bamboocommentreport',
            name='unique_bamboo_comment_report',
        ),
        migrations.RemoveConstraint(
            model_name='bamboolike',
            name='unique_bamboo_like',
        ),
        migrations.RemoveConstraint(
            model_name='bambooreport',
            name='unique_bamboo_report',
        ),
        migrations.AddField(
            model_name='bamboocomment',
            name='author_guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bamboocommentreport',
            name='guest_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bamboolike',
            name='guest_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bambooreport',
            name='guest_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='bamboostory',
            name='author_guest_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='bamboocomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bamboocommentreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bamboolike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bambooreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bamboo_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bamboostory',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bamboo_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bamboocomment',
            index=models.Index(fields=['author_guest_key', '-created_at'], name='bamboo_bamb_author__0ee850_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboolike',
            index=models.Index(fields=['story', 'guest_key'], name='bamboo_bamb_story_i_2eeacd_idx'),
        ),
        migrations.AddIndex(
            model_name='bamboostory',
            index=models.Index(fields=['author_guest_key', '-created_at'], name='bamboo_bamb_author__3a3ddc_idx'),
        ),
        migrations.AddConstraint(
            model_name='bamboocommentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'comment'), name='unique_bamboo_comment_report_user'),
        ),
        migrations.AddConstraint(
            model_name='bamboocommentreport',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_key', ''), _negated=True), fields=('guest_key', 'comment'), name='unique_bamboo_comment_report_guest'),
        ),
        migrations.AddConstraint(
            model_name='bamboolike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'story'), name='unique_bamboo_like_user'),
        ),
        migrations.AddConstraint(
            model_name='bamboolike',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_key', ''), _negated=True), fields=('guest_key', 'story'), name='unique_bamboo_like_guest'),
        ),
        migrations.AddConstraint(
            model_name='bambooreport',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'story'), name='unique_bamboo_report_user'),
        ),
        migrations.AddConstraint(
            model_name='bambooreport',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_key', ''), _negated=True), fields=('guest_key', 'story'), name='unique_bamboo_report_guest'),
        ),
    ]
