# Generated by Django 6.0.3 on 2026-04-28 13:57

from django.db import migrations, models


def clear_story_input_masked(apps, schema_editor):
    BambooStory = apps.get_model("bamboo", "BambooStory")
    BambooStory.objects.exclude(input_masked="").update(input_masked="")


class Migration(migrations.Migration):

    dependencies = [
        ('bamboo', '0003_guest_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bamboostory',
            name='input_masked',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(clear_story_input_masked, migrations.RunPython.noop),
    ]
