# Generated by Django 6.0.3 on 2026-04-24 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathGameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('game_type', models.CharField(choices=[('nim', '님'), ('24', '24 게임')], max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('random', '랜덤'), ('mcts', 'MCTS'), ('minimax', 'Minimax')], max_length=20)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('active', '진행 중'), ('win', '승리'), ('lose', '패배'), ('solved', '해결'), ('give_up', '포기')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='math_game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MathGameMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(choices=[('student', '학생'), ('ai', 'AI'), ('system', '시스템')], max_length=20)),
                ('move_json', models.JSONField(blank=True, default=dict)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='math_games.mathgamesession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mathgamesession',
            index=models.Index(fields=['game_type', 'result'], name='math_games__game_ty_a7a3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='mathgamesession',
            index=models.Index(fields=['session_key', 'game_type'], name='math_games__session_4eec23_idx'),
        ),
        migrations.AddIndex(
            model_name='mathgamemove',
            index=models.Index(fields=['session', 'actor'], name='math_games__session_0d2cd0_idx'),
        ),
    ]
