# Generated by Django 6.0.3 on 2026-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathgamesession',
            name='game_type',
            field=models.CharField(choices=[('nim', '님'), ('24', '24 게임'), ('2048', '2048')], max_length=20),
        ),
    ]
