# Generated by Django 6.0.1 on 2026-03-28 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NextEduMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='자료 제목')),
                ('html_content', models.TextField(verbose_name='HTML 코드')),
                ('access_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='학생 공유 여부')),
                ('subject', models.CharField(blank=True, choices=[('KOREAN', '국어'), ('MATH', '수학'), ('SOCIAL', '사회'), ('SCIENCE', '과학'), ('OTHER', '기타')], default='OTHER', max_length=20)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('unit_title', models.CharField(blank=True, default='', max_length=200)),
                ('material_type', models.CharField(choices=[('intro', '도입'), ('exploration', '탐구'), ('practice', '연습'), ('quiz', '퀴즈'), ('game', '게임'), ('reference', '참고자료'), ('presentation', '발표'), ('tool', '도구'), ('other', '기타')], default='other', max_length=20)),
                ('summary', models.CharField(blank=True, default='', max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True, default='')),
                ('entry_mode', models.CharField(choices=[('learn', '처음 배우기'), ('starter', '예시로 시작'), ('import', '기존 버전에서 가져오기'), ('paste', 'HTML 붙여넣기'), ('file', 'HTML 파일 올리기')], default='learn', max_length=20)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('teacher_guide', models.TextField(blank=True, default='')),
                ('student_questions', models.JSONField(blank=True, default=list)),
                ('remix_tips', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('difficulty_level', models.CharField(choices=[('beginner', '입문'), ('intermediate', '확장'), ('advanced', '응용')], default='beginner', max_length=20)),
                ('reflection_note', models.TextField(blank=True, default='')),
                ('legacy_source_material_id', models.UUIDField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_materials_next', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_source_material_id__isnull', False)), fields=('teacher', 'legacy_source_material_id'), name='edu_materials_next_unique_import_per_teacher_legacy')],
            },
        ),
    ]
