# Generated by Django 6.0.1 on 2026-02-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_schoolconfig_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='period_labels',
            field=models.TextField(default='1교시,2교시,3교시,4교시,5교시,6교시'),
        ),
    ]
