# Generated by Django 6.0.1 on 2026-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_schoolconfig_period_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfig',
            name='weekly_opening_hour',
            field=models.IntegerField(default=9, help_text='0-23시'),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='weekly_opening_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolconfig',
            name='weekly_opening_weekday',
            field=models.IntegerField(default=4, help_text='0=월, 1=화, ... 4=금, 6=일'),
        ),
    ]
