# Generated by Django 6.0.1 on 2026-03-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_graderecurringlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='target_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
