# Generated by Django 6.0.1 on 2026-04-10 00:00

import re
import unicodedata
from django.db import migrations, models


OWNER_TEXT_WHITESPACE_RE = re.compile(r"\s+")


def normalize_reservation_owner_text(value):
    normalized = unicodedata.normalize("NFKC", str(value or ""))
    normalized = OWNER_TEXT_WHITESPACE_RE.sub("", normalized).strip().lower()
    return normalized[:80]


def build_reservation_owner_key(*, grade=0, class_no=0, target_label="", name=""):
    normalized_name = normalize_reservation_owner_text(name)
    normalized_target_label = normalize_reservation_owner_text(target_label)

    try:
        grade_value = int(grade or 0)
    except (TypeError, ValueError):
        grade_value = 0

    try:
        class_value = int(class_no or 0)
    except (TypeError, ValueError):
        class_value = 0

    if normalized_target_label:
        return f"target|{normalized_target_label}|{normalized_name}"[:160]
    if grade_value > 0 and class_value > 0:
        return f"class|{grade_value}|{class_value}|{normalized_name}"[:160]
    if grade_value > 0:
        return f"grade|{grade_value}|{normalized_name}"[:160]
    if normalized_name:
        return f"name|{normalized_name}"[:160]
    return ""


def populate_owner_keys(apps, schema_editor):
    Reservation = apps.get_model("reservations", "Reservation")
    for reservation in Reservation.objects.all().iterator():
        owner_key = build_reservation_owner_key(
            grade=reservation.grade,
            class_no=reservation.class_no,
            target_label=reservation.target_label,
            name=reservation.name,
        )
        if reservation.owner_key != owner_key:
            reservation.owner_key = owner_key
            reservation.save(update_fields=["owner_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0009_reservationcollaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="owner_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=160),
        ),
        migrations.RunPython(populate_owner_keys, migrations.RunPython.noop),
    ]
