# Generated by Django 6.0.1 on 2026-04-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_reservation_owner_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="edit_code_hash",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
