# Generated by Django 6.0.1 on 2026-03-08 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('KOREAN', '국어'), ('MATH', '수학'), ('SOCIAL', '사회'), ('SCIENCE', '과학'), ('OTHER', '기타')], max_length=20, verbose_name='과목')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='학년/학기')),
                ('unit_title', models.CharField(max_length=200, verbose_name='단원명')),
                ('title', models.CharField(max_length=200, verbose_name='자료 제목')),
                ('source_type', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('pdf', 'PDF')], default='markdown', max_length=20, verbose_name='자료 형식')),
                ('content', models.TextField(blank=True, verbose_name='자료 내용/메모')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='textbooks/pdf/%Y/%m/')),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextbookLiveSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', '준비 중'), ('live', '진행 중'), ('ended', '종료')], default='draft', max_length=20)),
                ('join_code', models.CharField(db_index=True, max_length=6)),
                ('allow_student_annotation', models.BooleanField(default=False)),
                ('follow_mode', models.BooleanField(default=True)),
                ('current_page', models.PositiveIntegerField(default=1)),
                ('zoom_scale', models.FloatField(default=1.0)),
                ('viewport_json', models.JSONField(blank=True, default=dict)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbook_live_sessions', to='happy_seed.hsclassroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_live_sessions', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='textbooks.textbookmaterial')),
            ],
            options={
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextbookLiveParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', '교사'), ('student', '학생'), ('display', 'TV 화면')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('device_id', models.CharField(max_length=64)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbook_live_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='textbooks.textbooklivesession')),
            ],
            options={
                'ordering': ['role', 'display_name', 'joined_at'],
                'unique_together': {('session', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='TextbookLivePageState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveIntegerField()),
                ('fabric_json', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_states', to='textbooks.textbooklivesession')),
            ],
            options={
                'ordering': ['page_index'],
                'unique_together': {('session', 'page_index')},
            },
        ),
        migrations.CreateModel(
            name='TextbookLiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=50)),
                ('page_index', models.PositiveIntegerField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('actor_role', models.CharField(choices=[('teacher', '교사'), ('student', '학생'), ('display', '전광판'), ('system', '시스템')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='textbooks.textbooklivesession')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('session', 'seq')},
            },
        ),
    ]
