# Generated by Django 6.0.1 on 2026-03-07 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('KOREAN', '국어'), ('MATH', '수학'), ('SOCIAL', '사회'), ('SCIENCE', '과학')], max_length=20, verbose_name='과목')),
                ('grade', models.CharField(blank=True, max_length=50, null=True, verbose_name='학년/학기')),
                ('unit_title', models.CharField(max_length=200, verbose_name='단원명')),
                ('title', models.CharField(default='수업 자료', max_length=200, verbose_name='자료 제목')),
                ('content', models.TextField(blank=True, help_text='Markdown 형식의 본문', verbose_name='자료 내용')),
                ('is_published', models.BooleanField(default=False, verbose_name='학생 배포 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '교과서 자료',
                'verbose_name_plural': '교과서 자료들',
                'ordering': ['-created_at'],
            },
        ),
    ]
