# Generated by Django 6.0.1 on 2026-03-07 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='textbookmaterial',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='다른 교사와 공유 여부'),
        ),
        migrations.AddField(
            model_name='textbookmaterial',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_textbook_materials', to=settings.AUTH_USER_MODEL, verbose_name='추천한 사용자'),
        ),
        migrations.AddField(
            model_name='textbookmaterial',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
