# Generated by Django 6.0.1 on 2026-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_textbookmaterial_is_shared_textbookmaterial_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbookmaterial',
            name='is_shared',
            field=models.BooleanField(default=True, verbose_name='다른 교사와 공유 여부'),
        ),
    ]
