# Generated by Django 6.0.1 on 2026-03-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0003_alter_textbookmaterial_is_shared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='기준일')),
                ('categorize_count', models.IntegerField(default=0, verbose_name='자동 분류 사용 횟수')),
                ('prompt_count', models.IntegerField(default=0, verbose_name='프롬프트 도우미 사용 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks_ai_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 사용 기록',
                'verbose_name_plural': 'AI 사용 기록들',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
