# Generated by Django 6.0.1 on 2026-02-10 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_code', models.CharField(blank=True, help_text='6자리 입장코드', max_length=6, null=True, unique=True)),
                ('title', models.CharField(help_text='수합 제목', max_length=200)),
                ('description', models.TextField(blank=True, help_text='안내사항')),
                ('allow_file', models.BooleanField(default=True, help_text='파일 업로드 허용')),
                ('allow_link', models.BooleanField(default=True, help_text='링크 제출 허용')),
                ('allow_text', models.BooleanField(default=True, help_text='텍스트 제출 허용')),
                ('deadline', models.DateTimeField(blank=True, help_text='마감일시', null=True)),
                ('status', models.CharField(choices=[('active', '진행중'), ('closed', '마감'), ('archived', '보관')], default='active', max_length=10)),
                ('max_file_size_mb', models.IntegerField(default=10, help_text='파일당 최대 크기(MB)')),
                ('max_submissions', models.IntegerField(default=50, help_text='최대 제출 건수')),
                ('template_file', models.FileField(blank=True, help_text='양식 파일 (hwp, xlsx 등)', null=True, upload_to='collect/templates/')),
                ('template_file_name', models.CharField(blank=True, help_text='양식 파일 원본 이름', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '수합 요청',
                'verbose_name_plural': '수합 요청 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributor_name', models.CharField(help_text='제출자 이름', max_length=100)),
                ('contributor_affiliation', models.CharField(blank=True, help_text='소속', max_length=100)),
                ('submission_type', models.CharField(choices=[('file', '파일'), ('link', '링크'), ('text', '텍스트')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='collect/submissions/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='파일 크기(bytes)')),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('link_description', models.CharField(blank=True, max_length=200)),
                ('text_content', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_downloaded', models.BooleanField(default=False, help_text='다운로드 여부')),
                ('collection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='collect.collectionrequest')),
            ],
            options={
                'verbose_name': '제출물',
                'verbose_name_plural': '제출물 목록',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
