# Generated by Django 6.0.1 on 2026-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='max_file_size_mb',
            field=models.IntegerField(default=30, help_text='파일당 최대 크기(MB)'),
        ),
    ]
