# Generated by Django 6.0.1 on 2026-02-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_alter_collectionrequest_max_file_size_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='expected_submitters',
            field=models.TextField(blank=True, help_text='예상 제출자 목록 (줄바꿈 구분)'),
        ),
    ]
