# Generated by Django 6.0.1 on 2026-02-12 00:32

import collect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_collectionrequest_expected_submitters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrequest',
            name='template_file',
            field=models.FileField(blank=True, help_text='양식 파일 (hwp, xlsx 등)', null=True, storage=collect.models.get_raw_storage, upload_to='collect/templates/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, storage=collect.models.get_raw_storage, upload_to='collect/submissions/'),
        ),
    ]
