# Generated by Django 6.0.1 on 2026-02-12 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_alter_collectionrequest_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='management_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
