# Generated by Django 6.0.1 on 2026-02-12 01:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_submission_management_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='management_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
