# Generated by Django 6.0.1 on 2026-02-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_alter_submission_management_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='마감 처리 시각', null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='retention_until',
            field=models.DateTimeField(blank=True, help_text='자동 정리 유예 시각', null=True),
        ),
    ]
