# Generated by Django 6.0.1 on 2026-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0007_collectionrequest_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='allow_choice',
            field=models.BooleanField(default=False, help_text='선택형 제출 허용'),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='choice_allow_other',
            field=models.BooleanField(default=False, help_text='기타 직접 입력 허용'),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='choice_max_selections',
            field=models.PositiveIntegerField(blank=True, help_text='복수 선택 최대 개수 (비우면 제한 없음)', null=True),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='choice_min_selections',
            field=models.PositiveIntegerField(default=1, help_text='복수 선택 최소 개수'),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='choice_mode',
            field=models.CharField(choices=[('single', '단일 선택'), ('multi', '복수 선택')], default='single', help_text='선택형 제출 모드', max_length=10),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='choice_options',
            field=models.JSONField(blank=True, default=list, help_text='선택형 보기 목록'),
        ),
        migrations.AddField(
            model_name='submission',
            name='choice_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='choice_other_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('file', '파일'), ('link', '링크'), ('text', '텍스트'), ('choice', '선택형')], max_length=10),
        ),
    ]
