# Generated by Django 6.0.1 on 2026-02-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_collectionrequest_allow_choice_and_more'),
        ('handoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='shared_roster_group',
            field=models.ForeignKey(blank=True, help_text='배부 체크 명단과 연동할 대상 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collect_requests', to='handoff.handoffrostergroup'),
        ),
    ]
