# Generated by Django 6.0.1 on 2026-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_collectionrequest_shared_roster_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='bti_integration_source',
            field=models.CharField(choices=[('none', '사용 안 함'), ('ssambti', '쌤BTI'), ('studentmbti', '우리반BTI'), ('both', '쌤BTI + 우리반BTI')], default='none', help_text='BTI 결과 연동 대상', max_length=20),
        ),
    ]
