# Generated by Django 6.0.1 on 2026-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0010_collectionrequest_bti_integration_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='integration_ref',
            field=models.CharField(blank=True, default='', help_text='연동 중복 방지를 위한 외부 참조 키', max_length=120),
        ),
        migrations.AddField(
            model_name='submission',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('', '직접 제출'), ('ssambti', '쌤BTI'), ('studentmbti', '우리반BTI')], default='', help_text='외부/연동 경로 식별자', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('integration_source', ''), _negated=True), models.Q(('integration_ref', ''), _negated=True)), fields=('collection_request', 'integration_source', 'integration_ref'), name='collect_submission_unique_integration_ref'),
        ),
    ]
