# Generated by Django 6.0.3 on 2026-04-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0011_submission_integration_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrequest',
            name='collection_mode',
            field=models.CharField(choices=[('legacy', '기존 방식'), ('fields', '항목식')], default='legacy', help_text='수합 입력 방식', max_length=12),
        ),
        migrations.AddField(
            model_name='collectionrequest',
            name='field_schema',
            field=models.JSONField(blank=True, default=list, help_text='항목식 수합 입력 항목'),
        ),
        migrations.AddField(
            model_name='submission',
            name='field_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('file', '파일'), ('link', '링크'), ('text', '텍스트'), ('choice', '선택형'), ('fields', '항목식')], max_length=10),
        ),
    ]
