# Generated by Django 6.0.1 on 2026-01-23 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_key', models.CharField(choices=[('homeroom', '담임교사 모드'), ('officer', '학폭책임교사 모드'), ('admin', '교육청/행정 모드')], max_length=20, unique=True, verbose_name='모드 키')),
                ('display_name', models.CharField(max_length=50, verbose_name='표시 이름')),
                ('description', models.TextField(verbose_name='모드 설명')),
                ('system_prompt', models.TextField(verbose_name='시스템 프롬프트')),
                ('icon', models.CharField(default='fa-solid fa-user', max_length=50, verbose_name='아이콘 클래스')),
                ('color', models.CharField(default='purple', max_length=50, verbose_name='색상 클래스')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '상담 모드',
                'verbose_name_plural': '상담 모드 목록',
            },
        ),
        migrations.CreateModel(
            name='GuidelineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문서 제목')),
                ('category', models.CharField(choices=[('guidebook', '사안처리 가이드북'), ('manual', '업무 매뉴얼'), ('law', '법령/지침'), ('case', '사례집'), ('other', '기타')], default='guidebook', max_length=20, verbose_name='분류')),
                ('file', models.FileField(upload_to='school_violence/docs/', verbose_name='파일')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_processed', models.BooleanField(default=False, verbose_name='벡터DB 처리 완료')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='청크 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_guidelines', to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
            ],
            options={
                'verbose_name': '가이드라인 문서',
                'verbose_name_plural': '가이드라인 문서 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
