# Generated by Django 6.0.1 on 2026-01-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(help_text='YouTube video URL')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Auto-generated or custom thumbnail URL')),
                ('content', models.TextField(help_text='Main insight or quote')),
                ('kakio_note', models.TextField(blank=True, help_text="Teacher's special note")),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags e.g. #Leadership', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
