# Generated by Django 6.0.1 on 2026-01-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='category',
            field=models.CharField(choices=[('youtube', 'YouTube Scrap'), ('devlog', 'DevLog (Development Log)'), ('column', 'Column/Essay')], default='youtube', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
