# Generated by Django 6.0.1 on 2026-01-25 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_insight_category_alter_insight_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_insights', to=settings.AUTH_USER_MODEL),
        ),
    ]
