# Generated by Django 6.0.3 on 2026-04-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_insight_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='deck',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='짧은 소개'),
        ),
        migrations.AddField(
            model_name='insight',
            name='series_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='시리즈'),
        ),
        migrations.AddField(
            model_name='insight',
            name='track',
            field=models.CharField(choices=[('practical', '바로 쓰는 AI'), ('classroom', '수업 사례'), ('editorial', '운영 노트')], default='practical', max_length=20, verbose_name='트랙'),
        ),
    ]
