from django.urls import path

from .openclo_login import OPENCLO_LOGIN_PATH, openclo_login_view
from . import views

urlpatterns = [
    path(OPENCLO_LOGIN_PATH, openclo_login_view, name='openclo_hidden_login'),
    path('', views.home, name='home'),
    path('community/', views.community_feed, name='community_feed'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('post/create/', views.post_create, name='post_create'),
    path('notice/pinned-notice-expanded/', views.toggle_pinned_notice_expanded, name='toggle_pinned_notice_expanded'),
    path('post/<int:pk>/like/', views.post_like, name='post_like'),
    path('post/<int:pk>/comment/', views.comment_create, name='comment_create'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/detail/', views.post_detail_partial, name='post_detail_partial'),
    path('comment/<int:pk>/delete/', views.comment_delete, name='comment_delete'),
    path('comment/<int:pk>/edit/', views.comment_edit, name='comment_edit'),
    path('comment/<int:pk>/item/', views.comment_item_partial, name='comment_item'),
    path('comment/<int:pk>/report/', views.comment_report, name='comment_report'),
    path('news/review/', views.news_review_queue, name='news_review_queue'),
    path('news/review/<int:pk>/action/', views.news_review_action, name='news_review_action'),
    path('insights/review/', views.insight_sns_queue, name='insight_sns_queue'),
    path('insights/review/<int:pk>/action/', views.insight_sns_action, name='insight_sns_action'),
    path('prompts/', views.prompt_lab, name='prompt_lab'),
    path('tools/', views.tool_guide, name='tool_guide'),
    path('manuals/', views.service_guide_list, name='service_guide_list'),
    path('manuals/<int:pk>/', views.service_guide_detail, name='service_guide_detail'),
    path('about/', views.about, name='about'),
    path('settings/', views.settings_view, name='settings'),
    path('select-role/', views.select_role, name='select_role'),
    path('sso/schoolit/', views.sso_to_schoolit, name='sso_schoolit'),
    path('policy/', views.policy_view, name='policy'),
    path('policy/consent/', views.policy_consent_view, name='policy_consent'),
    path('accounts/social/consent/', views.social_signup_consent_view, name='social_signup_consent'),
    path('update-email/', views.update_email, name='update_email'),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('feedback/', views.feedback_view, name='feedback'),
    path('admin-dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('api/track-usage/', views.track_product_usage, name='track_product_usage'),
    path('api/home-agent/preview/', views.home_agent_preview, name='home_agent_preview'),
    path('api/home-agent/conversations/', views.home_agent_conversations, name='home_agent_conversations'),
    path('api/home-agent/execute/', views.home_agent_execute, name='home_agent_execute'),
    path('api/home-agent/quota/dismiss/', views.home_agent_quota_dismiss, name='home_agent_quota_dismiss'),
    path('api/buddy/draw/', views.teacher_buddy_draw, name='teacher_buddy_draw'),
    path('api/buddy/coupon/redeem/', views.teacher_buddy_redeem_coupon_view, name='teacher_buddy_redeem_coupon'),
    path('api/buddy/select/', views.teacher_buddy_select_view, name='teacher_buddy_select'),
    path('api/buddy/select/profile/', views.teacher_buddy_select_profile_view, name='teacher_buddy_select_profile'),
    path('api/buddy/skin/unlock/', views.teacher_buddy_unlock_skin_view, name='teacher_buddy_unlock_skin'),
    path('buddy/share/<uuid:public_share_token>/sheet/', views.teacher_buddy_profile_sheet, name='teacher_buddy_profile_sheet'),
    path('buddy/share/<uuid:public_share_token>/', views.teacher_buddy_share_page, name='teacher_buddy_share_page'),
    path('buddy/share/<uuid:public_share_token>/image.svg', views.teacher_buddy_share_image, name='teacher_buddy_share_image'),
    path('api/favorites/toggle/', views.toggle_product_favorite, name='toggle_product_favorite'),
    path('api/favorites/', views.list_product_favorites, name='list_product_favorites'),
    path('api/favorites/reorder/', views.reorder_product_favorites, name='reorder_product_favorites'),
    path('api/workbench-bundles/', views.list_workbench_bundles, name='list_workbench_bundles'),
    path('api/workbench-bundles/save/', views.save_workbench_bundle, name='save_workbench_bundle'),
    path('api/workbench-bundles/<int:bundle_id>/apply/', views.apply_workbench_bundle, name='apply_workbench_bundle'),
    path('api/workbench-bundles/<int:bundle_id>/delete/', views.delete_workbench_bundle, name='delete_workbench_bundle'),
    path('api/set-classroom/', views.set_active_classroom, name='set_active_classroom'),
]
