# Generated by Django 6.0.1 on 2026-03-09 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EduMaterial",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("subject", models.CharField(choices=[("KOREAN", "국어"), ("MATH", "수학"), ("SOCIAL", "사회"), ("SCIENCE", "과학"), ("OTHER", "기타")], max_length=20, verbose_name="과목")),
                ("grade", models.CharField(blank=True, max_length=50, verbose_name="학년/학기")),
                ("unit_title", models.CharField(max_length=200, verbose_name="단원명")),
                ("title", models.CharField(max_length=200, verbose_name="자료 제목")),
                ("html_content", models.TextField(verbose_name="HTML 코드")),
                ("input_mode", models.CharField(choices=[("paste", "코드 붙여넣기"), ("file", "HTML 파일 업로드")], default="paste", max_length=10, verbose_name="입력 방식")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("is_published", models.BooleanField(default=False, verbose_name="공개 여부")),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="edu_materials", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
    ]
