# Generated by Django 6.0.1 on 2026-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_materials', '0002_import_from_textbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edumaterial',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='학년/학기'),
        ),
        migrations.AlterField(
            model_name='edumaterial',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='공개 여부'),
        ),
        migrations.AlterField(
            model_name='edumaterial',
            name='subject',
            field=models.CharField(blank=True, choices=[('KOREAN', '국어'), ('MATH', '수학'), ('SOCIAL', '사회'), ('SCIENCE', '과학'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='edumaterial',
            name='unit_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='단원명'),
        ),
    ]
