# Generated by Codex on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edu_materials", "0003_alter_edumaterial_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edumaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("intro", "도입"),
                    ("exploration", "탐구"),
                    ("practice", "연습"),
                    ("quiz", "퀴즈"),
                    ("game", "게임"),
                    ("reference", "참고자료"),
                    ("presentation", "발표"),
                    ("tool", "도구"),
                    ("other", "기타"),
                ],
                default="other",
                max_length=20,
                verbose_name="자료 유형",
            ),
        ),
        migrations.AddField(
            model_name="edumaterial",
            name="metadata_confidence",
            field=models.FloatField(default=0.0, verbose_name="자동 분류 신뢰도"),
        ),
        migrations.AddField(
            model_name="edumaterial",
            name="metadata_source",
            field=models.CharField(
                choices=[("auto", "자동 분류"), ("manual", "직접 수정")],
                default="auto",
                max_length=20,
                verbose_name="분류 출처",
            ),
        ),
        migrations.AddField(
            model_name="edumaterial",
            name="metadata_status",
            field=models.CharField(
                choices=[("pending", "분류 대기"), ("done", "분류 완료"), ("failed", "분류 실패")],
                default="pending",
                max_length=20,
                verbose_name="분류 상태",
            ),
        ),
        migrations.AddField(
            model_name="edumaterial",
            name="search_text",
            field=models.TextField(blank=True, default="", verbose_name="검색 텍스트"),
        ),
        migrations.AddField(
            model_name="edumaterial",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="한줄 요약"),
        ),
        migrations.AddField(
            model_name="edumaterial",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="태그"),
        ),
    ]
