# Generated by Django 6.0.1 on 2026-03-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_materials', '0007_publish_all_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edumaterial',
            name='input_mode',
            field=models.CharField(choices=[('paste', '자료 붙여넣기'), ('file', '파일 올리기')], default='paste', max_length=10, verbose_name='입력 방식'),
        ),
    ]
