# Generated by Django 6.0.1 on 2026-03-24 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_materials', '0008_alter_input_mode_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='edumaterial',
            name='source_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_materials', to='edu_materials.edumaterial'),
        ),
        migrations.AddConstraint(
            model_name='edumaterial',
            constraint=models.UniqueConstraint(condition=models.Q(('source_material__isnull', False)), fields=('teacher', 'source_material'), name='edu_materials_unique_clone_per_teacher_source'),
        ),
    ]
