# Generated by Django 6.0.1 on 2026-02-21 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQQuizSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField(verbose_name='대상 날짜')),
                ('preset_type', models.CharField(choices=[('general', '상식'), ('math', '수학'), ('korean', '국어'), ('science', '과학'), ('social', '사회'), ('english', '영어')], default='general', max_length=20, verbose_name='과목 프리셋')),
                ('grade', models.IntegerField(default=3, verbose_name='학년')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('status', models.CharField(choices=[('draft', '초안'), ('published', '배포중'), ('closed', '종료'), ('failed', '생성실패')], default='draft', max_length=10, verbose_name='상태')),
                ('source', models.CharField(choices=[('ai', 'AI'), ('fallback', '기본문제')], default='ai', max_length=10, verbose_name='출처')),
                ('time_limit_seconds', models.IntegerField(default=600, verbose_name='제한시간(초)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='배포 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sq_quiz_sets', to='happy_seed.hsclassroom', verbose_name='교실')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sq_quiz_sets_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sq_quiz_sets_published', to=settings.AUTH_USER_MODEL, verbose_name='배포자')),
            ],
            options={
                'verbose_name': '퀴즈 세트',
                'verbose_name_plural': '퀴즈 세트',
            },
        ),
        migrations.CreateModel(
            name='SQQuizItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(verbose_name='순서')),
                ('question_text', models.TextField(verbose_name='문제')),
                ('choices', models.JSONField(verbose_name='선택지')),
                ('correct_index', models.IntegerField(verbose_name='정답 인덱스')),
                ('explanation', models.TextField(blank=True, verbose_name='해설')),
                ('difficulty', models.CharField(default='medium', max_length=10, verbose_name='난이도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seed_quiz.sqquizset', verbose_name='퀴즈 세트')),
            ],
            options={
                'verbose_name': '퀴즈 문항',
                'verbose_name_plural': '퀴즈 문항',
            },
        ),
        migrations.CreateModel(
            name='SQGenerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', '정보'), ('warn', '경고'), ('error', '오류')], default='info', max_length=5, verbose_name='레벨')),
                ('code', models.CharField(max_length=50, verbose_name='코드')),
                ('message', models.TextField(verbose_name='메시지')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='페이로드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='seed_quiz.sqquizset', verbose_name='퀴즈 세트')),
            ],
            options={
                'verbose_name': '생성 로그',
                'verbose_name_plural': '생성 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SQAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', '진행중'), ('submitted', '제출완료'), ('rewarded', '보상완료')], default='in_progress', max_length=15, verbose_name='상태')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='요청 ID')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('max_score', models.IntegerField(default=3, verbose_name='만점')),
                ('reward_seed_amount', models.IntegerField(default=0, verbose_name='보상 씨앗 수')),
                ('consent_snapshot', models.CharField(blank=True, max_length=15, verbose_name='동의 상태 스냅샷')),
                ('reward_applied_at', models.DateTimeField(blank=True, null=True, verbose_name='보상 지급 시각')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시각')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sq_attempts', to='happy_seed.hsstudent', verbose_name='학생')),
                ('quiz_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='seed_quiz.sqquizset', verbose_name='퀴즈 세트')),
            ],
            options={
                'verbose_name': '시도',
                'verbose_name_plural': '시도',
            },
        ),
        migrations.CreateModel(
            name='SQAttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_index', models.IntegerField(verbose_name='선택한 답')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='답변 시각')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='seed_quiz.sqattempt', verbose_name='시도')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed_quiz.sqquizitem', verbose_name='문항')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변',
                'constraints': [models.CheckConstraint(condition=models.Q(('selected_index__gte', 0), ('selected_index__lte', 3)), name='sq_answer_selected_index_range')],
                'unique_together': {('attempt', 'item')},
            },
        ),
        migrations.AddIndex(
            model_name='sqquizset',
            index=models.Index(fields=['classroom', 'target_date', 'status'], name='seed_quiz_s_classro_8e2923_idx'),
        ),
        migrations.AddIndex(
            model_name='sqquizset',
            index=models.Index(fields=['status', 'published_at'], name='seed_quiz_s_status_daa0b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='sqquizset',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('classroom', 'target_date', 'preset_type'), name='unique_published_quiz_per_class_date_preset'),
        ),
        migrations.AddConstraint(
            model_name='sqquizitem',
            constraint=models.CheckConstraint(condition=models.Q(('correct_index__gte', 0), ('correct_index__lte', 3)), name='sq_item_correct_index_range'),
        ),
        migrations.AlterUniqueTogether(
            name='sqquizitem',
            unique_together={('quiz_set', 'order_no')},
        ),
        migrations.AlterUniqueTogether(
            name='sqattempt',
            unique_together={('student', 'quiz_set')},
        ),
    ]
