# Generated by Django 6.0.1 on 2026-02-21 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqquizset',
            name='source',
            field=models.CharField(choices=[('ai', 'AI'), ('fallback', '기본문제'), ('bank', '은행'), ('csv', 'CSV')], default='ai', max_length=10, verbose_name='출처'),
        ),
        migrations.CreateModel(
            name='SQQuizBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset_type', models.CharField(choices=[('general', '상식'), ('math', '수학'), ('korean', '국어'), ('science', '과학'), ('social', '사회'), ('english', '영어')], default='general', max_length=20, verbose_name='과목 프리셋')),
                ('grade', models.IntegerField(default=3, verbose_name='학년')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('source', models.CharField(choices=[('ai', 'AI생성'), ('csv', 'CSV임포트'), ('manual', '직접입력')], default='manual', max_length=10, verbose_name='출처')),
                ('is_official', models.BooleanField(default=False, verbose_name='공식 세트')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 세트')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('use_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sq_quiz_banks_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '퀴즈 은행 세트',
                'verbose_name_plural': '퀴즈 은행 세트',
                'ordering': ['preset_type', 'grade', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sqquizset',
            name='bank_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_sets', to='seed_quiz.sqquizbank', verbose_name='은행 출처'),
        ),
        migrations.CreateModel(
            name='SQQuizBankItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.IntegerField(verbose_name='순서')),
                ('question_text', models.TextField(verbose_name='문제')),
                ('choices', models.JSONField(verbose_name='선택지')),
                ('correct_index', models.IntegerField(verbose_name='정답 인덱스')),
                ('explanation', models.TextField(blank=True, verbose_name='해설')),
                ('difficulty', models.CharField(default='medium', max_length=10, verbose_name='난이도')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seed_quiz.sqquizbank', verbose_name='은행 세트')),
            ],
            options={
                'verbose_name': '은행 문항',
                'verbose_name_plural': '은행 문항',
            },
        ),
        migrations.AddIndex(
            model_name='sqquizbank',
            index=models.Index(fields=['preset_type', 'grade', 'is_active'], name='seed_quiz_s_preset__e4e20e_idx'),
        ),
        migrations.AddIndex(
            model_name='sqquizbank',
            index=models.Index(fields=['is_official', 'is_active'], name='seed_quiz_s_is_offi_1c213d_idx'),
        ),
        migrations.AddIndex(
            model_name='sqquizbank',
            index=models.Index(fields=['is_public', 'is_active'], name='seed_quiz_s_is_publ_763663_idx'),
        ),
        migrations.AddConstraint(
            model_name='sqquizbankitem',
            constraint=models.CheckConstraint(condition=models.Q(('correct_index__gte', 0), ('correct_index__lte', 3)), name='sq_bank_item_correct_index_range'),
        ),
        migrations.AlterUniqueTogether(
            name='sqquizbankitem',
            unique_together={('bank', 'order_no')},
        ),
    ]
