# Generated by Django 6.0.1 on 2026-02-21 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        ('seed_quiz', '0002_alter_sqquizset_source_sqquizbank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQBatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='openai', max_length=30, verbose_name='제공자')),
                ('target_month', models.DateField(verbose_name='대상 월(1일 기준)')),
                ('batch_id', models.CharField(blank=True, default='', max_length=120, verbose_name='외부 배치 ID')),
                ('status', models.CharField(choices=[('pending', '대기'), ('submitted', '제출됨'), ('validating', '검증중'), ('in_progress', '진행중'), ('finalizing', '마무리중'), ('completed', '완료'), ('failed', '실패'), ('cancelled', '취소')], default='pending', max_length=20, verbose_name='상태')),
                ('input_file_id', models.CharField(blank=True, default='', max_length=120, verbose_name='입력 파일 ID')),
                ('output_file_id', models.CharField(blank=True, default='', max_length=120, verbose_name='출력 파일 ID')),
                ('error_file_id', models.CharField(blank=True, default='', max_length=120, verbose_name='오류 파일 ID')),
                ('requested_count', models.IntegerField(default=0, verbose_name='요청 수')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 수')),
                ('failed_count', models.IntegerField(default=0, verbose_name='실패 수')),
                ('meta_json', models.JSONField(blank=True, default=dict, verbose_name='메타 정보')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '퀴즈 배치 작업',
                'verbose_name_plural': '퀴즈 배치 작업',
            },
        ),
        migrations.CreateModel(
            name='SQRagDailyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_date', models.DateField(verbose_name='사용 날짜')),
                ('count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAG 일일 사용량',
                'verbose_name_plural': 'RAG 일일 사용량',
            },
        ),
        migrations.AddField(
            model_name='sqquizbank',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='노출 시작일'),
        ),
        migrations.AddField(
            model_name='sqquizbank',
            name='available_to',
            field=models.DateField(blank=True, null=True, verbose_name='노출 종료일'),
        ),
        migrations.AddField(
            model_name='sqquizbank',
            name='quality_status',
            field=models.CharField(choices=[('draft', '초안'), ('review', '검토대기'), ('approved', '승인'), ('rejected', '반려')], default='approved', max_length=10, verbose_name='품질 상태'),
        ),
        migrations.AddField(
            model_name='sqquizbank',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토 시각'),
        ),
        migrations.AddField(
            model_name='sqquizbank',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sq_quiz_banks_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
        migrations.AddField(
            model_name='sqquizbank',
            name='share_opt_in',
            field=models.BooleanField(default=False, verbose_name='공유 신청'),
        ),
        migrations.AddIndex(
            model_name='sqquizbank',
            index=models.Index(fields=['quality_status', 'is_active'], name='seed_quiz_s_quality_ca8a3d_idx'),
        ),
        migrations.AddField(
            model_name='sqbatchjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sq_batch_jobs_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='sqragdailyusage',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sq_rag_usages', to='happy_seed.hsclassroom', verbose_name='교실'),
        ),
        migrations.AddField(
            model_name='sqragdailyusage',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sq_rag_usages', to=settings.AUTH_USER_MODEL, verbose_name='교사'),
        ),
        migrations.AddIndex(
            model_name='sqbatchjob',
            index=models.Index(fields=['status', 'target_month'], name='seed_quiz_s_status_4539b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sqbatchjob',
            index=models.Index(fields=['provider', 'target_month'], name='seed_quiz_s_provide_96346a_idx'),
        ),
        migrations.AddIndex(
            model_name='sqragdailyusage',
            index=models.Index(fields=['usage_date', 'teacher'], name='seed_quiz_s_usage_d_caeff5_idx'),
        ),
        migrations.AddIndex(
            model_name='sqragdailyusage',
            index=models.Index(fields=['usage_date', 'classroom'], name='seed_quiz_s_usage_d_b17791_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sqragdailyusage',
            unique_together={('usage_date', 'classroom', 'teacher')},
        ),
    ]
