# Generated by Django 6.0.1 on 2026-02-21 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_quiz', '0003_sqbatchjob_sqragdailyusage_sqquizbank_available_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sqquizbank',
            name='source_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='원문 해시'),
        ),
        migrations.AddIndex(
            model_name='sqquizbank',
            index=models.Index(fields=['source_hash', 'created_at'], name='seed_quiz_s_source__3a2d4d_idx'),
        ),
    ]
