# Generated by Django 6.0.1 on 2026-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_quiz', '0004_sqquizbank_source_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqquizbank',
            name='preset_type',
            field=models.CharField(choices=[('orthography', '맞춤법'), ('spacing', '띄어쓰기'), ('vocabulary', '어휘 뜻'), ('proverb', '속담'), ('idiom', '관용어'), ('sino_idiom', '사자성어'), ('hanja_word', '한자어 뜻'), ('main_sentence', '중심문장 찾기'), ('sentence_order', '문장 순서 배열'), ('topic_title', '주제/제목 고르기'), ('fact_opinion', '사실/의견 구분'), ('eng_vocab', '영어 단어 뜻'), ('eng_sentence', '영어 문장 의미'), ('eng_cloze', '영어 빈칸 채우기'), ('arithmetic', '수학 연산'), ('pattern', '규칙 찾기'), ('fraction_decimal', '분수/소수 비교'), ('time_calendar', '시간/달력 계산'), ('unit_conversion', '단위 변환'), ('safety_common', '생활 안전 상식')], default='orthography', max_length=20, verbose_name='주제'),
        ),
        migrations.AlterField(
            model_name='sqquizset',
            name='preset_type',
            field=models.CharField(choices=[('orthography', '맞춤법'), ('spacing', '띄어쓰기'), ('vocabulary', '어휘 뜻'), ('proverb', '속담'), ('idiom', '관용어'), ('sino_idiom', '사자성어'), ('hanja_word', '한자어 뜻'), ('main_sentence', '중심문장 찾기'), ('sentence_order', '문장 순서 배열'), ('topic_title', '주제/제목 고르기'), ('fact_opinion', '사실/의견 구분'), ('eng_vocab', '영어 단어 뜻'), ('eng_sentence', '영어 문장 의미'), ('eng_cloze', '영어 빈칸 채우기'), ('arithmetic', '수학 연산'), ('pattern', '규칙 찾기'), ('fraction_decimal', '분수/소수 비교'), ('time_calendar', '시간/달력 계산'), ('unit_conversion', '단위 변환'), ('safety_common', '생활 안전 상식')], default='orthography', max_length=20, verbose_name='주제'),
        ),
    ]
