# Generated by Codex on 2026-02-21

from django.db import migrations


LEGACY_TO_TOPIC = {
    "general": "vocabulary",
    "korean": "main_sentence",
    "english": "eng_vocab",
    "math": "arithmetic",
    "science": "safety_common",
    "social": "fact_opinion",
}


def forwards(apps, schema_editor):
    SQQuizBank = apps.get_model("seed_quiz", "SQQuizBank")
    SQQuizSet = apps.get_model("seed_quiz", "SQQuizSet")

    for legacy, topic in LEGACY_TO_TOPIC.items():
        SQQuizBank.objects.filter(preset_type=legacy).update(preset_type=topic)
        SQQuizSet.objects.filter(preset_type=legacy).update(preset_type=topic)


def backwards(apps, schema_editor):
    SQQuizBank = apps.get_model("seed_quiz", "SQQuizBank")
    SQQuizSet = apps.get_model("seed_quiz", "SQQuizSet")

    for legacy, topic in LEGACY_TO_TOPIC.items():
        SQQuizBank.objects.filter(preset_type=topic).update(preset_type=legacy)
        SQQuizSet.objects.filter(preset_type=topic).update(preset_type=legacy)


class Migration(migrations.Migration):

    dependencies = [
        ("seed_quiz", "0005_alter_sqquizbank_preset_type_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
