# Generated by Django 6.0.1 on 2026-02-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_quiz', '0006_migrate_legacy_preset_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqquizbank',
            name='grade',
            field=models.IntegerField(choices=[(0, '학년무관'), (1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], default=3, verbose_name='학년'),
        ),
        migrations.AlterField(
            model_name='sqquizset',
            name='grade',
            field=models.IntegerField(choices=[(0, '학년무관'), (1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], default=3, verbose_name='학년'),
        ),
    ]
