# Generated by Django 6.0.3 on 2026-04-18 08:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0006_alter_hsclasseventlog_type_alter_hsseedledger_reason'),
        ('seed_quiz', '0009_alter_sqquizset_status_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SQGamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, verbose_name='표시 이름')),
                ('create_score', models.IntegerField(default=0, verbose_name='출제 점수')),
                ('solve_score', models.IntegerField(default=0, verbose_name='풀이 점수')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='순위')),
                ('is_connected', models.BooleanField(default=True, verbose_name='접속 중')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 접속')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sq_game_players', to='happy_seed.hsstudent', verbose_name='학생')),
            ],
            options={
                'verbose_name': '실시간 게임 참가자',
                'verbose_name_plural': '실시간 게임 참가자',
                'ordering': ['rank', 'student__number', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='SQGameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='게임 이름')),
                ('topic', models.CharField(choices=[('orthography', '맞춤법'), ('spacing', '띄어쓰기'), ('vocabulary', '어휘 뜻'), ('proverb', '속담'), ('idiom', '관용어'), ('sino_idiom', '사자성어'), ('hanja_word', '한자어 뜻'), ('main_sentence', '중심문장 찾기'), ('sentence_order', '문장 순서 배열'), ('topic_title', '주제/제목 고르기'), ('fact_opinion', '사실/의견 구분'), ('eng_vocab', '영어 단어 뜻'), ('eng_sentence', '영어 문장 의미'), ('eng_cloze', '영어 빈칸 채우기'), ('arithmetic', '수학 연산'), ('pattern', '규칙 찾기'), ('fraction_decimal', '분수/소수 비교'), ('time_calendar', '시간/달력 계산'), ('unit_conversion', '단위 변환'), ('safety_common', '생활 안전 상식')], default='orthography', max_length=20, verbose_name='주제')),
                ('grade', models.IntegerField(choices=[(0, '학년무관'), (1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '5학년'), (6, '6학년')], default=3, verbose_name='학년')),
                ('join_code', models.CharField(max_length=8, unique=True, verbose_name='입장 코드')),
                ('status', models.CharField(choices=[('waiting', '입장 대기'), ('creating', '문제 만들기'), ('playing', '문제 풀기'), ('finished', '결과')], default='waiting', max_length=12, verbose_name='상태')),
                ('question_mode', models.CharField(choices=[('mixed', '혼합'), ('ox', 'O/X'), ('mc4', '4지선다')], default='mixed', max_length=10, verbose_name='문제 형식')),
                ('questions_per_player', models.PositiveSmallIntegerField(default=1, verbose_name='학생당 출제 수')),
                ('solve_target_count', models.PositiveSmallIntegerField(default=5, verbose_name='학생당 풀이 수')),
                ('create_time_seconds', models.PositiveIntegerField(default=300, verbose_name='출제 시간(초)')),
                ('solve_time_seconds', models.PositiveIntegerField(default=300, verbose_name='풀이 시간(초)')),
                ('reward_enabled', models.BooleanField(default=False, verbose_name='씨앗 보상')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='설정')),
                ('phase_started_at', models.DateTimeField(blank=True, null=True, verbose_name='단계 시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sq_game_rooms', to='happy_seed.hsclassroom', verbose_name='교실')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sq_game_rooms_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '실시간 게임 방',
                'verbose_name_plural': '실시간 게임 방',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SQGameReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(verbose_name='순위')),
                ('seed_amount', models.PositiveIntegerField(default=0, verbose_name='보상 씨앗')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='보상 요청 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='seed_quiz.sqgameplayer', verbose_name='참가자')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='seed_quiz.sqgameroom', verbose_name='게임')),
            ],
            options={
                'verbose_name': '실시간 게임 보상',
                'verbose_name_plural': '실시간 게임 보상',
                'ordering': ['rank', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SQGameQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('ox', 'O/X'), ('mc4', '4지선다')], default='mc4', max_length=8, verbose_name='문제 형식')),
                ('question_text', models.TextField(verbose_name='문제')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='정답 텍스트')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='보기')),
                ('correct_index', models.IntegerField(default=0, verbose_name='정답 인덱스')),
                ('ai_quality_score', models.IntegerField(default=0, verbose_name='AI 품질 점수')),
                ('ai_quality_json', models.JSONField(blank=True, default=dict, verbose_name='AI 평가')),
                ('ai_feedback', models.CharField(blank=True, default='', max_length=255, verbose_name='AI 피드백')),
                ('base_points', models.IntegerField(default=0, verbose_name='기본 점수')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('pending_ai', 'AI 평가중'), ('ready', '사용 가능'), ('rejected', '제외')], default='draft', max_length=12, verbose_name='상태')),
                ('ai_started_at', models.DateTimeField(blank=True, null=True, verbose_name='AI 시작 시각')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시각')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='평가 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_questions', to='seed_quiz.sqgameplayer', verbose_name='출제자')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='seed_quiz.sqgameroom', verbose_name='게임')),
            ],
            options={
                'verbose_name': '실시간 게임 문제',
                'verbose_name_plural': '실시간 게임 문제',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='sqgameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='seed_quiz.sqgameroom', verbose_name='게임'),
        ),
        migrations.CreateModel(
            name='SQGameAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_index', models.IntegerField(verbose_name='선택한 답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('time_taken_ms', models.PositiveIntegerField(default=0, verbose_name='소요 시간(ms)')),
                ('points_earned', models.IntegerField(default=0, verbose_name='획득 점수')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='답변 시각')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='seed_quiz.sqgameplayer', verbose_name='풀이자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='seed_quiz.sqgamequestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': '실시간 게임 답변',
                'verbose_name_plural': '실시간 게임 답변',
                'indexes': [models.Index(fields=['question', 'player'], name='seed_quiz_s_questio_b7b4f3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('selected_index__gte', 0), ('selected_index__lte', 3)), name='sq_game_answer_selected_index_range')],
                'unique_together': {('question', 'player')},
            },
        ),
        migrations.AddIndex(
            model_name='sqgameroom',
            index=models.Index(fields=['classroom', 'status', '-created_at'], name='seed_quiz_s_classro_2fdd49_idx'),
        ),
        migrations.AddIndex(
            model_name='sqgameroom',
            index=models.Index(fields=['join_code'], name='seed_quiz_s_join_co_e8ba61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sqgamereward',
            unique_together={('game', 'player')},
        ),
        migrations.AddIndex(
            model_name='sqgamequestion',
            index=models.Index(fields=['game', 'status', 'created_at'], name='seed_quiz_s_game_id_744005_idx'),
        ),
        migrations.AddIndex(
            model_name='sqgamequestion',
            index=models.Index(fields=['author', 'status'], name='seed_quiz_s_author__5972b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sqgamequestion',
            constraint=models.CheckConstraint(condition=models.Q(('correct_index__gte', 0), ('correct_index__lte', 3)), name='sq_game_question_correct_index_range'),
        ),
        migrations.AddIndex(
            model_name='sqgameplayer',
            index=models.Index(fields=['game', 'rank'], name='seed_quiz_s_game_id_b624b9_idx'),
        ),
        migrations.AddIndex(
            model_name='sqgameplayer',
            index=models.Index(fields=['game', 'is_connected'], name='seed_quiz_s_game_id_9ff553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sqgameplayer',
            unique_together={('game', 'student')},
        ),
    ]
