# Generated by Django 6.0.1 on 2026-03-22 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickdrop', '0002_channel_pair_nonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickdropItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_label', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('text', '텍스트'), ('image', '이미지')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quickdrop/items/%Y/%m/')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quickdrop.quickdropchannel')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
