# Generated by Django 6.0.3 on 2026-04-24 12:01

import quickdrop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickdrop', '0004_quickdrop_file_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickdropitem',
            name='file',
            field=models.FileField(blank=True, null=True, storage=quickdrop.models._get_raw_storage, upload_to='quickdrop/items/%Y/%m/'),
        ),
    ]
