# Generated by Django 6.0.3 on 2026-04-25 23:19

import django.db.models.deletion
import guide_recorder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '가이드 세션',
                'verbose_name_plural': '가이드 세션들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('screenshot', models.ImageField(blank=True, upload_to=guide_recorder.models.guide_step_screenshot_upload_to)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('click_x', models.FloatField(default=0.0)),
                ('click_y', models.FloatField(default=0.0)),
                ('element_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guide_recorder.guidesession')),
            ],
            options={
                'verbose_name': '가이드 스텝',
                'verbose_name_plural': '가이드 스텝들',
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
