from pathlib import Path

from django.conf import settings
from django.test import Client, TestCase, override_settings
from django.urls import reverse


class DutyTickerTimerUiTests(TestCase):
    def setUp(self):
        self.client = Client()

    def test_dutyticker_page_renders_minute_step_timer_controls(self):
        response = self.client.get(reverse('dutyticker'))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'products/dutyticker/main.html')

        self.assertContains(response, 'id="customTimerMinutesInput"')
        self.assertContains(response, 'csrfToken:')
        self.assertContains(response, 'max="999"')
        self.assertContains(response, 'step="1"')
        self.assertContains(response, 'id="mainTimerDisplay" type="button"')
        self.assertContains(response, 'window.__DT_INITIAL_THEME__ = "deep_space";')
        self.assertContains(response, 'class="dt-clock-stage"')
        self.assertContains(response, 'class="dt-mission-stage"')
        self.assertContains(response, 'class="dt-mission-kicker">오늘 안내</div>')
        self.assertContains(response, 'id="timerAddMinuteBtn"')
        self.assertContains(response, 'id="timerPreset5Btn"')
        self.assertContains(response, 'id="timerPreset10Btn"')
        self.assertContains(response, 'id="timerCustomApplyBtn"')
        self.assertContains(response, 'id="timerResetBtn"')
        self.assertContains(response, 'id="roleResetAssignmentsBtn"')
        self.assertContains(response, 'window.dtApp.resetRoleAssignments()')
        self.assertContains(response, 'id="missionProgressResetBtn"')
        self.assertContains(response, 'window.dtApp.resetStudentMissionProgress()')
        self.assertContains(response, 'id="resetConfirmModal"')
        self.assertContains(response, 'id="dtActionToast"')
        self.assertNotContains(response, 'id="roleRotateNowBtn"')
        self.assertContains(response, 'title="별빛 추첨기"')
        self.assertContains(response, 'title="새 창으로 열기"')
        self.assertContains(response, 'title="전체화면"')
        self.assertNotContains(response, 'title="나가기"')
        self.assertContains(response, reverse('ppobgi:main'))
        self.assertContains(response, 'id="mainMissionTitle" contenteditable="true"')
        self.assertContains(response, 'id="mainMissionDesc" contenteditable="true"')
        self.assertContains(response, 'window.dtApp.changeMissionFontSize(-1)')
        self.assertContains(response, 'id="missionFontSizeLabel"')
        self.assertContains(response, 'id="missionQuickSaveBtn"')
        self.assertContains(response, 'id="missionQuickApplyBtn"')
        self.assertContains(response, 'id="missionQuickApplyLabel"')
        self.assertNotContains(response, 'id="missionQuickAutoBadge"')
        self.assertContains(response, 'id="missionQuickPhraseModal"')
        self.assertContains(response, 'id="missionQuickModalCount"')
        self.assertContains(response, 'id="missionQuickModalSelection"')
        self.assertContains(response, 'id="missionAutomationCount"')
        self.assertContains(response, 'id="missionAutomationActiveStatus"')
        self.assertContains(response, 'id="missionAutomationToggleBtn"')
        self.assertNotContains(response, 'id="missionAutomationList"')
        self.assertContains(response, 'id="missionAutomationSlotSummary"')
        self.assertContains(response, 'id="missionAutomationSlotList"')
        self.assertContains(response, 'id="missionAutomationApplyAllBtn"')
        self.assertContains(response, 'id="missionAutomationPhraseLabel"')
        self.assertContains(response, 'id="missionAutomationPhrasePreview"')
        self.assertContains(response, 'id="missionPhrasePanelSummary"')
        self.assertNotContains(response, 'id="missionPhrasePanelToggleBtn"')
        self.assertContains(response, 'id="missionPhrasePanelBody" class="mt-4 grid')
        self.assertContains(response, 'id="missionAutomationPanelBody" class="hidden')
        self.assertContains(response, '시간표 자동 적용')
        self.assertContains(response, '시간별 예외 설정')
        self.assertNotContains(response, '자동화 만들기')
        self.assertNotContains(response, '자동화 목록')
        self.assertContains(response, 'id="missionQuickPhraseList"')
        self.assertContains(response, 'id="missionQuickTitleInput"')
        self.assertContains(response, 'id="missionQuickDescInput"')
        self.assertContains(response, 'id="missionQuickLoadCurrentBtn"')
        self.assertContains(response, 'id="missionQuickCreateBtn"')
        self.assertContains(response, 'id="missionQuickUpdateBtn"')
        self.assertContains(response, 'id="missionQuickApplySelectedBtn"')
        self.assertContains(response, 'id="missionQuickDeleteBtn"')
        self.assertContains(response, 'id="missionQuickDeleteAllBtn"')
        self.assertNotContains(response, 'id="missionAutomationNewBtn"')
        self.assertNotContains(response, 'id="missionAutomationEnabledInput"')
        self.assertNotContains(response, 'id="missionAutomationCreateBtn"')
        self.assertNotContains(response, 'id="missionAutomationUpdateBtn"')
        self.assertNotContains(response, 'id="missionAutomationDeleteBtn"')
        self.assertNotContains(response, 'id="missionAutomationNameInput"')
        self.assertNotContains(response, 'id="missionAutomationStartInput"')
        self.assertNotContains(response, 'id="missionAutomationEndInput"')
        self.assertNotContains(response, 'id="missionAutomationMinutesInput"')
        self.assertContains(response, 'data-layout-density="presentation"')
        self.assertContains(response, 'data-display-mode="windowed"')
        self.assertContains(response, 'data-mission-stack-fit="normal"')
        self.assertContains(response, 'id="headerScheduleStrip"')
        self.assertNotContains(response, 'service-shell-fixed')
        self.assertContains(
            response,
            'class="fixed inset-0 z-[100] bg-slate-900 text-white p-4 md:p-6 font-sans overflow-x-hidden overflow-y-auto flex flex-col"',
        )
        self.assertContains(response, 'class="dt-student-card-head')
        self.assertContains(response, 'id="randomDrawName"')
        self.assertContains(response, 'id="randomDrawBtn"')
        self.assertContains(response, 'id="randomDrawResetBtn"')
        self.assertContains(response, 'window.dtApp.drawRandomStudent()')
        self.assertContains(response, 'window.dtApp.resetRandomPicker()')
        self.assertNotContains(response, 'id="bgmControls"')
        self.assertNotContains(response, 'id="bgmToggleBtn"')
        self.assertNotContains(response, 'id="bgmLoopModeBtn"')
        self.assertNotContains(response, 'id="bgmTrackRail"')
        self.assertNotContains(response, 'id="bgmVolumeRange"')
        self.assertNotContains(response, 'id="bgmVolumeValue"')
        self.assertNotContains(response, '<div class="dt-topbar-shell">')
        self.assertNotContains(response, 'EDUITIT CLASS OPS')
        self.assertNotContains(response, '<article id="headerOpsSummaryCard"')
        self.assertNotContains(response, 'window.dtBgmTracks = {')
        self.assertContains(response, '--dt-role-assignee-bg: #ecfeff;')
        self.assertContains(response, '--dt-role-assignee-border: #67e8f9;')
        self.assertContains(response, '--dt-role-assignee-bg: #f5f3ff;')
        self.assertContains(response, '--dt-role-assignee-border: #c084fc;')
        self.assertContains(response, '--dt-quick-modal-shell-bg: rgba(255, 255, 255, 0.97);')
        self.assertContains(response, '--dt-quick-modal-section-bg: rgba(236, 253, 245, 0.96);')
        self.assertContains(response, '--dt-quick-modal-selected-border: #fb7185;')
        self.assertContains(response, 'dt-quick-modal-shell')
        self.assertContains(response, 'dt-quick-modal-input')
        self.assertNotContains(response, '천리 길도 한 걸음부터')
        self.assertNotContains(response, 'id="breakAutoOpenBtn"')

    @override_settings(CSRF_COOKIE_HTTPONLY=True)
    def test_dutyticker_page_exposes_csrf_token_for_http_only_cookie_mode(self):
        response = self.client.get(reverse('dutyticker'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'csrfToken:')

    def test_timer_script_contains_safety_and_restore_methods(self):
        script_path = Path(settings.BASE_DIR) / 'products' / 'static' / 'products' / 'dutyticker' / 'js' / 'dutyticker.js'
        script = script_path.read_text(encoding='utf-8')

        self.assertIn('escapeHtml(value)', script)
        self.assertIn('timerStorageKey', script)
        self.assertIn('normalizeTimerSeconds(', script)
        self.assertIn('saveTimerState()', script)
        self.assertIn('restoreTimerState()', script)
        self.assertIn('getRemainingTimerSeconds(', script)
        self.assertIn('finishTimer()', script)
        self.assertIn('Math.min(999', script)
        self.assertIn("display.setAttribute('aria-pressed'", script)
        self.assertIn("bindButtonAction('timerPreset5Btn'", script)
        self.assertIn('this.timerMaxSeconds = 300;', script)
        self.assertIn('this.timerSeconds = 300;', script)
        self.assertIn('syncRandomPickerStudents()', script)
        self.assertIn('renderRandomPicker()', script)
        self.assertIn('drawRandomStudent()', script)
        self.assertIn('resetRandomPicker()', script)
        self.assertIn('resetRoleAssignments()', script)
        self.assertIn('performResetRoleAssignments()', script)
        self.assertIn('resetStudentMissionProgress()', script)
        self.assertIn('performResetStudentMissionProgress()', script)
        self.assertIn('requestResetConfirmation(', script)
        self.assertIn("showToast(message, tone = 'info')", script)
        self.assertIn("this.getApiUrl('resetAssignmentsUrl'", script)
        self.assertIn("this.getApiUrl('resetStudentMissionsUrl'", script)
        self.assertIn("options.credentials = 'same-origin'", script)
        self.assertIn('getCsrfToken()', script)
        self.assertIn('this.api.csrfToken', script)
        self.assertIn("cache: 'no-store'", script)
        self.assertIn('buildFreshUrl(url)', script)
        self.assertIn('openCurrentPageInNewWindow()', script)
        self.assertIn("window.open(targetUrl, 'eduititDutyTickerDisplayWindow')", script)
        self.assertIn('브라우저에서 팝업 허용 후 다시 시도해 주세요.', script)
        self.assertIn('applyThemeToDom(theme = this.theme)', script)
        self.assertIn('window.__DT_INITIAL_THEME__ = nextTheme;', script)
        self.assertNotIn('dt-bgm-state-v1', script)
        self.assertNotIn('bgmVolumePercent', script)
        self.assertNotIn('setupBgm()', script)
        self.assertNotIn('setBgmVolumePercent(', script)
        self.assertNotIn('toggleBgmLoopMode()', script)
        self.assertNotIn('renderBgmTrackRail()', script)
        self.assertNotIn('nextBgmTrack(', script)
        self.assertNotIn('prevBgmTrack(', script)
        self.assertIn('setupInlineMissionEditor()', script)
        self.assertIn('saveInlineMissionEdit()', script)
        self.assertIn('event.shiftKey', script)
        self.assertIn('changeMissionFontSize(', script)
        self.assertIn("this.missionFontSizeOrder = ['xxxs', 'xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl'];", script)
        self.assertIn('dt-mission-quick-phrase-v1', script)
        self.assertIn('missionAutomations = [];', script)
        self.assertIn('this.timeSlots = [];', script)
        self.assertIn('missionAutomationSelectedId = null;', script)
        self.assertIn('dt-mission-automation-runtime-v1', script)
        self.assertIn('restoreMissionQuickPhrase()', script)
        self.assertIn('applyMissionQuickPhrase()', script)
        self.assertIn('restoreMissionAutomationRuntime()', script)
        self.assertIn('setTimeSlots(data.timeSlots || []);', script)
        self.assertIn('setMissionAutomations(data.automations || []);', script)
        self.assertIn('getActiveMissionAutomation(now = new Date())', script)
        self.assertIn('syncMissionAutomationState(now = new Date())', script)
        self.assertIn('missionAutomationPanelExpanded = false;', script)
        self.assertIn('toggleMissionAutomationPanel(forceExpanded = null)', script)
        self.assertIn('renderMissionAutomationPanel()', script)
        self.assertIn('renderMissionAutomationManager()', script)
        self.assertIn('serializeMissionAutomations(rows = this.getSortedMissionAutomations())', script)
        self.assertIn('assignSelectedMissionQuickPhraseToAutomationSlot(slotCode)', script)
        self.assertIn('applySelectedMissionQuickPhraseToAllAutomationSlots()', script)
        self.assertIn('toggleMissionAutomationSlotEnabled(slotCode, enabled)', script)
        self.assertIn('deleteMissionAutomationBySlot(slotCode)', script)
        self.assertIn('renderMissionPhrasePanel()', script)
        self.assertIn('missionQuickSelectedId = null;', script)
        self.assertIn('openMissionQuickPhraseModal()', script)
        self.assertIn('renderMissionQuickPhraseModal()', script)
        self.assertIn('selectMissionQuickPhrase(', script)
        self.assertIn('deleteSelectedMissionQuickPhrase()', script)
        self.assertIn('clearMissionQuickPhrases()', script)
        self.assertIn('normalizeSpotlightStudentId(', script)
        self.assertIn('updateRoleCardSubtitle(', script)
        self.assertIn('clearRoleTickerClasses(', script)
        self.assertIn('triggerRoleTickerEntry(', script)
        self.assertIn('scrollRoleRowIntoViewIfNeeded(', script)
        self.assertIn('dt-role-cycle-enter', script)
        self.assertIn("prefers-reduced-motion: reduce", script)
        self.assertIn('현재 강조', script)
        self.assertIn('spotlightStudentId === null', script)
        self.assertIn('startHeaderClock()', script)
        self.assertIn('updateHeaderClock()', script)
        self.assertIn('setupAdaptiveLayoutObserver()', script)
        self.assertIn('measureMissionStackState()', script)
        self.assertIn('resolveAdaptiveDensity(app, displayMode, baseDensity)', script)
        self.assertIn('applyAdaptiveLayoutState()', script)
        self.assertIn("const shouldShowAllMorningSlots = showAllMorningSlots && displayMode === 'fullscreen';", script)
        self.assertIn("if (!candidateSlots.length && showAllMorningSlots && displayMode === 'windowed') {", script)
        self.assertIn("data-mission-stack-fit', this.missionPanelCollapsed ? 'normal' : resolvedLayout.fit", script)
        self.assertIn("data-display-mode', displayMode", script)
        self.assertIn("data-layout-density', density", script)
        self.assertIn('fullscreenchange', script)
        self.assertIn('grid.dataset.gridColumns', script)
        self.assertIn("const morningSlot = this.getTodaySlotByCode('morning');", script)
        self.assertIn('getScheduleSubjectName(slot)', script)
        self.assertIn('다음 교시 10분 전부터 표시됩니다', script)
