from pathlib import Path

from django.conf import settings
from django.test import Client, TestCase, override_settings
from django.urls import reverse


class DutyTickerTimerUiTests(TestCase):
    def setUp(self):
        self.client = Client()

    def test_dutyticker_page_renders_minute_step_timer_controls(self):
        response = self.client.get(reverse('dutyticker'))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, 'products/dutyticker/main.html')

        self.assertContains(response, 'id="customTimerMinutesInput"')
        self.assertContains(response, 'csrfToken:')
        self.assertContains(response, 'max="999"')
        self.assertContains(response, 'step="1"')
        self.assertContains(response, 'id="mainTimerDisplay" type="button"')
        self.assertContains(response, 'window.__DT_INITIAL_THEME__ = "deep_space";')
        self.assertContains(response, 'class="dt-clock-stage"')
        self.assertContains(response, 'class="dt-mission-stage"')
        self.assertContains(response, 'class="dt-mission-kicker">오늘 안내</div>')
        self.assertContains(response, 'id="timerAddMinuteBtn"')
        self.assertContains(response, 'id="timerPreset5Btn"')
        self.assertContains(response, 'id="timerPreset10Btn"')
        self.assertContains(response, 'id="timerCustomApplyBtn"')
        self.assertContains(response, 'id="timerResetBtn"')
        self.assertContains(response, 'id="roleResetAssignmentsBtn"')
        self.assertContains(response, 'window.dtApp.resetRoleAssignments()')
        self.assertContains(response, 'id="missionProgressResetBtn"')
        self.assertContains(response, 'window.dtApp.resetStudentMissionProgress()')
        self.assertContains(response, 'id="resetConfirmModal"')
        self.assertContains(response, 'id="dtActionToast"')
        self.assertNotContains(response, 'id="roleRotateNowBtn"')
        self.assertContains(response, 'title="별빛 추첨기"')
        self.assertContains(response, 'title="전체화면"')
        self.assertNotContains(response, 'title="나가기"')
        self.assertContains(response, reverse('ppobgi:main'))
        self.assertContains(response, 'id="mainMissionTitle" contenteditable="true"')
        self.assertContains(response, 'id="mainMissionDesc" contenteditable="true"')
        self.assertContains(response, 'window.dtApp.changeMissionFontSize(-1)')
        self.assertContains(response, 'id="missionFontSizeLabel"')
        self.assertContains(response, 'id="missionQuickSaveBtn"')
        self.assertContains(response, 'id="missionQuickApplyBtn"')
        self.assertContains(response, 'id="missionQuickPhraseModal"')
        self.assertContains(response, 'id="missionQuickModalCount"')
        self.assertContains(response, 'id="missionQuickPhraseList"')
        self.assertContains(response, 'id="missionQuickTitleInput"')
        self.assertContains(response, 'id="missionQuickDescInput"')
        self.assertContains(response, 'id="missionQuickLoadCurrentBtn"')
        self.assertContains(response, 'id="missionQuickCreateBtn"')
        self.assertContains(response, 'id="missionQuickUpdateBtn"')
        self.assertContains(response, 'id="missionQuickApplySelectedBtn"')
        self.assertContains(response, 'id="missionQuickDeleteBtn"')
        self.assertContains(response, 'id="missionQuickDeleteAllBtn"')
        self.assertContains(response, 'data-layout-density="presentation"')
        self.assertContains(response, 'data-display-mode="windowed"')
        self.assertContains(response, 'class="dt-student-card-head')
        self.assertContains(response, 'id="randomDrawName"')
        self.assertContains(response, 'id="randomDrawBtn"')
        self.assertContains(response, 'id="randomDrawResetBtn"')
        self.assertContains(response, 'window.dtApp.drawRandomStudent()')
        self.assertContains(response, 'window.dtApp.resetRandomPicker()')
        self.assertContains(response, 'id="bgmControls"')
        self.assertContains(response, 'id="bgmToggleBtn"')
        self.assertContains(response, 'id="bgmLoopModeBtn"')
        self.assertContains(response, 'id="bgmTrackRail"')
        self.assertContains(response, 'id="bgmVolumeRange"')
        self.assertContains(response, 'id="bgmVolumeValue"')
        self.assertContains(response, 'window.dtBgmTracks = {')
        self.assertNotContains(response, '천리 길도 한 걸음부터')

    @override_settings(CSRF_COOKIE_HTTPONLY=True)
    def test_dutyticker_page_exposes_csrf_token_for_http_only_cookie_mode(self):
        response = self.client.get(reverse('dutyticker'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'csrfToken:')

    def test_timer_script_contains_safety_and_restore_methods(self):
        script_path = Path(settings.BASE_DIR) / 'products' / 'static' / 'products' / 'dutyticker' / 'js' / 'dutyticker.js'
        script = script_path.read_text(encoding='utf-8')

        self.assertIn('escapeHtml(value)', script)
        self.assertIn('timerStorageKey', script)
        self.assertIn('normalizeTimerSeconds(', script)
        self.assertIn('saveTimerState()', script)
        self.assertIn('restoreTimerState()', script)
        self.assertIn('getRemainingTimerSeconds(', script)
        self.assertIn('finishTimer()', script)
        self.assertIn('Math.min(999', script)
        self.assertIn("display.setAttribute('aria-pressed'", script)
        self.assertIn("bindButtonAction('timerPreset5Btn'", script)
        self.assertIn('this.timerMaxSeconds = 300;', script)
        self.assertIn('this.timerSeconds = 300;', script)
        self.assertIn('syncRandomPickerStudents()', script)
        self.assertIn('renderRandomPicker()', script)
        self.assertIn('drawRandomStudent()', script)
        self.assertIn('resetRandomPicker()', script)
        self.assertIn('resetRoleAssignments()', script)
        self.assertIn('performResetRoleAssignments()', script)
        self.assertIn('resetStudentMissionProgress()', script)
        self.assertIn('performResetStudentMissionProgress()', script)
        self.assertIn('requestResetConfirmation(', script)
        self.assertIn("showToast(message, tone = 'info')", script)
        self.assertIn("this.getApiUrl('resetAssignmentsUrl'", script)
        self.assertIn("this.getApiUrl('resetStudentMissionsUrl'", script)
        self.assertIn("options.credentials = 'same-origin'", script)
        self.assertIn('getCsrfToken()', script)
        self.assertIn('this.api.csrfToken', script)
        self.assertIn("cache: 'no-store'", script)
        self.assertIn('buildFreshUrl(url)', script)
        self.assertIn('applyThemeToDom(theme = this.theme)', script)
        self.assertIn('window.__DT_INITIAL_THEME__ = nextTheme;', script)
        self.assertIn('dt-bgm-state-v1', script)
        self.assertIn('bgmVolumePercent', script)
        self.assertIn('setupBgm()', script)
        self.assertIn('setBgmVolumePercent(', script)
        self.assertIn('toggleBgmLoopMode()', script)
        self.assertIn('renderBgmTrackRail()', script)
        self.assertIn('nextBgmTrack(', script)
        self.assertIn('prevBgmTrack(', script)
        self.assertIn('setupInlineMissionEditor()', script)
        self.assertIn('saveInlineMissionEdit()', script)
        self.assertIn('event.shiftKey', script)
        self.assertIn('changeMissionFontSize(', script)
        self.assertIn("this.missionFontSizeOrder = ['xxxs', 'xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl'];", script)
        self.assertIn('dt-mission-quick-phrase-v1', script)
        self.assertIn('restoreMissionQuickPhrase()', script)
        self.assertIn('applyMissionQuickPhrase()', script)
        self.assertIn('missionQuickSelectedId = null;', script)
        self.assertIn('openMissionQuickPhraseModal()', script)
        self.assertIn('renderMissionQuickPhraseModal()', script)
        self.assertIn('selectMissionQuickPhrase(', script)
        self.assertIn('deleteSelectedMissionQuickPhrase()', script)
        self.assertIn('clearMissionQuickPhrases()', script)
        self.assertIn('normalizeSpotlightStudentId(', script)
        self.assertIn('updateRoleCardSubtitle(', script)
        self.assertIn('clearRoleTickerClasses(', script)
        self.assertIn('triggerRoleTickerEntry(', script)
        self.assertIn('scrollRoleRowIntoViewIfNeeded(', script)
        self.assertIn('dt-role-cycle-enter', script)
        self.assertIn("prefers-reduced-motion: reduce", script)
        self.assertIn('현재 강조', script)
        self.assertIn('spotlightStudentId === null', script)
        self.assertIn('startHeaderClock()', script)
        self.assertIn('updateHeaderClock()', script)
        self.assertIn('setupAdaptiveLayoutObserver()', script)
        self.assertIn('applyAdaptiveLayoutState()', script)
        self.assertIn("data-display-mode', displayMode", script)
        self.assertIn("data-layout-density', density", script)
        self.assertIn('fullscreenchange', script)
        self.assertIn('grid.dataset.gridColumns', script)
        self.assertIn('showAllMorningSlots = nowMinutes >= (8 * 60) && nowMinutes <= ((8 * 60) + 50);', script)
        self.assertIn('다음 교시 10분 전부터 표시됩니다', script)
