# Generated by Django 6.0.3 on 2026-04-13 07:33

import core.document_signing
import django.db.models.deletion
import docsign.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source_file', models.FileField(max_length=500, storage=core.document_signing.get_document_storage, upload_to=docsign.models.docsign_source_upload_to)),
                ('source_file_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('source_file_size_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_file_sha256_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], default='pdf', max_length=10)),
                ('signature_page', models.PositiveIntegerField(blank=True, null=True)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('signed_pdf', models.FileField(blank=True, max_length=500, null=True, storage=core.document_signing.get_raw_storage, upload_to=docsign.models.docsign_signed_upload_to)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sign_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
