# Generated by Django 6.0.3 on 2026-04-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignjob',
            name='mark_type',
            field=models.CharField(choices=[('signature', '사인'), ('checkmark', '체크')], default='signature', max_length=20),
        ),
    ]
