# Generated by Django 6.0.1 on 2026-02-06 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='예: 3학년 1반 MBTI 검사', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mbti_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학생 MBTI 검사 세션',
                'verbose_name_plural': '학생 MBTI 검사 세션 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentMBTIResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(help_text='학생 이름', max_length=50)),
                ('mbti_type', models.CharField(help_text='예: ENFP', max_length=4)),
                ('animal_name', models.CharField(help_text='예: 여우', max_length=50)),
                ('answers_json', models.JSONField(blank=True, help_text='학생이 선택한 답변들', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='studentmbti.testsession')),
            ],
            options={
                'verbose_name': '학생 MBTI 결과',
                'verbose_name_plural': '학생 MBTI 결과 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
