# Generated by Django 6.0.1 on 2026-02-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmbti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='access_code',
            field=models.CharField(blank=True, help_text='학생 입장 코드 (예: AB12CD)', max_length=10, null=True, unique=True),
        ),
    ]
