# Generated by Django 6.0.1 on 2026-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmbti', '0002_testsession_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmbtiresult',
            name='animal_name',
            field=models.CharField(blank=True, help_text='예: 여우', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentmbtiresult',
            name='mbti_type',
            field=models.CharField(blank=True, help_text='예: ENFP', max_length=4, null=True),
        ),
    ]
