# Generated by Django 6.0.1 on 2026-02-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmbti', '0003_alter_studentmbtiresult_animal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='access_code',
            field=models.CharField(blank=True, help_text='학생 입장 코드 (예: 123456)', max_length=6, null=True, unique=True),
        ),
    ]
