# Generated by Django 6.0.1 on 2026-02-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmbti', '0004_alter_testsession_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='test_type',
            field=models.CharField(choices=[('low', '저학년 (1~3학년)'), ('high', '고학년 (4~6학년)')], default='low', help_text='검사 유형 (저학년/고학년)', max_length=10),
        ),
    ]
