# Generated by Django 6.0.1 on 2026-02-22 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        ('studentmbti', '0006_add_mac_hash_to_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='연결된 학급 (학운위 학급 단축키)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mbti_sessions', to='happy_seed.hsclassroom'),
        ),
        migrations.AlterField(
            model_name='studentmbtiresult',
            name='mac_hash',
            field=models.CharField(blank=True, db_index=True, help_text='기기 식별 해시', max_length=64, null=True),
        ),
    ]
