# Generated by Django 6.0.1 on 2026-03-20 12:27

import django.db.models.deletion
import textbook_ai.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('KOREAN', '국어'), ('MATH', '수학'), ('SOCIAL', '사회'), ('SCIENCE', '과학'), ('ENGLISH', '영어'), ('OTHER', '기타')], default='OTHER', max_length=20)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('unit_title', models.CharField(blank=True, default='', max_length=200)),
                ('source_pdf', models.FileField(upload_to=textbook_ai.models.source_pdf_upload_to)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('license_confirmed', models.BooleanField(default=False)),
                ('parse_status', models.CharField(choices=[('queued', '대기 중'), ('processing', '읽는 중'), ('ready', '준비 완료'), ('needs_review', '검토 필요'), ('failed', '실패')], default='queued', max_length=20)),
                ('parser_name', models.CharField(blank=True, default='', max_length=50)),
                ('parser_mode', models.CharField(blank=True, default='', max_length=50)),
                ('parser_version', models.CharField(blank=True, default='', max_length=50)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbook_ai_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextbookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('heading', '제목'), ('text', '본문'), ('table', '표')], default='text', max_length=20)),
                ('heading_path', models.CharField(blank=True, default='', max_length=500)),
                ('text', models.TextField()),
                ('search_text', models.TextField(blank=True, default='')),
                ('page_from', models.PositiveIntegerField(default=1)),
                ('page_to', models.PositiveIntegerField(default=1)),
                ('bbox_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='textbook_ai.textbookdocument')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TextbookParseArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_json_file', models.FileField(blank=True, upload_to=textbook_ai.models.parsed_json_upload_to)),
                ('parsed_markdown_file', models.FileField(blank=True, upload_to=textbook_ai.models.parsed_markdown_upload_to)),
                ('parser_version', models.CharField(blank=True, default='', max_length=50)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('heading_count', models.PositiveIntegerField(default=0)),
                ('table_count', models.PositiveIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('text_char_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artifact', to='textbook_ai.textbookdocument')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='textbookdocument',
            index=models.Index(fields=['owner', 'updated_at'], name='textbook_ai_owner_i_611a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='textbookdocument',
            index=models.Index(fields=['owner', 'parse_status'], name='textbook_ai_owner_i_55c5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='textbookdocument',
            index=models.Index(fields=['owner', 'file_sha256'], name='textbook_ai_owner_i_4118bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='textbookdocument',
            constraint=models.UniqueConstraint(fields=('owner', 'file_sha256'), name='textbook_ai_unique_owner_file_sha256'),
        ),
        migrations.AddIndex(
            model_name='textbookchunk',
            index=models.Index(fields=['document', 'sort_order'], name='textbook_ai_documen_133736_idx'),
        ),
        migrations.AddIndex(
            model_name='textbookchunk',
            index=models.Index(fields=['document', 'page_from'], name='textbook_ai_documen_ba4d04_idx'),
        ),
        migrations.AddConstraint(
            model_name='textbookchunk',
            constraint=models.UniqueConstraint(fields=('document', 'sort_order'), name='textbook_ai_unique_document_sort_order'),
        ),
    ]
