"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: SECRET_KEY from environment variable
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only-change-in-production')

# SECURITY: DEBUG from environment (default False for safety)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# SECURITY: ALLOWED_HOSTS from environment
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Kakao API Key
KAKAO_JS_KEY = os.environ.get('KAKAO_JS_KEY', 'default-dev-key')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'core.apps.CoreConfig',
    'products.apps.ProductsConfig',
    'insights.apps.InsightsConfig',
    'portfolio.apps.PortfolioConfig',
    'autoarticle.apps.AutoarticleConfig',
    'fortune.apps.FortuneConfig',
    'signatures.apps.SignaturesConfig',
    'school_violence.apps.SchoolViolenceConfig',
    'artclass.apps.ArtclassConfig',
    'padlet_bot.apps.PadletBotConfig',
    
    # Auth & Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Allauth middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Settings
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SIGNUP_FIELDS = ['email', 'username*', 'password1*', 'password2*']
ACCOUNT_SESSION_REMEMBER = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True # ✅ 중간 페이지 없이 바로 소셜 로그인창으로 이동

# HTTPS 설정 (Railway 프록시 뒤에서 HTTPS 강제)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SSO Settings
SSO_JWT_SECRET = os.environ.get('SSO_JWT_SECRET', SECRET_KEY)
SCHOOLIT_URL = os.environ.get('SCHOOLIT_URL', 'http://localhost:3000') # schoolit 주소

# Allauth Provider Settings
# 환경변수: NAVER_CLIENT_ID, NAVER_CLIENT_SECRET, KAKAO_CLIENT_ID, KAKAO_CLIENT_SECRET
SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id': os.environ.get('KAKAO_CLIENT_ID', ''),
            'secret': os.environ.get('KAKAO_CLIENT_SECRET', ''),  # KAKAO_SECRET → KAKAO_CLIENT_SECRET
            'key': ''
        }
    },
    'naver': {
        'APP': {
            'client_id': os.environ.get('NAVER_CLIENT_ID', ''),
            'secret': os.environ.get('NAVER_CLIENT_SECRET', ''),  # NAVER_SECRET → NAVER_CLIENT_SECRET
            'key': ''
        }
    }
}

# 키 누락 시 로그 출력
import logging
logger = logging.getLogger(__name__)

if not SOCIALACCOUNT_PROVIDERS['naver']['APP']['client_id']:
    logger.warning("NAVER_CLIENT_ID is not set in environment variables!")
if not SOCIALACCOUNT_PROVIDERS['naver']['APP']['secret']:
    logger.warning("NAVER_CLIENT_SECRET is not set in environment variables!")
if not SOCIALACCOUNT_PROVIDERS['kakao']['APP']['client_id']:
    logger.warning("KAKAO_CLIENT_ID is not set in environment variables!")
if not SOCIALACCOUNT_PROVIDERS['kakao']['APP']['secret']:
    logger.warning("KAKAO_CLIENT_SECRET is not set in environment variables!")


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary 설정
print("=" * 80)
print("🔍 CLOUDINARY 환경 변수 체크")
print("=" * 80)

# 환경 변수 확인 (민감 정보 마스킹)
cloudinary_url = os.environ.get('CLOUDINARY_URL', '')
cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
api_key = os.environ.get('CLOUDINARY_API_KEY', '')
api_secret = os.environ.get('CLOUDINARY_API_SECRET', '')

print(f"CLOUDINARY_URL: {'설정됨' if cloudinary_url else '❌ 없음'}")
print(f"CLOUDINARY_CLOUD_NAME: {cloud_name if cloud_name else '❌ 없음'}")
print(f"CLOUDINARY_API_KEY: {api_key[:4] + '...' if api_key else '❌ 없음'}")
print(f"CLOUDINARY_API_SECRET: {'설정됨' if api_secret else '❌ 없음'}")

CLOUDINARY_STORAGE = {}

if cloudinary_url:
    print("📦 CLOUDINARY_URL 파싱 시도 중...")
    try:
        parsed = urlparse(cloudinary_url)
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': parsed.hostname or '',
            'API_KEY': parsed.username or '',
            'API_SECRET': parsed.password or '',
        }
        print(f"✅ 파싱 성공 - CLOUD_NAME: {parsed.hostname}")
    except Exception as e:
        print(f"❌ CLOUDINARY_URL 파싱 실패: {e}")
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': cloud_name,
            'API_KEY': api_key,
            'API_SECRET': api_secret,
        }
else:
    print("📦 개별 환경변수 사용")
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': cloud_name,
        'API_KEY': api_key,
        'API_SECRET': api_secret,
    }

# Cloudinary 라이브러리 직접 초기화
if CLOUDINARY_STORAGE.get('CLOUD_NAME') and CLOUDINARY_STORAGE.get('API_KEY'):
    try:
        import cloudinary
        cloudinary.config(
            cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
            api_key=CLOUDINARY_STORAGE['API_KEY'],
            api_secret=CLOUDINARY_STORAGE['API_SECRET'],
            secure=True
        )
        print(f"✅ Cloudinary 라이브러리 초기화 완료: {CLOUDINARY_STORAGE['CLOUD_NAME']}")
    except Exception as e:
        print(f"❌ Cloudinary 라이브러리 초기화 실패: {e}")

# Cloudinary 활성화 여부
USE_CLOUDINARY = bool(CLOUDINARY_STORAGE.get('CLOUD_NAME') and CLOUDINARY_STORAGE.get('API_KEY'))
print(f"🎯 USE_CLOUDINARY = {USE_CLOUDINARY}")

if USE_CLOUDINARY:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    print("✅ DEFAULT_FILE_STORAGE = cloudinary_storage.storage.MediaCloudinaryStorage")
else:
    print("❌ Cloudinary 비활성화 - 로컬 파일 시스템 사용")

print("=" * 80)

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
