"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from urllib.parse import urlparse
from dotenv import load_dotenv
from config.database import apply_database_network_overrides, normalize_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
load_dotenv(BASE_DIR / '.env')

# SSL Certificate fix for Windows local environment
if os.name == 'nt' and not os.environ.get('SSL_CERT_FILE'):
    try:
        import certifi
        os.environ['SSL_CERT_FILE'] = certifi.where()
        os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()
    except ImportError:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY: SECRET_KEY from environment variable
# Prefer the production-compatible SECRET_KEY name, but keep the local-dev fallback.
SECRET_KEY = (
    (os.environ.get('SECRET_KEY') or '').strip()
    or (os.environ.get('DJANGO_SECRET_KEY') or '').strip()
    or 'django-insecure-dev-only-change-in-production'
)

# SECURITY: DEBUG from environment (default False for safety)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')
TESTING = 'test' in sys.argv

# SECURITY: ALLOWED_HOSTS from environment
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')

# Kakao API Key
KAKAO_JS_KEY = os.environ.get('KAKAO_JS_KEY', 'default-dev-key')


# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',
    'cloudinary',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'products.apps.ProductsConfig',
    'insights.apps.InsightsConfig',
    'portfolio.apps.PortfolioConfig',
    'autoarticle.apps.AutoarticleConfig',
    'fortune.apps.FortuneConfig',
    'ssambti.apps.SsambtiConfig',
    'signatures.apps.SignaturesConfig',
    'consent.apps.ConsentConfig',
    'docsign.apps.DocsignConfig',
    'artclass.apps.ArtclassConfig',
    'chess.apps.ChessConfig',
    'janggi.apps.JanggiConfig',
    'fairy_games.apps.FairyGamesConfig',
    'reflex_game.apps.ReflexGameConfig',
    'math_games.apps.MathGamesConfig',
    'mancala.apps.MancalaConfig',
    'ppobgi.apps.PpobgiConfig',
    'studentmbti.apps.StudentmbtiConfig',
    'collect.apps.CollectConfig',
    'handoff.apps.HandoffConfig',
    'qrgen.apps.QrgenConfig',
    'hwpxchat.apps.HwpxchatConfig',
    'doccollab.apps.DoccollabConfig',
    'encyclopedia.apps.EncyclopediaConfig',
    'version_manager.apps.VersionManagerConfig',
    'happy_seed.apps.HappySeedConfig',
    'seed_quiz.apps.SeedQuizConfig',
    'noticegen.apps.NoticegenConfig',
    'timetable.apps.TimetableConfig',
    'classcalendar.apps.ClasscalendarConfig',
    'messagebox.apps.MessageboxConfig',
    'schoolcomm.apps.SchoolcommConfig',
    'quickdrop.apps.QuickdropConfig',
    'ocrdesk.apps.OcrdeskConfig',
    'textbooks.apps.TextbooksConfig',
    'textbook_ai.apps.TextbookAiConfig',
    'edu_materials.apps.EduMaterialsConfig',
    'edu_materials_next.apps.EduMaterialsNextConfig',
    'channels',
    'django_htmx',
    'django.contrib.humanize',
    'reservations.apps.ReservationsConfig',
    'parentcomm.apps.ParentcommConfig',
    'docviewer.apps.DocviewerConfig',
    'pdfhub.apps.PdfhubConfig',
    'slidesmith.apps.SlidesmithConfig',
    'blockclass.apps.BlockclassConfig',
    'infoboard.apps.InfoboardConfig',
    'teacher_law.apps.TeacherLawConfig',
    'schoolprograms.apps.SchoolprogramsConfig',

    # Auth & Allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.naver',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Allauth middleware
    'allauth.account.middleware.AccountMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    # Custom Middleware
    'core.middleware.MaintenanceModeMiddleware',  # 점검 모드 (제일 위쪽 처리가 좋음)
    'core.middleware.PolicyConsentMiddleware',  # 소셜 로그인 사용자 약관 동의 필수
    'core.middleware.OnboardingMiddleware',  # 모든 사용자 정보 입력 필수
    'core.middleware.BlockKnownProbePathsMiddleware',
    'core.middleware.SeoMetaFallbackMiddleware',
    'core.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                # Custom Context Processors
                'core.context_processors.visitor_counts',
                'core.context_processors.toast_messages',
                'core.context_processors.site_config',
                'core.context_processors.seo_meta',
                'core.context_processors.search_products',
                'core.context_processors.active_classroom',
                'core.context_processors.home_agent_limit_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL', '').strip()
if TESTING or not REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL 지원 (DATABASE_URL 환경 변수 사용 시)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # 프로덕션 환경: PostgreSQL 사용
    try:
        import dj_database_url
        DATABASE_URL = normalize_database_url(DATABASE_URL)
        default_db = dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,  # 연결 풀링: 10분
            conn_health_checks=True,  # 연결 상태 체크
        )
        default_db = apply_database_network_overrides(default_db, DATABASE_URL)
        DATABASES = {
            'default': default_db
        }
        hostaddr = (default_db.get('OPTIONS') or {}).get('hostaddr')
        if hostaddr:
            print(f"[DATABASE] Using PostgreSQL with IPv4 hostaddr={hostaddr}")
        else:
            print(f"[DATABASE] Using PostgreSQL with conn_max_age=600")
    except ImportError:
        print("[WARNING] dj-database-url not installed. Falling back to SQLite.")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # 로컬 개발 환경: SQLite 사용
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("[DATABASE] Using SQLite (development)")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Settings
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_SIGNUP_FORM_CLASS = 'core.signup_forms.CustomSignupForm'
ACCOUNT_ADAPTER = 'core.account_adapter.EduititAccountAdapter'
ACCOUNT_SESSION_REMEMBER = False  # 기본적으로 자동 로그인 해제 (보안을 위해)
ACCOUNT_RATE_LIMITS = {
    'login_failed': '10/m/ip,5/300s/key',
}
SESSION_COOKIE_AGE = 21600  # 내부 세션 정책값
SESSION_SAVE_EVERY_REQUEST = False  # 매 요청마다 DB write 방지 (성능 개선)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 브라우저 닫으면 로그아웃
SOCIALACCOUNT_AUTO_SIGNUP = False  # ✅ 소셜 로그인 후 추가 정보(별명) 입력 화면 표시
SOCIALACCOUNT_LOGIN_ON_GET = True # ✅ 중간 페이지 없이 바로 소셜 로그인창으로 이동
SOCIALACCOUNT_ADAPTER = 'core.socialaccount_adapter.EduititSocialAccountAdapter'

# HTTPS 설정 (Railway 프록시 뒤에서 HTTPS 강제)
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# SSO Settings
SSO_JWT_SECRET = os.environ.get('SSO_JWT_SECRET', SECRET_KEY)
SCHOOLIT_URL = os.environ.get('SCHOOLIT_URL', 'http://localhost:3000') # schoolit 주소

# Allauth Provider Settings
# 환경변수: NAVER_CLIENT_ID, NAVER_CLIENT_SECRET, KAKAO_CLIENT_ID, KAKAO_CLIENT_SECRET
SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id': os.environ.get('KAKAO_CLIENT_ID', ''),
            'secret': os.environ.get('KAKAO_CLIENT_SECRET', ''),  # KAKAO_SECRET → KAKAO_CLIENT_SECRET
            'key': ''
        }
    },
    'naver': {
        'APP': {
            'client_id': os.environ.get('NAVER_CLIENT_ID', ''),
            'secret': os.environ.get('NAVER_CLIENT_SECRET', ''),  # NAVER_SECRET → NAVER_CLIENT_SECRET
            'key': ''
        }
    }
}

# 키 누락 시 로그 출력 (DEBUG 레벨로 변경하여 덜 시끄럽게)
import logging
logger = logging.getLogger(__name__)

if not SOCIALACCOUNT_PROVIDERS['naver']['APP']['client_id']:
    logger.debug("NAVER_CLIENT_ID is not set in environment variables!")
if not SOCIALACCOUNT_PROVIDERS['naver']['APP']['secret']:
    logger.debug("NAVER_CLIENT_SECRET is not set in environment variables!")
if not SOCIALACCOUNT_PROVIDERS['kakao']['APP']['client_id']:
    logger.debug("KAKAO_CLIENT_ID is not set in environment variables!")
if not SOCIALACCOUNT_PROVIDERS['kakao']['APP']['secret']:
    logger.debug("KAKAO_CLIENT_SECRET is not set in environment variables!")


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
if TESTING:
    MEDIA_ROOT = BASE_DIR / "test_media"

# Cloudinary 설정
print("=" * 80)
print("[CLOUDINARY] Environment variable check")
print("=" * 80)

# 환경 변수 확인 (민감 정보 마스킹)
cloudinary_url = os.environ.get('CLOUDINARY_URL', '')
cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
api_key = os.environ.get('CLOUDINARY_API_KEY', '')
api_secret = os.environ.get('CLOUDINARY_API_SECRET', '')

print(f"CLOUDINARY_URL: {'SET' if cloudinary_url else '[X] NOT SET'}")
print(f"CLOUDINARY_CLOUD_NAME: {cloud_name if cloud_name else '[X] NOT SET'}")
print(f"CLOUDINARY_API_KEY: {api_key[:4] + '...' if api_key else '[X] NOT SET'}")
print(f"CLOUDINARY_API_SECRET: {'SET' if api_secret else '[X] NOT SET'}")

CLOUDINARY_STORAGE = {}

if cloudinary_url:
    print("[CLOUDINARY] Parsing CLOUDINARY_URL...")
    try:
        parsed = urlparse(cloudinary_url)
        # 1. URL 파싱 결과 우선 저장
        parsed_storage = {
            'CLOUD_NAME': parsed.hostname or '',
            'API_KEY': parsed.username or '',
            'API_SECRET': parsed.password or '',
            'SECURE': True,
        }
        print(f"[OK] Parsing success - CLOUD_NAME: {parsed.hostname}")
        
        # 2. 개별 환경 변수가 있다면 우선 적용 (Override)
        if cloud_name: parsed_storage['CLOUD_NAME'] = cloud_name
        if api_key: parsed_storage['API_KEY'] = api_key
        if api_secret: parsed_storage['API_SECRET'] = api_secret
        
        CLOUDINARY_STORAGE = parsed_storage
        
    except Exception as e:
        print(f"[X] CLOUDINARY_URL parsing failed: {e}")
        CLOUDINARY_STORAGE = {
            'CLOUD_NAME': cloud_name,
            'API_KEY': api_key,
            'API_SECRET': api_secret,
            'SECURE': True,
        }
else:
    print("[CLOUDINARY] Using individual environment variables")
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': cloud_name,
        'API_KEY': api_key,
        'API_SECRET': api_secret,
        'SECURE': True,
    }

# Cloudinary 라이브러리 직접 초기화
if CLOUDINARY_STORAGE.get('CLOUD_NAME') and CLOUDINARY_STORAGE.get('API_KEY'):
    try:
        import cloudinary
        cloudinary.config(
            cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
            api_key=CLOUDINARY_STORAGE['API_KEY'],
            api_secret=CLOUDINARY_STORAGE['API_SECRET'],
            secure=True
        )
        print(f"[OK] Cloudinary library initialized: {CLOUDINARY_STORAGE['CLOUD_NAME']}")
    except Exception as e:
        print(f"[X] Cloudinary library initialization failed: {e}")

# Cloudinary 활성화 여부
USE_CLOUDINARY = bool(CLOUDINARY_STORAGE.get('CLOUD_NAME') and CLOUDINARY_STORAGE.get('API_KEY'))
print(f"[CLOUDINARY] USE_CLOUDINARY = {USE_CLOUDINARY}")

if USE_CLOUDINARY:
    # Django 4.2+ recommended storages configuration
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "cloudinary_storage.storage.StaticHashedCloudinaryStorage",
        },
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'
    print("[OK] STORAGES and legacy storage constants configured for Cloudinary")
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
    print("[INFO] Cloudinary disabled - using local file system")

print("=" * 80)

LOGIN_REDIRECT_URL = 'select_role'
LOGOUT_REDIRECT_URL = 'home'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'request_id': {
            '()': 'core.logging_filters.RequestIDFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} [{request_id}] {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'filters': ['request_id'],
        },
    },
    'loggers': {
        'core.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.context_processors': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.auth_security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
# Maintenance Mode
# 배포 환경 변수에 MAINTENANCE_MODE=True 로 설정하면 작동합니다. 기본값은 False입니다.
MAINTENANCE_MODE = os.getenv('MAINTENANCE_MODE', 'False') == 'True'
AUTOARTICLE_EXPORT_LAYOUT = os.getenv('AUTOARTICLE_EXPORT_LAYOUT', 'v1')
# Home layout rollout: set HOME_LAYOUT_VERSION to v1, v2, v4, v5, or v6 to lock a version.
# If unset, legacy HOME_V2_ENABLED fallback still decides between v1 and v2 only.
HOME_LAYOUT_VERSION = os.environ.get('HOME_LAYOUT_VERSION', '').strip().lower()
# Legacy fallback flag for v1/v2 only. Keep until v1/v2 paths and rollback rules are retired.
HOME_V2_ENABLED = os.environ.get('HOME_V2_ENABLED', 'True').lower() == 'true'
# Mobile home V4 rollout: keep the current hamburger menu by default.
# Set HOME_V4_MOBILE_CALENDAR_FIRST_ENABLED=True to switch mobile V4 to calendar-first quick tools.
HOME_V4_MOBILE_CALENDAR_FIRST_ENABLED = os.environ.get(
    'HOME_V4_MOBILE_CALENDAR_FIRST_ENABLED',
    'False',
).lower() == 'true'
HOME_TEACHER_BUDDY_ENABLED = os.environ.get(
    'HOME_TEACHER_BUDDY_ENABLED',
    'False',
).lower() == 'true'
ALLOW_TABLET_ACCESS = os.environ.get('ALLOW_TABLET_ACCESS', 'True').lower() in ('true', '1', 'yes')
GLOBAL_SEARCH_ENABLED = os.environ.get('GLOBAL_SEARCH_ENABLED', 'True').lower() in ('true', '1', 'yes')


def _rollout_env(name, default="", aliases=None):
    value = os.environ.get(name)
    if value is None and aliases:
        for alias in aliases:
            alias_value = os.environ.get(alias)
            if alias_value is not None:
                value = alias_value
                break
    if value is None:
        return default
    return value


def _rollout_env_bool(name, default='False', aliases=None):
    return str(_rollout_env(name, default=default, aliases=aliases)).strip().lower() in ('true', '1', 'yes')


def _rollout_env_csv(name, aliases=None):
    raw = _rollout_env(name, default='', aliases=aliases)
    return [item.strip() for item in str(raw).split(',') if item.strip()]


FEATURE_MESSAGE_CAPTURE_ENABLED = _rollout_env_bool(
    'FEATURE_MESSAGE_CAPTURE_ENABLED',
    default='False',
    aliases=('feature_message_capture_enabled',),
)
FEATURE_MESSAGE_CAPTURE_ALLOWLIST_USERNAMES = _rollout_env_csv(
    'FEATURE_MESSAGE_CAPTURE_ALLOWLIST_USERNAMES',
    aliases=('feature_message_capture_allowlist_usernames',),
)
FEATURE_MESSAGE_CAPTURE_ALLOWLIST_EMAILS = _rollout_env_csv(
    'FEATURE_MESSAGE_CAPTURE_ALLOWLIST_EMAILS',
    aliases=('feature_message_capture_allowlist_emails',),
)
FEATURE_MESSAGE_CAPTURE_ALLOWLIST_USER_IDS = _rollout_env_csv(
    'FEATURE_MESSAGE_CAPTURE_ALLOWLIST_USER_IDS',
    aliases=('feature_message_capture_allowlist_user_ids',),
)
FEATURE_MESSAGE_CAPTURE_ITEM_TYPES = _rollout_env_bool(
    'FEATURE_MESSAGE_CAPTURE_ITEM_TYPES',
    default='False',
    aliases=('feature_message_capture_item_types',),
)
FEATURE_MESSAGE_CAPTURE_CLASSIFIER_SHADOW = _rollout_env_bool(
    'FEATURE_MESSAGE_CAPTURE_CLASSIFIER_SHADOW',
    default='False',
    aliases=('feature_message_capture_classifier_shadow',),
)
FEATURE_MESSAGE_CAPTURE_CLASSIFIER_ASSIST = _rollout_env_bool(
    'FEATURE_MESSAGE_CAPTURE_CLASSIFIER_ASSIST',
    default='False',
    aliases=('feature_message_capture_classifier_assist',),
)
FEATURE_MESSAGE_CAPTURE_CLASSIFIER_ASSIST_THRESHOLD = float(
    _rollout_env('FEATURE_MESSAGE_CAPTURE_CLASSIFIER_ASSIST_THRESHOLD', default='0.80', aliases=('feature_message_capture_classifier_assist_threshold',))
)
ONBOARDING_EXEMPT_PATH_PREFIXES = []
if TESTING:
    ONBOARDING_EXEMPT_PATH_PREFIXES.append('/autoarticle/')
DUTYTICKER_STUDENT_GAMES_MAX_AGE_SECONDS = int(os.environ.get('DUTYTICKER_STUDENT_GAMES_MAX_AGE_SECONDS', '28800'))
DUTYTICKER_STUDENT_GAMES_LAUNCH_TICKET_TTL_SECONDS = int(
    os.environ.get('DUTYTICKER_STUDENT_GAMES_LAUNCH_TICKET_TTL_SECONDS', '900')
)
SEED_QUIZ_BATCH_ENABLED = os.environ.get('SEED_QUIZ_BATCH_ENABLED', 'False').lower() in ('true', '1', 'yes')
SEED_QUIZ_ALLOW_RAG = os.environ.get('SEED_QUIZ_ALLOW_RAG', 'False').lower() in ('true', '1', 'yes')
SEED_QUIZ_CSV_MAX_FILE_BYTES = int(os.environ.get('SEED_QUIZ_CSV_MAX_FILE_BYTES', str(2 * 1024 * 1024)))
SEED_QUIZ_CSV_MAX_ROWS = int(os.environ.get('SEED_QUIZ_CSV_MAX_ROWS', '1200'))
SEED_QUIZ_CSV_MAX_SETS = int(os.environ.get('SEED_QUIZ_CSV_MAX_SETS', '400'))
NEWS_INGEST_MAX_PENDING = int(os.environ.get('NEWS_INGEST_MAX_PENDING', '200'))
NEWS_INGEST_ALLOWED_HOSTS = [
    host.strip().lower()
    for host in os.environ.get('NEWS_INGEST_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
LAW_API_OC = os.environ.get('LAW_API_OC', '').strip()
TEACHER_LAW_ENABLED = os.environ.get('TEACHER_LAW_ENABLED', 'False').lower() in ('true', '1', 'yes')
TEACHER_LAW_DAILY_LIMIT_PER_USER = int(os.environ.get('TEACHER_LAW_DAILY_LIMIT_PER_USER', '15'))
TEACHER_LAW_TOTAL_TIMEOUT_SECONDS = int(os.environ.get('TEACHER_LAW_TOTAL_TIMEOUT_SECONDS', '20'))
TEACHER_LAW_SEARCH_TIMEOUT_SECONDS = int(os.environ.get('TEACHER_LAW_SEARCH_TIMEOUT_SECONDS', '4'))
TEACHER_LAW_DETAIL_TIMEOUT_SECONDS = int(os.environ.get('TEACHER_LAW_DETAIL_TIMEOUT_SECONDS', '4'))
TEACHER_LAW_LLM_TIMEOUT_SECONDS = int(os.environ.get('TEACHER_LAW_LLM_TIMEOUT_SECONDS', '12'))
TEACHER_LAW_SEARCH_RESULT_LIMIT = int(os.environ.get('TEACHER_LAW_SEARCH_RESULT_LIMIT', '5'))
TEACHER_LAW_DETAIL_FETCH_LIMIT = int(os.environ.get('TEACHER_LAW_DETAIL_FETCH_LIMIT', '3'))
TEACHER_LAW_FAQ_CACHE_TTL_SECONDS = int(os.environ.get('TEACHER_LAW_FAQ_CACHE_TTL_SECONDS', '43200'))

# =============================================================================
# SENTRY ERROR TRACKING (production only)
# =============================================================================
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
print(f"[SENTRY] DSN={'SET' if SENTRY_DSN else 'NOT SET'}, DEBUG={DEBUG}")
if SENTRY_DSN and not DEBUG:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.2,
            profiles_sample_rate=0.1,
            send_default_pii=True,
        )
        print("[SENTRY] Initialized successfully!")
    except ImportError:
        print("[SENTRY] ERROR: sentry-sdk package not installed!")
    except Exception as e:
        print(f"[SENTRY] ERROR: Init failed - {e}")
else:
    print(f"[SENTRY] SKIPPED (DSN={'SET' if SENTRY_DSN else 'EMPTY'}, DEBUG={DEBUG})")
