# Generated by Django 6.0.1 on 2026-02-18 21:00

import consent.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("signatures", "0009_trainingsession_print_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="SignatureDocument",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(max_length=200)),
                        ("original_file", models.FileField(upload_to="signatures/consent/originals/%Y/%m/%d")),
                        ("file_type", models.CharField(choices=[("pdf", "PDF"), ("image", "Image")], max_length=10)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="consent_documents",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "db_table": "signatures_signaturedocument",
                    },
                ),
                migrations.CreateModel(
                    name="SignatureRequest",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                        ("title", models.CharField(max_length=200)),
                        ("message", models.TextField(blank=True)),
                        ("legal_notice", models.TextField(blank=True)),
                        ("consent_text_version", models.CharField(default="v1", max_length=32)),
                        (
                            "status",
                            models.CharField(
                                choices=[("draft", "Draft"), ("sent", "Sent"), ("completed", "Completed")],
                                default="draft",
                                max_length=20,
                            ),
                        ),
                        ("merged_pdf", models.FileField(blank=True, null=True, upload_to="signatures/consent/merged/%Y/%m/%d")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("sent_at", models.DateTimeField(blank=True, null=True)),
                        ("preview_checked_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "created_by",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="consent_requests",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "document",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="requests",
                                to="consent.signaturedocument",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "db_table": "signatures_signaturerequest",
                    },
                ),
                migrations.CreateModel(
                    name="SignaturePosition",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("page", models.PositiveIntegerField(default=1)),
                        ("x", models.FloatField(help_text="Points from left")),
                        ("y", models.FloatField(help_text="Points from bottom")),
                        ("width", models.FloatField(default=180)),
                        ("height", models.FloatField(default=70)),
                        ("x_ratio", models.FloatField(blank=True, null=True)),
                        ("y_ratio", models.FloatField(blank=True, null=True)),
                        ("w_ratio", models.FloatField(blank=True, null=True)),
                        ("h_ratio", models.FloatField(blank=True, null=True)),
                        (
                            "request",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="positions",
                                to="consent.signaturerequest",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["page", "id"],
                        "db_table": "signatures_signatureposition",
                    },
                ),
                migrations.CreateModel(
                    name="SignatureRecipient",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("student_name", models.CharField(max_length=100)),
                        ("parent_name", models.CharField(max_length=100)),
                        ("phone_number", models.CharField(max_length=20)),
                        ("access_token", models.CharField(default=consent.models._generate_access_token, max_length=64, unique=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("pending", "Pending"),
                                    ("verified", "Verified"),
                                    ("signed", "Signed"),
                                    ("declined", "Declined"),
                                ],
                                default="pending",
                                max_length=20,
                            ),
                        ),
                        ("decision", models.CharField(blank=True, choices=[("agree", "Agree"), ("disagree", "Disagree")], max_length=20)),
                        ("decline_reason", models.TextField(blank=True)),
                        ("signature_data", models.TextField(blank=True)),
                        ("signed_pdf", models.FileField(blank=True, null=True, upload_to="signatures/consent/signed/%Y/%m/%d")),
                        ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                        ("user_agent", models.TextField(blank=True)),
                        ("signed_at", models.DateTimeField(blank=True, null=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "request",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="recipients",
                                to="consent.signaturerequest",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["student_name", "id"],
                        "db_table": "signatures_signaturerecipient",
                        "unique_together": {("request", "student_name", "parent_name", "phone_number")},
                    },
                ),
                migrations.CreateModel(
                    name="ConsentAuditLog",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        (
                            "event_type",
                            models.CharField(
                                choices=[
                                    ("verify_success", "Verify Success"),
                                    ("verify_fail", "Verify Fail"),
                                    ("sign_submitted", "Sign Submitted"),
                                    ("link_created", "Link Created"),
                                    ("request_sent", "Request Sent"),
                                ],
                                max_length=40,
                            ),
                        ),
                        ("event_meta", models.JSONField(blank=True, default=dict)),
                        ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                        ("user_agent", models.TextField(blank=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "recipient",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="audit_logs",
                                to="consent.signaturerecipient",
                            ),
                        ),
                        (
                            "request",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="audit_logs",
                                to="consent.signaturerequest",
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-created_at"],
                        "db_table": "signatures_consentauditlog",
                    },
                ),
            ],
        )
    ]
