# Generated by Codex on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signaturerequest",
            name="link_expire_days",
            field=models.PositiveSmallIntegerField(choices=[(7, "7일"), (14, "14일"), (30, "30일")], default=14),
        ),
    ]
