# Generated by Codex on 2026-02-19

import consent.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0002_signaturerequest_link_expire_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signaturedocument",
            name="original_file",
            field=models.FileField(
                storage=consent.models.get_raw_storage,
                upload_to="signatures/consent/originals/%Y/%m/%d",
            ),
        ),
        migrations.AlterField(
            model_name="signaturerecipient",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=consent.models.get_raw_storage,
                upload_to="signatures/consent/signed/%Y/%m/%d",
            ),
        ),
        migrations.AlterField(
            model_name="signaturerequest",
            name="merged_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                storage=consent.models.get_raw_storage,
                upload_to="signatures/consent/merged/%Y/%m/%d",
            ),
        ),
    ]
