# Generated by Django 6.0.1 on 2026-02-23 15:27

import consent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0005_signaturerequest_document_evidence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturedocument',
            name='original_file',
            field=models.FileField(max_length=500, storage=consent.models.get_document_storage, upload_to='signatures/consent/originals/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='signaturerecipient',
            name='decision',
            field=models.CharField(blank=True, choices=[('agree', '동의'), ('disagree', '비동의')], max_length=20),
        ),
        migrations.AlterField(
            model_name='signaturerecipient',
            name='signed_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, storage=consent.models.get_raw_storage, upload_to='signatures/consent/signed/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='signaturerecipient',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('verified', '본인확인 완료'), ('signed', '동의 제출'), ('declined', '비동의 제출')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='signaturerequest',
            name='merged_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, storage=consent.models.get_raw_storage, upload_to='signatures/consent/merged/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='signaturerequest',
            name='status',
            field=models.CharField(choices=[('draft', '작성중'), ('sent', '발송됨'), ('completed', '완료')], default='draft', max_length=20),
        ),
    ]
