# Generated by Django 6.0.1 on 2026-02-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0006_alter_signaturedocument_original_file_and_more'),
        ('handoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='shared_roster_group',
            field=models.ForeignKey(blank=True, help_text='배부 체크 공유 명단과 연동 (선택)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_requests', to='handoff.handoffrostergroup'),
        ),
    ]
