# Generated by Django 6.0.1 on 2026-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0007_signaturerequest_shared_roster_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerecipient',
            name='identity_assurance',
            field=models.CharField(choices=[('token_only', '링크 기반 제출'), ('phone_last4', '전화번호 끝 4자리 확인')], default='token_only', max_length=20),
        ),
        migrations.AddField(
            model_name='signaturerecipient',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signaturerecipient',
            name='verified_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signaturerecipient',
            name='verified_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consentauditlog',
            name='event_type',
            field=models.CharField(choices=[('verify_success', 'Verify Success'), ('verify_fail', 'Verify Fail'), ('sign_submitted', 'Sign Submitted'), ('link_created', 'Link Created'), ('request_sent', 'Request Sent'), ('document_viewed', 'Document Viewed')], max_length=40),
        ),
    ]
