# Generated by Django 6.0.1 on 2026-03-16 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0012_alter_consentauditlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signaturerequest',
            name='audience_type',
            field=models.CharField(choices=[('guardian', '학부모 확인형'), ('general', '일반 서명형')], default='guardian', max_length=20),
        ),
        migrations.CreateModel(
            name='ConsentRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience_type', models.CharField(choices=[('guardian', '학부모 확인형'), ('general', '일반 서명형')], default='guardian', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_rosters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signatures_consentroster',
                'ordering': ['-is_favorite', 'name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='consent.consentroster'),
        ),
        migrations.CreateModel(
            name='ConsentRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='consent.consentroster')),
            ],
            options={
                'db_table': 'signatures_consentrosterentry',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='consentroster',
            constraint=models.UniqueConstraint(fields=('owner', 'audience_type', 'name'), name='consent_roster_owner_audience_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='consentrosterentry',
            constraint=models.UniqueConstraint(fields=('roster', 'student_name', 'parent_name', 'phone_number'), name='consent_roster_entry_unique'),
        ),
    ]
