# Generated by Django 6.0.3 on 2026-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0013_signaturerequest_audience_type_consentroster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureposition',
            name='check_rule',
            field=models.CharField(choices=[('always', '항상'), ('agree', '동의일 때'), ('disagree', '비동의일 때')], default='agree', max_length=20),
        ),
        migrations.AddField(
            model_name='signatureposition',
            name='mark_type',
            field=models.CharField(choices=[('signature', '사인'), ('checkmark', '체크'), ('name', '이름')], default='signature', max_length=20),
        ),
        migrations.AddField(
            model_name='signatureposition',
            name='text_source',
            field=models.CharField(choices=[('student_name', '학생 이름'), ('signer_name', '서명자 이름')], default='signer_name', max_length=20),
        ),
    ]
