# Generated by Django 6.0.1 on 2026-01-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': '협업 제안 및 문의', 'verbose_name_plural': '협업 제안 및 문의'},
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='상세 내용'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='organization',
            field=models.CharField(max_length=200, verbose_name='소속 기관/단체'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='requested_date',
            field=models.DateField(blank=True, null=True, verbose_name='희망 일시 (선택)'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='제안 및 문의 주제'),
        ),
    ]
