# Generated by Django 6.0.1 on 2026-02-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_inquiry_options_alter_inquiry_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='portfolio/achievements/', verbose_name='상장/증빙 이미지'),
        ),
        migrations.AlterField(
            model_name='lectureprogram',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='portfolio/thumbnails/', verbose_name='썸네일'),
        ),
    ]
