# Generated by Django 6.0.1 on 2026-04-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_achievement_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(max_length=500, upload_to="portfolio/achievements/", verbose_name="추가 사진")),
                ("caption", models.CharField(blank=True, max_length=200, verbose_name="사진 설명")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="portfolio.achievement",
                        verbose_name="연결 실적",
                    ),
                ),
            ],
            options={
                "verbose_name": "실적 사진",
                "verbose_name_plural": "실적 사진",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
