# Generated by Django 6.0.1 on 2026-02-22 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_slug', models.CharField(max_length=120, verbose_name='학교 슬러그')),
                ('school_name', models.CharField(blank=True, max_length=120, verbose_name='학교명')),
                ('sync_mode', models.CharField(choices=[('direct', '바로반영'), ('preview_manual', '미리보기 수동반영')], max_length=30, verbose_name='반영 방식')),
                ('sync_options_text', models.CharField(blank=True, max_length=120, verbose_name='반영 대상 옵션')),
                ('overwrite_existing', models.BooleanField(default=False, verbose_name='기존 고정시간표 덮어쓰기')),
                ('status', models.CharField(choices=[('success', '성공'), ('partial', '부분반영'), ('skipped', '건너뜀'), ('failed', '실패')], default='success', max_length=20, verbose_name='결과 상태')),
                ('applied_count', models.PositiveIntegerField(default=0, verbose_name='새로 반영')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='이름 갱신')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='건너뜀')),
                ('conflict_count', models.PositiveIntegerField(default=0, verbose_name='기존값 충돌')),
                ('room_created_count', models.PositiveIntegerField(default=0, verbose_name='신규 특별실')),
                ('summary_text', models.TextField(blank=True, verbose_name='요약 메모')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='추가 기록')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='실행 시각')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='실행 사용자')),
            ],
            options={
                'verbose_name': '시간표 예약 반영 로그',
                'verbose_name_plural': '시간표 예약 반영 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
