# Generated by Django 6.0.3 on 2026-04-10 12:43

import django.db.models.deletion
import timetable.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_owner_key'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('class_no', models.PositiveIntegerField()),
                ('homeroom_name', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_classrooms', to='reservations.school')),
            ],
            options={
                'ordering': ['school__name', 'school_year', 'grade', 'class_no'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sheet_data', models.JSONField(blank=True, default=list)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('teacher_type', models.CharField(choices=[('homeroom', '담임'), ('specialist', '전담'), ('instructor', '강사')], max_length=20)),
                ('target_weekly_hours', models.PositiveIntegerField(default=0)),
                ('subjects_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_teachers', to='reservations.school')),
            ],
            options={
                'ordering': ['school__name', 'teacher_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('class', '반'), ('teacher', '교사')], max_length=20)),
                ('token', models.CharField(default=timetable.models._default_share_token, max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_share_links', to='timetable.timetableclassroom')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='timetable.timetablesnapshot')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_share_links', to='timetable.timetableteacher')),
            ],
            options={
                'ordering': ['audience_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.PositiveIntegerField()),
                ('term', models.CharField(max_length=40)),
                ('grade', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('days_json', models.JSONField(blank=True, default=list)),
                ('period_labels_json', models.JSONField(blank=True, default=list)),
                ('sheet_data', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_workspaces', to=settings.AUTH_USER_MODEL)),
                ('published_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_workspaces', to='timetable.timetablesnapshot')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_workspaces', to='reservations.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_timetable_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school__name', 'school_year', 'term', 'grade', 'id'],
            },
        ),
        migrations.AddField(
            model_name='timetablesnapshot',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='timetable.timetableworkspace'),
        ),
        migrations.CreateModel(
            name='TimetableSlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.CharField(max_length=20)),
                ('period_no', models.PositiveIntegerField()),
                ('subject_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('manual', '수동'), ('meeting', '회의'), ('import', '가져오기')], default='manual', max_length=20)),
                ('display_text', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignments', to='timetable.timetableclassroom')),
                ('special_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_assignments', to='reservations.specialroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_assignments', to='timetable.timetableteacher')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['workspace_id', 'classroom__class_no', 'day_key', 'period_no'],
            },
        ),
        migrations.CreateModel(
            name='TimetableRoomPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_per_slot', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('special_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_policies', to='reservations.specialroom')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_policies', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['workspace_id', 'special_room__name'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePublishedRecurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.CharField(max_length=20)),
                ('period_no', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurring_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_publications', to='reservations.recurringschedule')),
                ('special_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_published_recurrings', to='reservations.specialroom')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_recurrings', to='timetable.timetablesnapshot')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_recurrings', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['workspace_id', 'day_key', 'period_no', 'special_room__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableclassroom',
            constraint=models.UniqueConstraint(fields=('school', 'school_year', 'grade', 'class_no'), name='unique_timetable_classroom_per_year'),
        ),
        migrations.AddConstraint(
            model_name='timetableteacher',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_timetable_teacher_per_school'),
        ),
        migrations.AddConstraint(
            model_name='timetableworkspace',
            constraint=models.UniqueConstraint(fields=('school', 'school_year', 'term', 'grade'), name='unique_timetable_workspace_scope'),
        ),
        migrations.AddConstraint(
            model_name='timetableslotassignment',
            constraint=models.UniqueConstraint(fields=('workspace', 'classroom', 'day_key', 'period_no'), name='unique_timetable_slot_assignment'),
        ),
        migrations.AddConstraint(
            model_name='timetableroompolicy',
            constraint=models.UniqueConstraint(fields=('workspace', 'special_room'), name='unique_timetable_room_policy'),
        ),
        migrations.AddConstraint(
            model_name='timetablepublishedrecurring',
            constraint=models.UniqueConstraint(fields=('workspace', 'special_room', 'day_key', 'period_no'), name='unique_timetable_published_recurring_slot'),
        ),
    ]
