# Generated by Django 6.0.3 on 2026-04-10 13:12

import django.db.models.deletion
import timetable.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableclassroom_timetablesnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSharePortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=timetable.models._default_share_token, max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_portal', to='timetable.timetablesnapshot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
