# Generated by Django 6.0.3 on 2026-04-10 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_owner_key'),
        ('timetable', '0003_timetableshareportal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesnapshot',
            name='events_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TimetableSharedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.PositiveIntegerField()),
                ('term', models.CharField(max_length=40)),
                ('scope_type', models.CharField(choices=[('school', '학교 전체'), ('grade', '학년 공통')], max_length=20)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=120)),
                ('day_key', models.CharField(max_length=20)),
                ('period_start', models.PositiveIntegerField()),
                ('period_end', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_shared_events', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_shared_events', to='reservations.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_timetable_shared_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school__name', 'school_year', 'term', 'day_key', 'period_start', 'scope_type', 'grade', 'id'],
            },
        ),
    ]
