# Generated by Django 6.0.3 on 2026-04-10 15:13

import django.db.models.deletion
import timetable.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_owner_key'),
        ('timetable', '0004_timetablesnapshot_events_json_timetablesharedevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesnapshot',
            name='date_overrides_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='timetableworkspace',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableworkspace',
            name='term_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TimetableSchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_stage', models.CharField(choices=[('elementary', '초등'), ('middle', '중등'), ('high', '고등'), ('custom', '직접 입력')], default='elementary', max_length=20)),
                ('grade_start', models.PositiveIntegerField(default=1)),
                ('grade_end', models.PositiveIntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_profile', to='reservations.school')),
            ],
            options={
                'ordering': ['school__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableClassEditLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=timetable.models._default_share_token, max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_links', to='timetable.timetableclassroom')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_timetable_edit_links', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_edit_links', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['workspace_id', 'classroom__class_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'classroom'), name='unique_timetable_class_edit_link')],
            },
        ),
        migrations.CreateModel(
            name='TimetableClassInputStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '아직 안 함'), ('editing', '입력 중'), ('submitted', '입력 완료'), ('reviewed', '관리자 검토 완료')], default='not_started', max_length=20)),
                ('editor_name', models.CharField(blank=True, max_length=80)),
                ('last_saved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_statuses', to='timetable.timetableclassroom')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_input_statuses', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['workspace_id', 'classroom__class_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'classroom'), name='unique_timetable_class_input_status')],
            },
        ),
        migrations.CreateModel(
            name='TimetableDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period_no', models.PositiveIntegerField()),
                ('subject_name', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('teacher_link', '반별 입력'), ('meeting', '회의'), ('manual', '관리자 수동')], default='teacher_link', max_length=20)),
                ('display_text', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_date_overrides', to='timetable.timetableclassroom')),
                ('special_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_date_overrides', to='reservations.specialroom')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_date_overrides', to='timetable.timetableteacher')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['workspace_id', 'date', 'classroom__class_no', 'period_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'classroom', 'date', 'period_no'), name='unique_timetable_date_override')],
            },
        ),
    ]
