# Generated by Django 6.0.3 on 2026-04-11 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetablesnapshot_date_overrides_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableclassinputstatus',
            name='status',
            field=models.CharField(choices=[('not_started', '아직 안 함'), ('editing', '입력 중'), ('submitted', '입력 완료'), ('reviewed', '관리자 검토 완료'), ('published', '확정 반영')], default='not_started', max_length=20),
        ),
        migrations.CreateModel(
            name='TimetableAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('actor_type', models.CharField(choices=[('admin', '관리 교사'), ('teacher_link', '반별 입력 링크'), ('system', '시스템')], default='system', max_length=20)),
                ('event_type', models.CharField(max_length=40)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_audit_logs', to='timetable.timetableclassroom')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='timetable.timetableworkspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
