# Generated by Django 6.0.1 on 2026-04-01 01:11

import django.db.models.deletion
import schoolcomm.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredAssetBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum_sha256', models.CharField(max_length=64, unique=True)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('file', models.FileField(max_length=255, upload_to=schoolcomm.models.blob_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '저장 파일 원본',
                'verbose_name_plural': '저장 파일 원본',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('room_kind', models.CharField(choices=[('notice', '공지'), ('shared', '자료공유'), ('dm', '1:1 대화'), ('group_dm', '그룹 대화')], max_length=20)),
                ('is_system_room', models.BooleanField(default=False)),
                ('participants_signature', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '커뮤니티 방',
                'verbose_name_plural': '커뮤니티 방',
                'ordering': ['-last_message_at', 'name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', '소유자'), ('admin', '관리자'), ('member', '멤버')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('active', '활성'), ('inactive', '비활성')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_school_memberships', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_school_membership_invites', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학교 멤버십',
                'verbose_name_plural': '학교 멤버십',
                'ordering': ['workspace__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('sender_membership_snapshot', models.CharField(blank=True, default='', max_length=40)),
                ('body', models.TextField(blank=True, default='')),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('last_replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='schoolcomm.roommessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schoolcomm.communityroom')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_messages', to=settings.AUTH_USER_MODEL)),
                ('sender_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_school_messages', to='schoolcomm.schoolmembership')),
            ],
            options={
                'verbose_name': '방 메시지',
                'verbose_name_plural': '방 메시지',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('status', models.CharField(choices=[('active', '운영 중'), ('archived', '보관')], default='active', max_length=20)),
                ('academic_year', models.CharField(blank=True, default='', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_from_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_workspaces', to='schoolcomm.schoolworkspace')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학교 워크스페이스',
                'verbose_name_plural': '학교 워크스페이스',
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schoolcomm.schoolworkspace'),
        ),
        migrations.AddField(
            model_name='communityroom',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schoolcomm.schoolworkspace'),
        ),
        migrations.CreateModel(
            name='SharedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_name_snapshot', models.CharField(blank=True, default='', max_length=120)),
                ('original_name', models.CharField(max_length=255)),
                ('file_extension', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_school_assets', to=settings.AUTH_USER_MODEL)),
                ('blob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_assets', to='schoolcomm.storedassetblob')),
            ],
            options={
                'verbose_name': '공유 자료',
                'verbose_name_plural': '공유 자료',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAssetLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_links', to='schoolcomm.roommessage')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='schoolcomm.sharedasset')),
            ],
            options={
                'verbose_name': '메시지 자료 연결',
                'verbose_name_plural': '메시지 자료 연결',
            },
        ),
        migrations.CreateModel(
            name='CalendarSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '검토 대기'), ('applied', '적용 완료'), ('dismissed', '숨김')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_calendar_suggestions', to=settings.AUTH_USER_MODEL)),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_suggestions', to='schoolcomm.roommessage')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_suggestions', to='schoolcomm.sharedasset')),
            ],
            options={
                'verbose_name': '캘린더 추천',
                'verbose_name_plural': '캘린더 추천',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('unclassified', '미분류'), ('lesson', '수업자료'), ('assessment', '평가자료'), ('work', '업무'), ('other', '기타')], default='unclassified', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('source', models.CharField(choices=[('auto', '자동'), ('manual', '수동')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to='schoolcomm.sharedasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_asset_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자별 자료 분류',
                'verbose_name_plural': '사용자별 자료 분류',
            },
        ),
        migrations.CreateModel(
            name='UserRoomState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count_cache', models.PositiveIntegerField(default=0)),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schoolcomm.roommessage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='schoolcomm.communityroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_room_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '방 읽음 상태',
                'verbose_name_plural': '방 읽음 상태',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('owner', '소유자'), ('admin', '관리자'), ('member', '멤버')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', '대기'), ('accepted', '수락'), ('expired', '만료'), ('revoked', '취소')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_school_workspace_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_workspace_invites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='schoolcomm.schoolworkspace')),
            ],
            options={
                'verbose_name': '워크스페이스 초대',
                'verbose_name_plural': '워크스페이스 초대',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('ack', '확인')], default='ack', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_message_reactions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='schoolcomm.roommessage')),
            ],
            options={
                'verbose_name': '메시지 반응',
                'verbose_name_plural': '메시지 반응',
                'unique_together': {('message', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schoolcomm.communityroom')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to='schoolcomm.schoolmembership')),
            ],
            options={
                'verbose_name': '방 참여자',
                'verbose_name_plural': '방 참여자',
                'ordering': ['joined_at', 'membership__user__username'],
                'unique_together': {('room', 'membership')},
            },
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['room', 'created_at'], name='schoolcomm__room_id_3b56d9_idx'),
        ),
        migrations.AddIndex(
            model_name='roommessage',
            index=models.Index(fields=['parent_message', 'created_at'], name='schoolcomm__parent__209673_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['user', 'status'], name='schoolcomm__user_id_e66e62_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['workspace', 'status'], name='schoolcomm__workspa_9b9723_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolmembership',
            unique_together={('workspace', 'user')},
        ),
        migrations.AddIndex(
            model_name='communityroom',
            index=models.Index(fields=['workspace', 'room_kind'], name='schoolcomm__workspa_a88c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='communityroom',
            index=models.Index(fields=['workspace', 'last_message_at'], name='schoolcomm__workspa_4ff160_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageassetlink',
            unique_together={('message', 'asset')},
        ),
        migrations.AddIndex(
            model_name='calendarsuggestion',
            index=models.Index(fields=['user', 'status'], name='schoolcomm__user_id_323993_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedasset',
            index=models.Index(fields=['original_name'], name='schoolcomm__origina_1d0f97_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedasset',
            index=models.Index(fields=['file_extension'], name='schoolcomm__file_ex_ef1368_idx'),
        ),
        migrations.AddIndex(
            model_name='userassetcategory',
            index=models.Index(fields=['user', 'category'], name='schoolcomm__user_id_77bef1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userassetcategory',
            unique_together={('user', 'asset')},
        ),
        migrations.AddIndex(
            model_name='userroomstate',
            index=models.Index(fields=['user', 'unread_count_cache'], name='schoolcomm__user_id_f81f19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userroomstate',
            unique_together={('room', 'user')},
        ),
    ]
