# Generated by Django 6.0.1 on 2026-04-03 01:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcalendar', '0017_alter_calendarmessagecapturecandidate_candidate_kind'),
        ('schoolcomm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default='emerald', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_calendar_events', to='schoolcomm.schoolmembership')),
                ('updated_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_shared_calendar_events', to='schoolcomm.schoolmembership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendar_events', to='schoolcomm.schoolworkspace')),
            ],
            options={
                'verbose_name': '끼리끼리 공유 일정',
                'verbose_name_plural': '끼리끼리 공유 일정',
                'ordering': ['start_time', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SharedCalendarEventCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('personal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schoolcomm_source_copies', to='classcalendar.calendarevent')),
                ('shared_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='schoolcomm.sharedcalendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_shared_calendar_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '끼리끼리 일정 개인 복사',
                'verbose_name_plural': '끼리끼리 일정 개인 복사',
            },
        ),
        migrations.AddIndex(
            model_name='sharedcalendarevent',
            index=models.Index(fields=['workspace', 'start_time'], name='schoolcomm__workspa_0db34a_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedcalendarevent',
            index=models.Index(fields=['workspace', 'end_time'], name='schoolcomm__workspa_6e8d96_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedcalendareventcopy',
            index=models.Index(fields=['user', 'copied_at'], name='schoolcomm__user_id_6f68d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sharedcalendareventcopy',
            unique_together={('shared_event', 'user')},
        ),
    ]
