# Generated by Django 6.0.1 on 2026-03-09 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classcalendar', '0012_calendarmessagecapture_confirmed_item_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HwpxDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='hwpxchat/%Y/%m/%d')),
                ('original_name', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('document_title', models.CharField(blank=True, default='', max_length=200)),
                ('raw_markdown', models.TextField(blank=True, default='')),
                ('summary_text', models.CharField(blank=True, default='', max_length=255)),
                ('parse_payload', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, default='deepseek', max_length=30)),
                ('structure_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('fallback', 'Fallback'), ('too_large', 'Too Large'), ('limit_blocked', 'Limit Blocked'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pipeline_version', models.CharField(default='workitem-v1', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hwpx_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HwpxDocumentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('normalized_question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True, default='')),
                ('citations_json', models.JSONField(blank=True, default=list)),
                ('has_insufficient_evidence', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='deepseek', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hwpxchat.hwpxdocument')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HwpxWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('action_text', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('assignee_text', models.CharField(blank=True, default='', max_length=120)),
                ('target_text', models.CharField(blank=True, default='', max_length=200)),
                ('materials_text', models.TextField(blank=True, default='')),
                ('delivery_required', models.BooleanField(default=False)),
                ('evidence_text', models.TextField(blank=True, default='')),
                ('evidence_refs_json', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('skipped', 'Skipped'), ('saved', 'Saved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='hwpxchat.hwpxdocument')),
            ],
            options={
                'ordering': ['sort_order', 'created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='hwpxdocument',
            index=models.Index(fields=['owner', 'created_at'], name='hwpxchat_hw_owner_i_e35dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='hwpxdocument',
            index=models.Index(fields=['owner', 'file_sha256', 'pipeline_version'], name='hwpxchat_hw_owner_i_0c1af2_idx'),
        ),
        migrations.AddConstraint(
            model_name='hwpxdocument',
            constraint=models.UniqueConstraint(fields=('owner', 'file_sha256', 'pipeline_version'), name='hwpx_document_unique_owner_hash_pipeline'),
        ),
        migrations.AddIndex(
            model_name='hwpxdocumentquestion',
            index=models.Index(fields=['document', 'normalized_question', 'provider'], name='hwpxchat_hw_documen_19cd68_idx'),
        ),
        migrations.AddIndex(
            model_name='hwpxworkitem',
            index=models.Index(fields=['document', 'sort_order'], name='hwpxchat_hw_documen_644eec_idx'),
        ),
    ]
