# Generated by Django 6.0.1 on 2026-04-12 00:00

from django.db import migrations


def drop_legacy_work_item_sync(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "hwpxchat_hwpxworkitemsync"
    if table_name not in set(connection.introspection.table_names()):
        return

    quoted_table = schema_editor.quote_name(table_name)
    drop_sql = f"DROP TABLE IF EXISTS {quoted_table}"
    if connection.vendor == "postgresql":
        drop_sql = f"{drop_sql} CASCADE"

    with connection.cursor() as cursor:
        cursor.execute(drop_sql)


class Migration(migrations.Migration):

    dependencies = [
        ("hwpxchat", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(drop_legacy_work_item_sync, migrations.RunPython.noop),
    ]
