# Generated by Django 6.0.1 on 2026-01-24 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='수업 제목')),
                ('youtube_url', models.URLField(verbose_name='유튜브 URL')),
                ('default_interval', models.PositiveIntegerField(default=10, verbose_name='기본 간격(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='art_classes', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '미술 수업',
                'verbose_name_plural': '미술 수업들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='단계 번호')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artclass/steps/', verbose_name='참고 이미지')),
                ('art_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='artclass.artclass', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수업 단계',
                'verbose_name_plural': '수업 단계들',
                'ordering': ['step_number'],
            },
        ),
    ]
