# Generated by Django 6.0.1 on 2026-01-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artclass',
            name='is_shared',
            field=models.BooleanField(default=True, verbose_name='공유 여부'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
