# Generated by Django 6.0.1 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artclass", "0002_artclass_is_shared_artclass_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="artclass",
            name="playback_mode",
            field=models.CharField(
                choices=[
                    ("embed", "내장 플레이어 (기본)"),
                    ("external_window", "새 창 재생 (임베드 차단 대응)"),
                ],
                default="embed",
                help_text="임베드 불가 영상일 경우 새 창 재생 모드를 사용할 수 있습니다.",
                max_length=24,
                verbose_name="영상 재생 모드",
            ),
        ),
    ]
