# Generated by Django 6.0.1 on 2026-03-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artclass', '0003_artclass_playback_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='artclass',
            name='auto_category',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='자동 카테고리'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='auto_confidence',
            field=models.FloatField(default=0.0, verbose_name='자동 분류 신뢰도'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='auto_grade_band',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='자동 학년군'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='auto_tags',
            field=models.JSONField(blank=True, default=list, verbose_name='자동 태그'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='is_auto_classified',
            field=models.BooleanField(default=False, verbose_name='자동 분류 완료'),
        ),
        migrations.AddField(
            model_name='artclass',
            name='search_text',
            field=models.TextField(blank=True, default='', verbose_name='검색 텍스트'),
        ),
    ]
