# Generated by Django 6.0.1 on 2026-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artclass', '0004_artclass_auto_category_artclass_auto_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artclass',
            name='playback_mode',
            field=models.CharField(choices=[('embed', '브라우저 임베드 (레거시)'), ('external_window', '런처 시작 (기본)')], default='external_window', help_text='기본 시작은 런처입니다. 브라우저 임베드는 레거시 호환용으로만 유지됩니다.', max_length=24, verbose_name='영상 재생 모드'),
        ),
    ]
