# Generated by Django 6.0.1 on 2026-03-24 01:07

import artclass.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artclass', '0005_alter_artclass_playback_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='artclass',
            name='teacher_material_note',
            field=models.TextField(blank=True, default='', verbose_name='교사용 자료 활용 메모'),
        ),
        migrations.CreateModel(
            name='ArtClassAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=artclass.models.artclass_material_upload_to, verbose_name='첨부 파일')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='원본 파일명')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('art_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='artclass.artclass', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수업 자료 첨부',
                'verbose_name_plural': '수업 자료 첨부',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
