# Generated by Django 6.0.1 on 2026-01-23 01:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='연수 제목')),
                ('instructor', models.CharField(max_length=100, verbose_name='강사명')),
                ('datetime', models.DateTimeField(verbose_name='연수 일시')),
                ('location', models.CharField(max_length=200, verbose_name='장소')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='서명 받기 활성화')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '연수',
                'verbose_name_plural': '연수 목록',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=50, verbose_name='참여자 이름')),
                ('signature_data', models.TextField(verbose_name='서명 데이터 (Base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='서명 일시')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='signatures.trainingsession', verbose_name='연수')),
            ],
            options={
                'verbose_name': '서명',
                'verbose_name_plural': '서명 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
