# Generated by Django 6.0.1 on 2026-01-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='participant_affiliation',
            field=models.CharField(blank=True, max_length=100, verbose_name='직위/학년반'),
        ),
    ]
