# Generated by Django 6.0.1 on 2026-01-26 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_signature_participant_affiliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='내 서명 스타일', max_length=100, verbose_name='스타일 이름')),
                ('font_family', models.CharField(default='Nanum Brush Script', max_length=100, verbose_name='폰트')),
                ('color', models.CharField(default='#000000', max_length=20, verbose_name='글자 색상')),
                ('background_color', models.CharField(default='transparent', max_length=20, verbose_name='배경 색상')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_styles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
