# Generated by Django 6.0.1 on 2026-02-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_savedsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='expected_count',
            field=models.IntegerField(blank=True, help_text='입력 시 진행률을 실시간으로 확인할 수 있습니다', null=True, verbose_name='예상 참석 인원'),
        ),
    ]
