# Generated by Django 6.0.1 on 2026-02-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0005_trainingsession_expected_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('affiliation', models.CharField(blank=True, help_text='예: 1-1, 2-3, 교사', max_length=100, verbose_name='소속/학년반')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='매칭 확인')),
                ('match_note', models.CharField(blank=True, help_text='예: 오타 수정 (박영이 → 박영희)', max_length=200, verbose_name='매칭 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_expected', to='signatures.signature', verbose_name='매칭된 서명')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_participants', to='signatures.trainingsession', verbose_name='연수')),
            ],
            options={
                'verbose_name': '예상 참석자',
                'verbose_name_plural': '예상 참석자 목록',
                'ordering': ['name', 'affiliation'],
                'unique_together': {('training_session', 'name', 'affiliation')},
            },
        ),
    ]
