# Generated by Django 6.0.1 on 2026-02-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0007_signaturedocument_signaturerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureposition',
            name='h_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signatureposition',
            name='w_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signatureposition',
            name='x_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signatureposition',
            name='y_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='preview_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
