# Generated by Django 6.0.1 on 2026-02-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0008_signatureposition_h_ratio_signatureposition_w_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='print_title',
            field=models.CharField(blank=True, help_text='인쇄 상단 제목(미입력 시 자동 제목 사용)', max_length=200, verbose_name='인쇄 제목'),
        ),
    ]
