# Generated by Django 6.0.1 on 2026-02-18 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0001_initial"),
        ("signatures", "0009_trainingsession_print_title"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="ConsentAuditLog"),
                migrations.DeleteModel(name="SignaturePosition"),
                migrations.DeleteModel(name="SignatureRecipient"),
                migrations.DeleteModel(name="SignatureRequest"),
                migrations.DeleteModel(name="SignatureDocument"),
            ],
        )
    ]
