# Generated by Django 6.0.1 on 2026-02-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0001_initial'),
        ('signatures', '0010_detach_consent_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='shared_roster_group',
            field=models.ForeignKey(blank=True, help_text='배부 체크 명단과 연결해 참석자 명단으로 재사용', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_sessions', to='handoff.handoffrostergroup', verbose_name='공유 명단'),
        ),
    ]
