# Generated by Django 6.0.1 on 2026-03-01 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0012_signature_affiliation_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('signature', '서명'), ('participant', '예상 참석자')], max_length=20, verbose_name='대상 유형')),
                ('mode', models.CharField(choices=[('single', '개별 정정'), ('bulk', '일괄 정정'), ('script', '정규화 스크립트')], default='single', max_length=20, verbose_name='수정 방식')),
                ('before_affiliation', models.CharField(blank=True, max_length=100, verbose_name='변경 전')),
                ('after_affiliation', models.CharField(blank=True, max_length=100, verbose_name='변경 후')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수정 시각')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliation_correction_logs', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('expected_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliation_correction_logs', to='signatures.expectedparticipant', verbose_name='대상 예상 참석자')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliation_correction_logs', to='signatures.signature', verbose_name='대상 서명')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_correction_logs', to='signatures.trainingsession', verbose_name='연수')),
            ],
            options={
                'verbose_name': '직위/학년반 정정 로그',
                'verbose_name_plural': '직위/학년반 정정 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
