# Generated by Django 6.0.1 on 2026-03-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0013_affiliationcorrectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='제출 IP'),
        ),
        migrations.AddField(
            model_name='signature',
            name='submission_mode',
            field=models.CharField(choices=[('open', '공유 링크')], default='open', max_length=20, verbose_name='제출 방식'),
        ),
        migrations.AddField(
            model_name='signature',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='제출 브라우저'),
        ),
        migrations.CreateModel(
            name='SignatureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sign_submitted', '서명 제출')], max_length=40, verbose_name='이벤트 유형')),
                ('event_meta', models.JSONField(blank=True, default=dict, verbose_name='이벤트 메타')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='브라우저')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('expected_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='signatures.expectedparticipant', verbose_name='예상 참석자')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='signatures.signature', verbose_name='서명')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='signatures.trainingsession', verbose_name='연수')),
            ],
            options={
                'verbose_name': '서명 감사 로그',
                'verbose_name_plural': '서명 감사 로그',
                'ordering': ['-created_at'],
            },
        ),
    ]
