# Generated by Django 6.0.1 on 2026-03-11 05:54

from django.db import migrations, models


def populate_manual_sort_order(apps, schema_editor):
    TrainingSession = apps.get_model("signatures", "TrainingSession")
    Signature = apps.get_model("signatures", "Signature")

    for session in TrainingSession.objects.all().iterator():
        signatures = list(
            Signature.objects.filter(training_session_id=session.id).order_by("created_at", "id")
        )
        for index, signature in enumerate(signatures, start=1):
            signature.manual_sort_order = index
        if signatures:
            Signature.objects.bulk_update(signatures, ["manual_sort_order"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0014_signature_ip_address_signature_submission_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='manual_sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='수동 정렬 순서'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='signature_sort_mode',
            field=models.CharField(choices=[('submitted', '사인한 순서'), ('affiliation', '학년반/이름 정렬'), ('manual', '직접 순서 정하기')], default='affiliation', help_text='명단 없이 받은 서명을 어떤 순서로 보여주고 출력할지 정합니다.', max_length=20, verbose_name='서명 정렬 방식'),
        ),
        migrations.RunPython(populate_manual_sort_order, noop_reverse),
    ]
