# Generated by Django 6.0.1 on 2026-03-11 06:46

from django.db import migrations, models


def populate_expected_participant_manual_sort_order(apps, schema_editor):
    TrainingSession = apps.get_model("signatures", "TrainingSession")
    ExpectedParticipant = apps.get_model("signatures", "ExpectedParticipant")

    for session in TrainingSession.objects.all().iterator():
        participants = list(
            ExpectedParticipant.objects.filter(training_session_id=session.id).order_by("created_at", "id")
        )
        for index, participant in enumerate(participants, start=1):
            participant.manual_sort_order = index
        if participants:
            ExpectedParticipant.objects.bulk_update(participants, ["manual_sort_order"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0015_signature_manual_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedparticipant',
            name='manual_sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='수동 정렬 순서'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='participant_sort_mode',
            field=models.CharField(choices=[('submitted', '사인한 순서'), ('affiliation', '학년반/이름 정렬'), ('manual', '직접 순서 정하기')], default='submitted', help_text='명단이 있는 경우 출석부에 어떤 순서로 보여줄지 정합니다.', max_length=20, verbose_name='명단 정렬 방식'),
        ),
        migrations.RunPython(populate_expected_participant_manual_sort_order, noop_reverse),
    ]
