# Generated by Django 6.0.1 on 2026-04-02 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0017_trainingsession_access_code_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='proxy_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_created_training_sessions', to=settings.AUTH_USER_MODEL, verbose_name='대행 생성자'),
        ),
    ]
