# Generated by Django 6.0.1 on 2026-04-03 00:35

import django.db.models.deletion
import signatures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0018_trainingsession_proxy_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSessionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=signatures.models.training_session_attachment_upload_to, verbose_name='첨부 파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='signatures.trainingsession', verbose_name='연수')),
            ],
            options={
                'verbose_name': '연수 첨부 파일',
                'verbose_name_plural': '연수 첨부 파일',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
