# Generated by Django 6.0.3 on 2026-04-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0019_trainingsessionattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='last_shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 공유 시작 시각'),
        ),
    ]
