# Generated by Django 6.0.3 on 2026-04-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0020_trainingsession_last_shared_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='consent_checkbox_checked',
            field=models.BooleanField(default=False, verbose_name='체크 동의 완료'),
        ),
        migrations.AddField(
            model_name='signature',
            name='consent_checkbox_text',
            field=models.CharField(blank=True, max_length=160, verbose_name='체크 동의 문구'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='consent_checkbox_text',
            field=models.CharField(blank=True, max_length=160, verbose_name='체크 동의 문구'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='require_consent_checkbox',
            field=models.BooleanField(default=False, verbose_name='체크 동의 받기'),
        ),
    ]
