# Generated by Django 6.0.1 on 2026-03-18 05:48

import django.db.models.deletion
import infoboard.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='보드 이름', max_length=200)),
                ('description', models.TextField(blank=True, help_text='보드 설명')),
                ('icon', models.CharField(default='📌', help_text='이모지 아이콘', max_length=10)),
                ('color_theme', models.CharField(choices=[('blue', '파란색'), ('green', '초록색'), ('purple', '보라색'), ('orange', '주황색'), ('red', '빨간색'), ('dark', '어두운색')], default='purple', max_length=20)),
                ('layout', models.CharField(choices=[('grid', '격자형'), ('list', '목록형'), ('timeline', '타임라인')], default='grid', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='비로그인 열람 허용')),
                ('allow_student_submit', models.BooleanField(default=False, help_text='학생 카드 제출 허용')),
                ('access_code', models.CharField(blank=True, help_text='6자리 입장코드', max_length=6, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoboard_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '보드',
                'verbose_name_plural': '보드 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boards', models.ManyToManyField(blank=True, related_name='collections', to='infoboard.board')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoboard_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '컬렉션',
                'verbose_name_plural': '컬렉션 목록',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_level', models.CharField(choices=[('view', '보기만'), ('submit', '카드 제출'), ('edit', '편집')], default='view', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='infoboard.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoboard_shared_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '공유 링크',
                'verbose_name_plural': '공유 링크 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infoboard_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'ordering': ['name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, help_text='비로그인 제출자 이름', max_length=100)),
                ('card_type', models.CharField(choices=[('link', '링크'), ('file', '파일'), ('image', '이미지'), ('text', '메모')], default='text', max_length=10)),
                ('title', models.CharField(help_text='카드 제목', max_length=300)),
                ('content', models.TextField(blank=True, help_text='텍스트/메모 내용')),
                ('url', models.URLField(blank=True, help_text='링크 URL', max_length=1000)),
                ('file', models.FileField(blank=True, null=True, storage=infoboard.models._get_raw_storage, upload_to='infoboard/files/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='파일 크기(bytes)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='infoboard/images/')),
                ('color', models.CharField(blank=True, help_text='카드 배경색 hex', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='상단 고정')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoboard_cards', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='infoboard.board')),
                ('tags', models.ManyToManyField(blank=True, related_name='cards', to='infoboard.tag')),
            ],
            options={
                'verbose_name': '카드',
                'verbose_name_plural': '카드 목록',
                'ordering': ['-is_pinned', 'display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='boards', to='infoboard.tag'),
        ),
    ]
