# Generated by Django 6.0.1 on 2026-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='og_description',
            field=models.TextField(blank=True, help_text='OG 설명'),
        ),
        migrations.AddField(
            model_name='card',
            name='og_image',
            field=models.URLField(blank=True, help_text='OG 이미지 URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='card',
            name='og_site_name',
            field=models.CharField(blank=True, help_text='OG 사이트명', max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='og_title',
            field=models.CharField(blank=True, help_text='OG 제목', max_length=500),
        ),
    ]
