# Generated by Django 6.0.1 on 2026-03-19 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handoff', '0002_handoffrostermember_affiliation_and_more'),
        ('infoboard', '0002_card_og_description_card_og_image_card_og_site_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='shared_roster_group',
            field=models.ForeignKey(blank=True, help_text='학생 제출 이름을 공용 명부와 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoboard_boards', to='handoff.handoffrostergroup'),
        ),
    ]
