# Generated by Django 6.0.1 on 2026-03-19 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoboard', '0002_card_og_description_card_og_image_card_og_site_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='moderation_mode',
            field=models.CharField(choices=[('instant', '바로 공개'), ('manual', '승인 후 공개')], default='instant', help_text='학생 참여를 바로 공개할지 승인 후 공개할지 정합니다.', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('published', '게시됨'), ('pending', '승인 대기'), ('hidden', '숨김')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedlink',
            name='access_level',
            field=models.CharField(choices=[('view', '읽기'), ('comment', '댓글·반응'), ('submit', '제출'), ('edit', '관리')], default='view', max_length=10),
        ),
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('published', '게시됨'), ('pending', '승인 대기'), ('hidden', '숨김')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoboard_card_comments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='infoboard.card')),
                ('shared_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_comments', to='infoboard.sharedlink')),
            ],
            options={
                'verbose_name': '카드 댓글',
                'verbose_name_plural': '카드 댓글 목록',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_key', models.CharField(blank=True, max_length=64)),
                ('reaction_type', models.CharField(choices=[('like', '좋아요'), ('idea', '아이디어'), ('question', '질문')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='infoboard.card')),
                ('shared_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_reactions', to='infoboard.sharedlink')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infoboard_card_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카드 반응',
                'verbose_name_plural': '카드 반응 목록',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('card', 'user'), name='infoboard_unique_reaction_per_user'), models.UniqueConstraint(condition=models.Q(('guest_key__gt', '')), fields=('card', 'guest_key'), name='infoboard_unique_reaction_per_guest')],
            },
        ),
    ]
