# Generated by Django 6.0.1 on 2026-04-10 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infoboard', '0003_board_shared_roster_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(max_length=300)),
                ('is_hidden', models.BooleanField(default=False)),
                ('hidden_reason', models.CharField(blank=True, choices=[('', '해당 없음'), ('teacher', '교사 숨김')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infoboard_comments', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='infoboard.card')),
            ],
            options={
                'verbose_name': '카드 댓글',
                'verbose_name_plural': '카드 댓글 목록',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['card', 'is_hidden', 'created_at'], name='infoboard_c_card_id_a2708e_idx')],
            },
        ),
    ]
