# Generated by Django 6.0.1 on 2026-02-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('column_type', models.CharField(choices=[('text', '텍스트'), ('number', '숫자'), ('date', '날짜'), ('select', '단일선택'), ('multi_select', '다중선택'), ('checkbox', '체크박스'), ('file', '파일')], default='text', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=160)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sheetbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', '비공개'), ('school', '학교 공유')], default='private', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sheet_rows', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sheet_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SheetCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheetbook.sheetcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='sheetbook.sheetrow')),
            ],
        ),
        migrations.CreateModel(
            name='SheetTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tab_type', models.CharField(choices=[('grid', '그리드'), ('calendar', '달력')], default='grid', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='sheetbook.sheetbook')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sheetbook.sheettab'),
        ),
        migrations.AddField(
            model_name='sheetcolumn',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='sheetbook.sheettab'),
        ),
        migrations.AddIndex(
            model_name='sheetbook',
            index=models.Index(fields=['owner', 'updated_at'], name='sheetbook_s_owner_i_99aab1_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetcell',
            index=models.Index(fields=['column', 'row'], name='sheetbook_s_column__228eed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetcell',
            unique_together={('row', 'column')},
        ),
        migrations.AddIndex(
            model_name='sheettab',
            index=models.Index(fields=['sheetbook', 'sort_order'], name='sheetbook_s_sheetbo_dd0646_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['tab', 'sort_order'], name='sheetbook_s_tab_id_fb5a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetcolumn',
            index=models.Index(fields=['tab', 'sort_order'], name='sheetbook_s_tab_id_c6abce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetcolumn',
            unique_together={('tab', 'key')},
        ),
    ]
