# Generated by Django 6.0.1 on 2026-02-27 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('calendar', '달력 등록'), ('collect', '간편 수합'), ('consent', '동의서'), ('handoff', '배부 체크'), ('notice', '안내문')], max_length=20)),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패')], default='success', max_length=20)),
                ('selection_start_row', models.PositiveIntegerField(default=0)),
                ('selection_start_col', models.PositiveIntegerField(default=0)),
                ('selection_end_row', models.PositiveIntegerField(default=0)),
                ('selection_end_col', models.PositiveIntegerField(default=0)),
                ('selected_cell_count', models.PositiveIntegerField(default=0)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('result_label', models.CharField(blank=True, max_length=200)),
                ('result_url', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheetbook_action_invocations', to=settings.AUTH_USER_MODEL)),
                ('sheetbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_invocations', to='sheetbook.sheetbook')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_invocations', to='sheetbook.sheettab')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sheetbook', 'created_at'], name='sheetbook_a_sheetbo_eede0e_idx'), models.Index(fields=['tab', 'created_at'], name='sheetbook_a_tab_id_1ceb02_idx'), models.Index(fields=['actor', 'created_at'], name='sheetbook_a_actor_i_7ba97e_idx')],
            },
        ),
    ]
