# Generated by Django 6.0.1 on 2026-02-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbook', '0002_actioninvocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetbookMetricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=80)),
                ('action_type', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheetbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to='sheetbook.sheetbook')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_events', to='sheetbook.sheettab')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheetbook_metric_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='sheetbook_s_event_n_de08d5_idx'), models.Index(fields=['user', 'created_at'], name='sheetbook_s_user_id_2c3cce_idx'), models.Index(fields=['sheetbook', 'created_at'], name='sheetbook_s_sheetbo_e25555_idx'), models.Index(fields=['tab', 'created_at'], name='sheetbook_s_tab_id_824a8a_idx')],
            },
        ),
    ]
