# Generated by Django 6.0.1 on 2026-03-01 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbook', '0003_sheetbookmetricevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('filter_text', models.CharField(blank=True, max_length=120)),
                ('sort_direction', models.CharField(choices=[('asc', '오름차순'), ('desc', '내림차순')], default='asc', max_length=4)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheetbook_saved_views', to=settings.AUTH_USER_MODEL)),
                ('sort_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_views', to='sheetbook.sheetcolumn')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='sheetbook.sheettab')),
            ],
            options={
                'ordering': ['-is_favorite', 'name', 'id'],
                'indexes': [models.Index(fields=['tab', 'is_favorite', 'id'], name='sheetbook_s_tab_id_40805e_idx'), models.Index(fields=['tab', 'is_default'], name='sheetbook_s_tab_id_6b63a3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tab',), name='sheetbook_savedview_one_default_per_tab')],
            },
        ),
    ]
