# Generated by Codex on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sheetbook", "0004_savedview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actioninvocation",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("calendar", "달력 등록"),
                    ("collect", "간편 수합"),
                    ("consent", "동의서"),
                    ("signature", "서명 요청"),
                    ("handoff", "배부 체크"),
                    ("notice", "안내문"),
                ],
                max_length=20,
            ),
        ),
    ]
