# Generated by Django 6.0.1 on 2026-03-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetbook', '0006_sheetbook_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetbook',
            name='preferred_calendar_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_calendar_sheetbooks', to='sheetbook.sheettab'),
        ),
        migrations.AddField(
            model_name='sheetbook',
            name='preferred_schedule_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_schedule_sheetbooks', to='sheetbook.sheettab'),
        ),
    ]
