# Generated by Django 6.0.4 on 2026-04-09 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='프로그램명')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('summary', models.CharField(max_length=180, verbose_name='대표 소개')),
                ('description', models.TextField(verbose_name='프로그램 소개')),
                ('category', models.CharField(choices=[('fieldtrip', '찾아오는 체험학습'), ('teacher_training', '교사연수'), ('school_event', '학교행사'), ('sports_day', '스포츠데이'), ('one_day_class', '원데이 클래스')], max_length=40, verbose_name='카테고리')),
                ('theme_tags', models.JSONField(blank=True, default=list, verbose_name='주제 태그')),
                ('theme_tags_text', models.CharField(blank=True, max_length=300, verbose_name='주제 태그 입력값')),
                ('grade_bands', models.JSONField(blank=True, default=list, verbose_name='대상 학년')),
                ('grade_bands_text', models.CharField(blank=True, max_length=200, verbose_name='대상 학년 검색용')),
                ('delivery_mode', models.CharField(choices=[('visiting', '학교 방문형'), ('event_support', '행사 지원형'), ('hybrid', '혼합형'), ('online', '온라인/원격형')], max_length=30, verbose_name='진행 방식')),
                ('province', models.CharField(choices=[('nationwide', '전국'), ('seoul', '서울'), ('busan', '부산'), ('daegu', '대구'), ('incheon', '인천'), ('gwangju', '광주'), ('daejeon', '대전'), ('ulsan', '울산'), ('sejong', '세종'), ('gyeonggi', '경기'), ('gangwon', '강원'), ('chungbuk', '충북'), ('chungnam', '충남'), ('jeonbuk', '전북'), ('jeonnam', '전남'), ('gyeongbuk', '경북'), ('gyeongnam', '경남'), ('jeju', '제주')], max_length=20, verbose_name='대표 활동 지역')),
                ('coverage_note', models.CharField(blank=True, max_length=140, verbose_name='방문 가능 지역 메모')),
                ('duration_text', models.CharField(max_length=80, verbose_name='진행 시간')),
                ('capacity_text', models.CharField(max_length=80, verbose_name='수용 인원')),
                ('price_text', models.CharField(max_length=120, verbose_name='가격 표시')),
                ('safety_info', models.TextField(blank=True, verbose_name='안전/보험 안내')),
                ('materials_info', models.TextField(blank=True, verbose_name='준비물/요청 사항')),
                ('faq', models.TextField(blank=True, verbose_name='자주 묻는 질문')),
                ('admin_note', models.TextField(blank=True, verbose_name='운영 메모')),
                ('approval_status', models.CharField(choices=[('draft', '임시 저장'), ('pending', '심사 대기'), ('approved', '공개중'), ('rejected', '반려')], default='draft', max_length=20, verbose_name='공개 상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 노출')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='누적 조회수')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='심사 요청 시각')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='공개 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '학교 프로그램 등록글',
                'verbose_name_plural': '학교 프로그램 등록글',
                'ordering': ['-is_featured', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InquiryThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('fieldtrip', '찾아오는 체험학습'), ('teacher_training', '교사연수'), ('school_event', '학교행사'), ('sports_day', '스포츠데이'), ('one_day_class', '원데이 클래스')], max_length=40)),
                ('school_region', models.CharField(max_length=80, verbose_name='학교 지역')),
                ('preferred_schedule', models.CharField(max_length=120, verbose_name='희망 시기')),
                ('target_audience', models.CharField(max_length=120, verbose_name='대상')),
                ('expected_participants', models.PositiveIntegerField(verbose_name='예상 인원')),
                ('budget_text', models.CharField(blank=True, max_length=120, verbose_name='예산')),
                ('status', models.CharField(choices=[('awaiting_vendor', '업체 답변 대기'), ('in_progress', '진행 중'), ('proposal_sent', '제안 도착'), ('closed', '종료')], default='awaiting_vendor', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('last_message_sender_role', models.CharField(blank=True, choices=[('teacher', '교사'), ('vendor', '업체')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_program_inquiries', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='schoolprograms.programlisting')),
            ],
            options={
                'verbose_name': '학교 프로그램 문의 스레드',
                'verbose_name_plural': '학교 프로그램 문의 스레드',
                'ordering': ['-last_message_at', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InquiryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_text', models.CharField(max_length=200, verbose_name='비용 범위')),
                ('included_items', models.TextField(verbose_name='포함 항목')),
                ('schedule_note', models.TextField(verbose_name='일정 메모')),
                ('preparation_note', models.TextField(blank=True, verbose_name='준비 요청')),
                ('followup_request', models.TextField(blank=True, verbose_name='후속 요청')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_program_proposals', to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='schoolprograms.inquirythread')),
            ],
            options={
                'verbose_name': '학교 프로그램 제안 카드',
                'verbose_name_plural': '학교 프로그램 제안 카드',
            },
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('teacher', '교사'), ('vendor', '업체')], max_length=20)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_program_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schoolprograms.inquirythread')),
            ],
            options={
                'verbose_name': '학교 프로그램 문의 메시지',
                'verbose_name_plural': '학교 프로그램 문의 메시지',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to='schoolprograms/listings/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, max_length=140, verbose_name='이미지 설명')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schoolprograms.programlisting')),
            ],
            options={
                'verbose_name': '학교 프로그램 이미지',
                'verbose_name_plural': '학교 프로그램 이미지',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
                ('provider_name', models.CharField(max_length=120, verbose_name='업체명')),
                ('summary', models.CharField(blank=True, max_length=160, verbose_name='한 줄 소개')),
                ('description', models.TextField(blank=True, verbose_name='업체 소개')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='대표 이메일')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='대표 연락처')),
                ('website', models.URLField(blank=True, verbose_name='홈페이지')),
                ('service_area_summary', models.CharField(blank=True, max_length=120, verbose_name='주 활동 지역')),
                ('verification_document', models.FileField(blank=True, max_length=500, null=True, upload_to='schoolprograms/provider_docs/', verbose_name='증빙 서류')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_program_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학교 프로그램 업체',
                'verbose_name_plural': '학교 프로그램 업체',
                'ordering': ['provider_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='programlisting',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='schoolprograms.providerprofile'),
        ),
        migrations.AddField(
            model_name='inquirythread',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='schoolprograms.providerprofile'),
        ),
        migrations.CreateModel(
            name='ListingViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(blank=True, default='', max_length=120)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='schoolprograms.programlisting')),
            ],
            options={
                'verbose_name': '학교 프로그램 조회 기록',
                'verbose_name_plural': '학교 프로그램 조회 기록',
                'ordering': ['-viewed_at', '-id'],
                'indexes': [models.Index(fields=['listing', 'viewed_at'], name='schoolprogr_listing_64a8b6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='programlisting',
            index=models.Index(fields=['approval_status', 'category', 'province'], name='schoolprogr_approva_6b4f88_idx'),
        ),
        migrations.AddIndex(
            model_name='programlisting',
            index=models.Index(fields=['provider', 'approval_status'], name='schoolprogr_provide_e71111_idx'),
        ),
        migrations.AddIndex(
            model_name='programlisting',
            index=models.Index(fields=['slug'], name='schoolprogr_slug_809f98_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirythread',
            index=models.Index(fields=['teacher', 'status'], name='schoolprogr_teacher_6e0340_idx'),
        ),
        migrations.AddIndex(
            model_name='inquirythread',
            index=models.Index(fields=['provider', 'status'], name='schoolprogr_provide_f1f57b_idx'),
        ),
    ]
