# Generated by Django 6.0.3 on 2026-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprograms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlisting',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='대표 시군구'),
        ),
        migrations.AlterField(
            model_name='programlisting',
            name='coverage_note',
            field=models.CharField(blank=True, max_length=140, verbose_name='추가 방문 가능 권역'),
        ),
    ]
