# Generated by Django 6.0.3 on 2026-04-09 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprograms', '0002_programlisting_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='schoolprograms.programlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_school_program_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '학교 프로그램 저장',
                'verbose_name_plural': '학교 프로그램 저장',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='schoolprograms_unique_saved_listing')],
            },
        ),
    ]
