# Generated by Django 6.0.4 on 2026-04-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprograms', '0003_savedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirythread',
            name='is_agreement_reached',
            field=models.BooleanField(default=False, verbose_name='합의 완료 여부'),
        ),
    ]
