# Generated by Django 6.0.4 on 2026-04-09 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprograms', '0004_inquirythread_is_agreement_reached'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirythread',
            name='status',
            field=models.CharField(choices=[('awaiting_vendor', '업체 답변 대기'), ('in_progress', '진행 중'), ('proposal_sent', '제안 도착'), ('on_hold', '보류 중'), ('closed', '종료')], default='awaiting_vendor', max_length=20),
        ),
        migrations.CreateModel(
            name='InquiryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120, verbose_name='한 줄 후기')),
                ('body', models.TextField(max_length=2000, verbose_name='이용후기')),
                ('recommended_for', models.CharField(blank=True, max_length=180, verbose_name='이런 경우 추천')),
                ('status', models.CharField(choices=[('pending', '운영 검토 중'), ('published', '공개중'), ('hidden', '비공개')], default='pending', max_length=20, verbose_name='공개 상태')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='공개 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schoolprograms.programlisting')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schoolprograms.providerprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_program_reviews', to=settings.AUTH_USER_MODEL)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='schoolprograms.inquirythread')),
            ],
            options={
                'verbose_name': '학교 프로그램 이용후기',
                'verbose_name_plural': '학교 프로그램 이용후기',
                'ordering': ['-published_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['provider', 'status', 'published_at'], name='schoolprogr_provide_7c4150_idx'), models.Index(fields=['listing', 'status', 'published_at'], name='schoolprogr_listing_6d233a_idx')],
            },
        ),
    ]
