# Generated by Django 6.0.4 on 2026-04-10 07:41

import django.db.models.deletion
import schoolprograms.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprograms', '0005_alter_inquirythread_status_inquiryreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='verification_document',
            field=models.FileField(blank=True, max_length=500, null=True, storage=schoolprograms.storage.schoolprograms_document_storage, upload_to='schoolprograms/provider_docs/', verbose_name='증빙 서류'),
        ),
        migrations.CreateModel(
            name='ListingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=schoolprograms.storage.schoolprograms_document_storage, upload_to='schoolprograms/attachments/', verbose_name='첨부 파일')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='MIME 타입')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='파일 크기')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='schoolprograms.programlisting')),
            ],
            options={
                'verbose_name': '학교 프로그램 첨부파일',
                'verbose_name_plural': '학교 프로그램 첨부파일',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
