# Generated by Django 6.0.3 on 2026-04-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolprograms", "0006_alter_providerprofile_verification_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programlisting",
            name="schedule_basis",
            field=models.CharField(
                choices=[
                    ("school_level", "학교급 기준"),
                    ("elementary", "초등 기준"),
                    ("middle", "중등 기준"),
                    ("high", "고등 기준"),
                    ("flexible", "학교 시간표 조율"),
                ],
                default="school_level",
                max_length=20,
                verbose_name="기준 시간표",
            ),
        ),
        migrations.AddField(
            model_name="programlisting",
            name="schedule_detail",
            field=models.TextField(blank=True, verbose_name="상세 교시 운영안"),
        ),
        migrations.AddField(
            model_name="programlisting",
            name="venue_note",
            field=models.CharField(blank=True, max_length=180, verbose_name="공간 메모"),
        ),
        migrations.AddField(
            model_name="programlisting",
            name="venue_requirements",
            field=models.JSONField(blank=True, default=list, verbose_name="필요 공간"),
        ),
        migrations.AddField(
            model_name="programlisting",
            name="venue_requirements_text",
            field=models.CharField(blank=True, max_length=200, verbose_name="필요 공간 검색용"),
        ),
    ]
