# Generated by Django 6.0.1 on 2026-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_size',
            field=models.CharField(default='small', help_text='Card size: small, wide, tall, hero', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color_theme',
            field=models.CharField(default='purple', help_text='Color theme: purple, green, red, orange, blue', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which to display (lower numbers first)'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text='External URL for services hosted elsewhere'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(default='🛠️', help_text='Emoji or FontAwesome class for card icon', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.CharField(default='tool', help_text='Service type: game, tool, platform', max_length=20),
        ),
    ]
