# Generated by Django 6.0.1 on 2026-01-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_card_size_product_color_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_size',
            field=models.CharField(choices=[('small', 'Small (1x1)'), ('wide', 'Wide (2x1)'), ('tall', 'Tall (1x2)'), ('hero', 'Hero (2x2)')], default='small', help_text='Card size', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_theme',
            field=models.CharField(choices=[('purple', 'Purple'), ('green', 'Green'), ('red', 'Red'), ('orange', 'Orange'), ('blue', 'Blue'), ('dark', 'Dark')], default='purple', help_text='Color theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_type',
            field=models.CharField(choices=[('game', 'Game'), ('tool', 'Tool'), ('platform', 'Platform'), ('library', 'Library'), ('guide', 'Guide')], default='tool', help_text='Service type', max_length=20),
        ),
    ]
