# Generated by Django 6.0.1 on 2026-01-20 13:52

from django.db import migrations



def update_card_size(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(title="AI 프롬프트 레시피").update(card_size="wide")

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productfeature'),
    ]

    operations = [
        migrations.RunPython(update_card_size),
    ]
