# Generated by Django 6.0.1 on 2026-01-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_signatures_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lead_text',
            field=models.TextField(blank=True, help_text='Short lead text for modal display'),
        ),
    ]
