# Generated by Django 6.0.1 on 2026-01-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_dtrole_dtschedule_dtsettings_dtstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtsettings',
            name='last_broadcast_message',
            field=models.TextField(blank=True, help_text='Persisted broadcast message'),
        ),
        migrations.AddField(
            model_name='dtstudent',
            name='is_mission_completed',
            field=models.BooleanField(default=False, help_text='Daily mission completion status'),
        ),
    ]
