# Generated by Django 6.0.1 on 2026-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_dtsettings_last_broadcast_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtsettings',
            name='mission_desc',
            field=models.TextField(default='선생님 말씀에 집중해 주세요.', help_text='Main display mission description'),
        ),
        migrations.AddField(
            model_name='dtsettings',
            name='mission_title',
            field=models.CharField(default='오늘도 행복한 우리 교실', help_text='Main display mission title', max_length=200),
        ),
    ]
