# Generated by Django 6.0.1 on 2026-01-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_dtsettings_mission_desc_dtsettings_mission_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_guest_allowed',
            field=models.BooleanField(default=False, help_text='비회원 체험 가능 여부'),
        ),
    ]
