# Generated by Django 6.0.1 on 2026-01-30 13:31

from django.db import migrations



def create_ssambti_product(apps, schema_editor):
    """Create Ssambti product for production database"""
    Product = apps.get_model('products', 'Product')
    
    # Check if Ssambti product already exists
    if not Product.objects.filter(title='쌤BTI').exists():
        Product.objects.create(
            title='쌤BTI',
            lead_text='나는 어떤 선생님일까? 🦁',
            description='12가지 질문으로 알아보는 나의 교육 스타일! MBTI 기반 티처블 동물원에서 나와 닮은 동물을 찾아보세요.',
            price=0.00,
            is_active=True,
            is_featured=False,
            is_guest_allowed=True,
            icon='🦁',
            color_theme='orange',
            card_size='small',
            display_order=0,
            service_type='tool',
            external_url='/ssambti/',
        )
        print("✓ Ssambti product created successfully!")
    else:
        print("ℹ Ssambti product already exists, skipping creation.")


def delete_ssambti_product(apps, schema_editor):
    """Reverse migration: delete Ssambti product"""
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(title='쌤BTI').delete()
    print("✓ Ssambti product deleted.")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_is_guest_allowed'),
    ]

    operations = [
        migrations.RunPython(create_ssambti_product, delete_ssambti_product),
    ]
