# Generated by Django 6.0.1 on 2026-01-30 14:50

from django.db import migrations


def recreate_ssambti_product(apps, schema_editor):
    """
    Recreate Ssambti product with correct settings.
    This fixes the external_url issue from migration 0018.
    """
    Product = apps.get_model('products', 'Product')

    # Delete old version if exists (may have wrong external_url from 0018)
    Product.objects.filter(title='쌤BTI').delete()

    # Create fresh Ssambti product with correct settings
    Product.objects.create(
        title='쌤BTI',
        lead_text='나는 어떤 선생님일까? 🦁',
        description='12가지 질문으로 알아보는 나의 교육 스타일! MBTI 기반 티처블 동물원에서 나와 닮은 동물을 찾아보세요.',
        price=0.00,
        is_active=True,
        is_featured=False,
        is_guest_allowed=True,
        icon='🦁',
        color_theme='orange',
        card_size='small',
        display_order=13,  # After AI 프롬프트 레시피 (12)
        service_type='game',
        external_url='',  # CRITICAL FIX: Empty for internal service
    )
    print("[OK] Ssambti product recreated successfully with correct settings!")


def reverse_recreate(apps, schema_editor):
    """Reverse migration: delete Ssambti product"""
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(title='쌤BTI').delete()
    print("[OK] Ssambti product deleted.")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_add_ssambti_product'),
    ]

    operations = [
        migrations.RunPython(recreate_ssambti_product, reverse_recreate),
    ]
