# Generated by Django 6.0.1 on 2026-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_type',
            field=models.CharField(choices=[('classroom', '학급운영'), ('work', '업무경감'), ('lesson', '수업도구'), ('game', '게임모음'), ('counsel', '상담·운세'), ('edutech', '에듀테크'), ('etc', '기타')], default='etc', help_text='서비스 카테고리', max_length=20),
        ),
    ]
