# Generated by Django 6.0.1 on 2026-02-10 09:38

from django.db import migrations


def update_service_types(apps, schema_editor):
    """Update product service_type values from old categories to new ones."""
    Product = apps.get_model('products', 'Product')

    # Mapping: product_id -> new_service_type
    # Based on the confirmed local DB state
    updates = {
        121: 'classroom',   # 반짝반짝 우리반 알림판
        122: 'game',        # 왁자지껄 교실 윷놀이
        123: 'counsel',     # 토닥토닥 선생님 운세
        124: 'work',        # 가뿐하게 서명 톡
        125: 'work',        # 궁금해? 패들릿 봇
        126: 'classroom',   # 몽글몽글 미술 수업
        127: 'work',        # 글솜씨 뚝딱! 소식지
        128: 'etc',         # 유튜브 탈알고리즘
        129: 'etc',         # 학교 통합 지원 스쿨잇
        130: 'edutech',     # 인사이트
        131: 'edutech',     # AI 도구 가이드
        132: 'edutech',     # AI 프롬프트 레시피
        133: 'work',        # 학교폭력 사안 처리 비서
        135: 'counsel',     # 쌤BTI
        136: 'game',        # 두뇌 풀가동! 교실 체스
        137: 'work',        # HWP to PDF 변환기
        138: 'counsel',     # 우리반 캐릭터 친구 찾기
        139: 'work',        # 교사 백과사전
    }

    for product_id, service_type in updates.items():
        Product.objects.filter(id=product_id).update(service_type=service_type)

    # Also update any remaining products with old values to 'etc'
    old_values = ['tool', 'platform', 'library', 'guide']
    Product.objects.filter(service_type__in=old_values).update(service_type='etc')


def reverse_update(apps, schema_editor):
    """No reliable reverse - just pass."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_service_type'),
    ]

    operations = [
        migrations.RunPython(update_service_types, reverse_update),
    ]
