# Generated by Django 6.0.1 on 2026-02-10 09:38

from django.db import migrations


def update_service_types(apps, schema_editor):
    """Update product service_type values from old categories to new ones."""
    Product = apps.get_model('products', 'Product')

    # Mapping: product title (partial match) -> new_service_type
    title_to_category = {
        '알림판': 'classroom',
        '미술 수업': 'classroom',
        '윷놀이': 'game',
        '체스': 'game',
        '운세': 'counsel',
        '쌤BTI': 'counsel',
        'BTI': 'counsel',
        '캐릭터 친구': 'counsel',
        '서명': 'work',
        '패들릿': 'work',
        '소식지': 'work',
        '학교폭력': 'work',
        'HWP': 'work',
        'PDF': 'work',
        '백과사전': 'work',
        '인사이트': 'edutech',
        'AI 도구': 'edutech',
        '프롬프트': 'edutech',
        '탈알고리즘': 'etc',
        '스쿨잇': 'etc',
    }

    for keyword, service_type in title_to_category.items():
        Product.objects.filter(title__icontains=keyword).update(service_type=service_type)

    # Catch-all: any remaining products with old values -> etc
    old_values = ['tool', 'platform', 'library', 'guide']
    Product.objects.filter(service_type__in=old_values).update(service_type='etc')


def reverse_update(apps, schema_editor):
    """No reliable reverse - just pass."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_service_type'),
    ]

    operations = [
        migrations.RunPython(update_service_types, reverse_update),
    ]
