# Generated by Django 6.0.1 on 2026-02-10

from django.db import migrations


def fix_service_types(apps, schema_editor):
    """Fix product service_type values using title-based matching.

    This ensures correct categories regardless of product ID differences
    between local and production databases.
    """
    Product = apps.get_model('products', 'Product')

    # Mapping: keyword in title -> new service_type
    title_to_category = [
        ('알림판', 'classroom'),
        ('미술 수업', 'classroom'),
        ('몽글몽글', 'classroom'),
        ('윷놀이', 'game'),
        ('체스', 'game'),
        ('운세', 'counsel'),
        ('쌤BTI', 'counsel'),
        ('캐릭터 친구', 'counsel'),
        ('서명 톡', 'work'),
        ('패들릿', 'work'),
        ('소식지', 'work'),
        ('학교폭력', 'work'),
        ('HWP', 'work'),
        ('백과사전', 'work'),
        ('인사이트', 'edutech'),
        ('AI 도구', 'edutech'),
        ('프롬프트', 'edutech'),
        ('탈알고리즘', 'etc'),
        ('스쿨잇', 'etc'),
    ]

    for keyword, service_type in title_to_category:
        Product.objects.filter(title__icontains=keyword).update(service_type=service_type)

    # Catch-all: any remaining products with old category values -> etc
    old_values = ['tool', 'platform', 'library', 'guide', 'lesson']
    Product.objects.filter(service_type__in=old_values).update(service_type='etc')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_update_product_service_types_data'),
    ]

    operations = [
        migrations.RunPython(fix_service_types, migrations.RunPython.noop),
    ]
