# Generated by Django 6.0.1 on 2026-02-10 14:36

from django.db import migrations


def fix_service_type(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    # 'guide'는 SERVICE_CHOICES에 없는 잘못된 값 → 'edutech'로 수정
    Product.objects.filter(title='교사 백과사전', service_type='guide').update(service_type='edutech')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_fix_service_types_by_title'),
    ]

    operations = [
        migrations.RunPython(fix_service_type, migrations.RunPython.noop),
    ]
