# Generated by Django 6.0.1 on 2026-02-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_fix_notebooklm_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="매뉴얼 제목 (예: '선생님과 함께하는 000 시작하기')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='매뉴얼 소개글')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ManualSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, help_text='Markdown 지원')),
                ('image', models.ImageField(blank=True, null=True, upload_to='manuals/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo 임베드 URL')),
                ('layout_type', models.CharField(choices=[('text_only', '텍스트 전용'), ('image_left', '이미지 좌측 + 텍스트'), ('image_right', '텍스트 + 이미지 우측'), ('full_visual', '전체 너비 이미지/비디오'), ('card_carousel', '카드 캐러셀 (Quick Start)')], default='text_only', max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text='섹션 배지 (예: Tip, 핵심, 주의)', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.servicemanual')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
