# Generated by Django 6.0.1 on 2026-02-14 06:02

from django.db import migrations

def create_manual_data(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ServiceManual = apps.get_model('products', 'ServiceManual')
    ManualSection = apps.get_model('products', 'ManualSection')

    # 1. 학교 예약 시스템 매뉴얼
    try:
        reservation_product = Product.objects.get(title='학교 예약 시스템')
        manual, created = ServiceManual.objects.get_or_create(
            product=reservation_product,
            defaults={
                'title': '우리 학교 특별실 예약, 1분이면 끝!',
                'description': '복잡한 엑셀 파일, 전화로 확인하던 특별실 예약은 이제 그만.\n모바일과 PC에서 실시간으로 현황을 보고 클릭 한 번으로 예약하세요.',
                'is_published': True
            }
        )
        # Update if it exists but content is old
        if not created:
             manual.title = '우리 학교 특별실 예약, 1분이면 끝!'
             manual.description = '복잡한 엑셀 파일, 전화로 확인하던 특별실 예약은 이제 그만.\n모바일과 PC에서 실시간으로 현황을 보고 클릭 한 번으로 예약하세요.'
             manual.is_published = True
             manual.save()

        # Sections - Delete existing sections to re-create them in order
        manual.sections.all().delete()
        
        ManualSection.objects.create(
            manual=manual,
            title='학교 등록 및 시작',
            content="### 1. 학교 찾기부터 시작하세요\n\n메인 화면에서 **'학교 찾기'** 버튼을 눌러 선생님의 학교가 이미 등록되어 있는지 확인해보세요.\n없다면 **'새 학교 등록'**을 통해 학교 정보를 입력하면 즉시 전용 예약 시스템이 생성됩니다.\n\n> **Tip**: 학교 관리자 비밀번호는 꼭 기억해두세요! 나중에 특별실이나 시간을 수정할 때 필요합니다.",
            layout_type='image_left',
            display_order=1,
            badge_text='시작하기'
        )
        ManualSection.objects.create(
            manual=manual,
            title='예약 방법',
            content="### 빈 시간 클릭, 이름 입력, 끝!\n\n1. 원하는 **교실(특별실)** 탭을 선택합니다.\n2. 날짜를 확인하고, 비어있는 **교시**를 클릭합니다.\n3. **예약자명(학년반)**과 **수업 내용**을 간단히 입력하고 '예약하기'를 누릅니다.\n\n다른 선생님이 이미 예약한 시간은 회색으로 표시되어 중복 예약을 원천 차단합니다.",
            layout_type='text_only',
            display_order=2,
            badge_text=''
        )
        ManualSection.objects.create(
            manual=manual,
            title='중복/삭제 관리',
            content="### 내가 한 예약 수정하기\n\n예약한 내역을 클릭하면 **수정**하거나 **취소**할 수 있습니다.\n비밀번호를 설정했다면 비밀번호 입력 후 삭제가 가능합니다.\n\n관리자는 **'대시보드'**에서 모든 예약을 한눈에 관리하고, 특정 날짜나 교시를 막아둘 수도 있습니다(블랙아웃).",
            layout_type='card_carousel',
            display_order=3,
            badge_text='관리자 기능'
        )
    except Product.DoesNotExist:
        print("Product '학교 예약 시스템' does not exist. Skipping manual creation.")


    # 2. 선생님 사주 매뉴얼
    try:
        saju_product = Product.objects.get(title='선생님 사주')
        manual, created = ServiceManual.objects.get_or_create(
            product=saju_product,
            defaults={
                'title': '선생님을 위한 사주 사용법: 교실 속 지혜',
                'description': '단순한 점이 아닙니다. 아이들의 기질을 이해하고, 학급 운영의 힌트를 얻는 도구입니다.\n선생님의 타고난 에너지와 학생들의 성향을 조화롭게 맞추는 방법을 알아보세요.',
                'is_published': True
            }
        )
        # Update
        if not created:
             manual.title = '선생님을 위한 사주 사용법: 교실 속 지혜'
             manual.description = '단순한 점이 아닙니다. 아이들의 기질을 이해하고, 학급 운영의 힌트를 얻는 도구입니다.\n선생님의 타고난 에너지와 학생들의 성향을 조화롭게 맞추는 방법을 알아보세요.'
             manual.is_published = True
             manual.save()

        # Sections
        manual.sections.all().delete()

        ManualSection.objects.create(
            manual=manual,
            title='내 기질 파악하기',
            content="### 선생님의 중심 에너지는 무엇인가요?\n\n'사주' 탭에 들어가 생년월일시를 입력하면, 선생님을 상징하는 **일간(Day Master)**이 나옵니다.\n- **목(木)**: 아이들을 성장시키고 뻗어나가는 힘\n- **화(火)**: 열정적이고 밝은 에너지로 분위기를 주도\n- **토(土)**: 묵묵히 품어주고 중심을 잡는 포용력\n- **금(金)**: 원칙과 체계를 세우는 냉철함\n- **수(水)**: 유연하고 지혜롭게 흐르는 소통\n\n이 에너지를 알면, 내가 힘들 때 왜 힘든지, 어떤 스타일로 아이들을 대할 때 가장 편안한지 알 수 있습니다.",
            layout_type='text_only',
            display_order=1,
            badge_text='핵심'
        )
        ManualSection.objects.create(
            manual=manual,
            title='학생과의 궁합 보기',
            content="### 유독 힘든 아이, 이유가 있을까요?\n\n특정 아이와 자꾸 부딪힌다면, 에너지의 방향이 다를 수 있습니다.\n'학생 사주' 기능을 통해 아이의 기질을 확인해보세요.\n\n- **예시**: 선생님은 꼼꼼한 '금'인데, 아이는 자유분방한 '화'라면? 통제하려 할수록 튀어나갑니다.\n- **해결**: 아이의 에너지를 인정하고, '규칙'보다는 '역할'을 주어 에너지를 쓰게 해주세요.",
            layout_type='image_right',
            display_order=2,
            badge_text='Tip'
        )
        ManualSection.objects.create(
            manual=manual,
            title='매일의 운세 활용하기',
            content="### 출근 전, 오늘의 날씨(운세) 확인\n\n'오늘의 운세'는 비가 올지 해가 뜰지 알려주는 일기예보와 같습니다.\n\n- **관인상생의 날**: 결재판이 잘 넘어가고 학부모 상담이 부드러운 날입니다.\n- **식상운**: 아이들과 활동적인 수업을 하기에 딱 좋은 날입니다.\n- **충(Clash)**: 돌발 상황이 생길 수 있으니, 차분하게 마음을 먹고 출근하세요.\n\n미리 알고 대비하면, 마음의 여유가 생깁니다.",
            layout_type='card_carousel',
            display_order=3,
            badge_text='매일 아침'
        )

    except Product.DoesNotExist:
        print("Product '선생님 사주' does not exist. Skipping manual creation.")

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_servicemanual_manualsection'),
    ]

    operations = [
        migrations.RunPython(create_manual_data),
    ]
