# Generated by Django 6.0.1 on 2026-02-16 22:02

from django.db import migrations, models


def backfill_product_texts(apps, schema_editor):
    """빈 값인 항목만 채운다 (idempotent)."""
    Product = apps.get_model('products', 'Product')
    BACKFILL = {
        '간편 수합':       ('학생 파일을 한곳에 모아요', '정리된 제출 목록', '3분'),
        '서명 수집':       ('연수 서명을 전자로 받아요', '출력용 서명부', '2분'),
        '학교 예약 시스템':  ('특별실 예약 충돌을 없애요', '예약 현황표', '1분'),
        '쌤BTI':          ('나의 교사 유형을 알아봐요', 'MBTI 결과 카드', '5분'),
        '학생 MBTI':      ('학생 성격 유형을 파악해요', '학급 MBTI 분석표', '10분'),
        '미술 수업 도우미':  ('미술 수업을 단계별로 진행해요', '단계별 수업 가이드', '5분'),
        '사주팔자':        ('사주로 나를 알아봐요', '사주 분석 리포트', '3분'),
        '학교폭력 상담 AI': ('학교폭력 사안을 상담해요', 'AI 상담 답변', '즉시'),
        'AI 기사 생성':    ('학교 소식을 기사로 만들어요', '뉴스 기사 + 카드뉴스', '3분'),
        '문서 버전 관리':   ('문서 수정 이력을 추적해요', '버전별 비교표', '2분'),
        '패들릿 봇':       ('패들릿 내용을 AI로 분석해요', 'AI 요약 답변', '즉시'),
        '교사 백과사전':    ('NotebookLM을 공유해요', '공유 노트북 링크', '1분'),
        '체스':           ('브라우저에서 체스를 즐겨요', '대국 기록', '자유'),
        '장기':           ('브라우저에서 장기를 즐겨요', '대국 기록', '자유'),
        '윷놀이':          ('브라우저에서 윷놀이를 해요', '게임 결과', '자유'),
        '학급 당번 관리':   ('학급 당번을 자동 배정해요', '주간 당번표', '3분'),
    }
    for title, (solve, result, time) in BACKFILL.items():
        updated = Product.objects.filter(
            title=title, solve_text=''
        ).update(solve_text=solve, result_text=result, time_text=time)
        if not updated:
            print(f"[backfill] '{title}' not found or already filled")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_update_hwp_converter_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='result_text',
            field=models.CharField(blank=True, help_text="결과물 (예: '엑셀 정리표')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='solve_text',
            field=models.CharField(blank=True, help_text="무엇을 해결? (예: '학생 파일을 한곳에 모아요')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='time_text',
            field=models.CharField(blank=True, help_text="소요시간 (예: '3분')", max_length=50),
        ),
        migrations.RunPython(backfill_product_texts, migrations.RunPython.noop),
    ]
