# Generated by Django 6.0.1 on 2026-02-22

from django.db import migrations


def deactivate_legacy_insight_product(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(title="인사이트", is_active=True).update(is_active=False)


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0044_move_ppobgi_to_classroom"),
    ]

    operations = [
        migrations.RunPython(
            deactivate_legacy_insight_product,
            migrations.RunPython.noop,
        ),
    ]
