# Generated by Django 5.2.4 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0048_move_timetable_to_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtsettings",
            name="rotation_mode",
            field=models.CharField(
                choices=[
                    ("auto_sequential", "자동 순차 (하루 1칸)"),
                    ("auto_random", "자동 랜덤 (하루 1회)"),
                    ("manual_sequential", "수동 순차"),
                    ("manual_random", "수동 랜덤"),
                ],
                default="manual_sequential",
                help_text="역할 순환 모드",
                max_length=20,
            ),
        ),
    ]
