# Generated by Django 6.0.1 on 2026-02-25 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        ('products', '0049_dtsettings_rotation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dtrole',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_roles', to='happy_seed.hsclassroom'),
        ),
        migrations.AddField(
            model_name='dtroleassignment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_assignments', to='happy_seed.hsclassroom'),
        ),
        migrations.AddField(
            model_name='dtschedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_schedules', to='happy_seed.hsclassroom'),
        ),
        migrations.AddField(
            model_name='dtsettings',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_settings', to='happy_seed.hsclassroom'),
        ),
        migrations.AddField(
            model_name='dtstudent',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_students', to='happy_seed.hsclassroom'),
        ),
        migrations.AlterField(
            model_name='dtsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dtsettings',
            constraint=models.UniqueConstraint(fields=('user', 'classroom'), name='dtsettings_user_classroom_unique'),
        ),
        migrations.AddConstraint(
            model_name='dtsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('classroom__isnull', True)), fields=('user',), name='dtsettings_user_global_unique'),
        ),
    ]
