# Generated by Django 6.0.1 on 2026-02-25 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0004_alter_hsclasseventlog_type'),
        ('products', '0050_dtrole_classroom_dtroleassignment_classroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dtsettings',
            name='spotlight_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dutyticker_spotlight_settings', to='products.dtstudent'),
        ),
        migrations.CreateModel(
            name='DTTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_code', models.CharField(max_length=20)),
                ('slot_kind', models.CharField(choices=[('period', '교시'), ('break', '쉬는시간'), ('lunch', '점심시간')], default='period', max_length=20)),
                ('slot_order', models.PositiveSmallIntegerField(default=1)),
                ('slot_label', models.CharField(default='1교시', max_length=50)),
                ('period_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_time_slots', to='happy_seed.hsclassroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_time_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot_order'],
                'constraints': [models.UniqueConstraint(fields=('user', 'classroom', 'slot_code'), name='dttimeslot_user_classroom_code_unique'), models.UniqueConstraint(condition=models.Q(('classroom__isnull', True)), fields=('user', 'slot_code'), name='dttimeslot_user_global_code_unique')],
            },
        ),
    ]
