# Generated by Django 5.2.1 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0051_dtsettings_spotlight_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("collect_sign", "수합·서명"),
                    ("classroom", "수업·학급 운영"),
                    ("work", "문서·작성"),
                    ("game", "교실 활동"),
                    ("counsel", "상담·리프레시"),
                    ("edutech", "가이드·인사이트"),
                    ("etc", "외부 서비스"),
                ],
                default="etc",
                help_text="서비스 카테고리(수합·서명은 launch_route_name 매핑으로도 자동 분류됨)",
                max_length=20,
            ),
        ),
    ]
