# Generated by Django 6.0.1 on 2026-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_update_product_service_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtsettings',
            name='theme',
            field=models.CharField(choices=[('deep_space', '딥 스페이스 (기본, 다크)'), ('sunny', '햇살 가득 교실 (라이트)'), ('pastel', '차분한 파스텔'), ('vivid', '비비드 팝 (캐주얼)')], default='deep_space', help_text='디자인 테마', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='solve_text',
            field=models.CharField(blank=True, help_text="무엇을 해결? (예: '문서와 의견 수합, 번거로운 일은 이제 저에게 맡겨주세요!')", max_length=100),
        ),
    ]
