# Generated by Django 6.0.1 on 2026-03-07 14:52

from django.db import migrations

def fix_textbooks(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductFeature = apps.get_model('products', 'ProductFeature')
    ServiceManual = apps.get_model('products', 'ServiceManual')
    ManualSection = apps.get_model('products', 'ManualSection')

    # Unicode literals (교육 자료실)
    title = '\uAD50\uC721 \uC790\uB8CC\uC2E4'
    route = 'textbooks:main'

    # 1. Product cleaning
    bad_list = list(Product.objects.filter(launch_route_name=route))
    for p in bad_list:
        if p.title != title:
            p.delete()
    
    # 2. Update/create product
    product, created = Product.objects.update_or_create(
        launch_route_name=route,
        defaults={
            'title': title,
            'lead_text': '\uBC14\uC774\uBE0C \uCF54\uB529\uC73C\uB8DC \uAD50\uC2E4\uB9CC\uC758 \uC778\uD130\uB799\uD2F0\uBE0C\uD55C \uC790\uB8CC\uB97C \uBC30\uD3EC\uD558\uC138\uC694.',
            'description': (
                "\uAD50\uC721 \uC790\uB8CC\uC2E4\uC740 AI \uD504\uB86C\uD504\uD2B8\uB97C \uD1B5\uD574 3D \uD0DC\uC591\uACC4, \uC9C0\uAD6C\uBC38 \uB4F1 \uBCF5\uC7A1\uD55C \uC218\uC5C5 \uB304\uAD6C\uB97C "
                "\uB2E8\uC77C HTML \uCF54\uB4DC\uB8DC \uC0DD\uC131\uD558\uACE0 \uD559\uC0DD\uB4E4\uC5D0\uACAC QR\uCF54\uB4DC\uB8DC \uC989\uC2DC \uBC30\uD3EC\uD560 \uC218 \uC748\uB294 \uC11C\uBE44\uC2A4\uC785\uB2C8\uB2E4. "
                "\uC804\uAD6D \uC120\uC11D\uB2D8\uB4E4\uACFC \uC790\uB8CC\uB97C \uAC35\uC720\uD558\uACE0 \uD559\uAE09 \uCE98\uB9B0\uB354\uC640\uB3C4 \uBC14\uB8DC \uC5F0\uACC4\uB429\uB2C8\uB2E4."
            ),
            'price': 0.00,
            'is_active': True,
            'is_featured': True,
            'is_guest_allowed': True,
            'icon': '\U0001F4DA',
            'color_theme': 'green',
            'card_size': 'small',
            'display_order': 15,
            'service_type': 'classroom',
        }
    )

    # 3. Features
    feature_list = [
        ('\u2728', '\uBC14\uC774\uBE0C \uCF54\uB529 & AI \uB3C4\uC6B0\uBBF8', '\uBCF5\uC7A1\uD55C \uCF54\uB529 \uC5C6\uC774 \uD504\uB86C\uD504\uD2B8\uB9CC\uC73C\uB8DC \uC544\uC774\uB4E4\uC774 \uC88B\uC544\uD560 \uB9CC\uD55C \uC778\uD130\uB799\uD2F0\uBE0C \uC790\uB8CC\uB97C \uC0DD\uC131\uD569\uB2C8\uB2E4.'),
        ('\U0001F517', 'QR \uCF54\uB4DC \uC989\uC2DC \uBC30\uD3EC', '\uB9CC\uB4E0 \uC790\uB8CC\uB97C QR\uCF54\uB4DC\uB8DC \uD744\uC6B0\uAC70\uB098 \uD559\uC2B5\uC9C0\uC5D0 \uBD80\uCC29\uD560 \uC218 \uC748\uB294 \uC704\uC82F\uC73C\uB8DC \uBC14\uB8DC \uBCF5\uC0AC\uD569\uB2C8\uB2E4.'),
        ('\U0001F4C5', '\uD559\uAE09 \uCE98\uB9B0\uB354 \uC608\uC57D', '\uC218\uC5C5 \uC77C\uC815\uC744 \uC608\uC57D\uD558\uBA74 \uD559\uAE09 \uCE98\uB9B0\uB354(Sheetbook)\uC5D0 \uB9C1\uD0AC\uC640 \uD568\uAED8 \uC790\uB3D9 \uB4F1\uB85D\uB429\uB2C8\uB2E4.'),
        ('\U0001F916', 'AI \uD615\uC131\uD3C9\uAC00 \uD034\uC988', '\uB525\uC2DC\uD03C AI\uAC00 \uC790\uB8CC \uB0B4\uC6A9\uC744 \uBC14\uD0D5\uC73C\uB8DC \uC544\uC774\uB4E4\uC744 \uC704\uD55C O/X \uD034\uC988\uB97C \uC790\uB3D9\uC73C\uB8DC \uCD9C\uC81C\uD569\uB2C8\uB2E4.'),
    ]
    for icon, f_title, desc in feature_list:
        ProductFeature.objects.update_or_create(
            product=product, title=f_title,
            defaults={'icon': icon, 'description': desc}
        )

    # 4. Manual
    manual, _ = ServiceManual.objects.update_or_create(
        product=product,
        defaults={
            'title': '\uAD50\uC721 \uC790\uB8CC\uC2E4 \uC0AC\uC6A9 \uAC00\uC774\uB4DC',
            'is_published': True,
            'description': '\uC790\uB8CC \uC0DD\uC131\uBD80\uD130 \uD559\uC0DD \uBC30\uD3EC, \uCE98\uB9B0\uB354 \uC5F0\uACC4\uAE4C\uC9C0\uC758 \uD744\uB984\uC744 \uC548\uB0B4\uD569\uB2C8\uB2E4.'
        }
    )

    # 5. Sections
    section_list = [
        ('\uC790\uB8CC \uC0DD\uC131\uD558\uAE40', 'AI \uD504\uB86C\uD504\uD2B8 \uB3C4\uC6B0\uBBF8\uC758 \uB3C4\uC6C0\uC744 \uBC1B\uC544 \uC218\uC5C5 \uC8FC\uC81C\uC5D0 \uB9DE\uB294 HTML \uCF54\uB4DC\uB97C \uC0DD\uC131\uD588\uACE0 \uB4F1\uB85D\uD558\uC138\uC694.', 1),
        ('\uD559\uC0DD \uBC30\uD3EC(QR)', '\uC791\uC131\uB41C \uC790\uB8CC\uB97C \uD559\uC0DD \uAC1C\uBCC4 \uAE30\uAE30\uB8DC \uC804\uC11D\uD558\uAE30 \uC704\uD574 \uD654\uBA74\uC5D0 QR \uCF54\uB4DC\uB97C \uD744\uC6B0\uAC70\uB098 \uCD9C\uB825\uC6A9 \uC704\uC82F\uC744 \uBC1F\uC0AC\uD558\uC138\uC694.', 2),
        ('\uC218\uC5C5 \uC608\uC57D & \uAC35\uC720', '\uC218\uC5C5 \uB0A0\uC9DC\uB97C \uC9C0\uC815\uD558\uC5EC \uD559\uAE09 \uCE98\uB9B0\uB354\uC5D0 \uC5F0\uACC4\uD558\uACE0, \uB2E4\uB978 \uC120\uC11D\uB2D8\uB4E4\uACFC \uC790\uB8CC\uB97C \uAC35\uC720\uD574 \uBC34\uC138\uC694.', 3),
    ]
    for m_title, content, order in section_list:
        ManualSection.objects.update_or_create(
            manual=manual, title=m_title,
            defaults={'content': content, 'display_order': order}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_dtsettings_role_view_mode'),
    ]

    operations = [
        migrations.RunPython(fix_textbooks, migrations.RunPython.noop),
    ]

