# Generated by Django
from django.db import migrations
from django.core.management import call_command

def add_infoboard_service(apps, schema_editor):
    try:
        call_command('ensure_infoboard')
    except Exception as e:
        print(f"Failed to run ensure_infoboard during migration: {e}")

def remove_infoboard_service(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(launch_route_name='infoboard:dashboard').delete()
    Product.objects.filter(title='인포보드').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_add_student_games_launch_ticket'),
    ]

    operations = [
        migrations.RunPython(add_infoboard_service, remove_infoboard_service),
    ]
