# Generated by Django 6.0.1 on 2026-03-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_align_guest_access_launch_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtsettings',
            name='tts_enabled',
            field=models.BooleanField(default=False, help_text='교시 시작 전 안내 TTS 자동 읽기 사용'),
        ),
        migrations.AddField(
            model_name='dtsettings',
            name='tts_minutes_before',
            field=models.PositiveSmallIntegerField(default=5, help_text='교시 시작 몇 분 전에 읽을지'),
        ),
        migrations.AddField(
            model_name='dtsettings',
            name='tts_pitch',
            field=models.FloatField(default=1.0, help_text='브라우저 음성 높낮이'),
        ),
        migrations.AddField(
            model_name='dtsettings',
            name='tts_rate',
            field=models.FloatField(default=0.95, help_text='브라우저 음성 속도'),
        ),
        migrations.AddField(
            model_name='dtsettings',
            name='tts_voice_uri',
            field=models.CharField(blank=True, default='', help_text='브라우저 음성 voiceURI', max_length=255),
        ),
        migrations.AlterField(
            model_name='dtsettings',
            name='theme',
            field=models.CharField(choices=[('deep_space', '딥 스페이스 (기본, 다크)'), ('sunny', '살구빛 햇살 (밝음)'), ('pastel', '민트 파스텔 (부드러움)'), ('vivid', '코랄 팝 (선명함)')], default='deep_space', help_text='디자인 테마', max_length=20),
        ),
    ]
