# Generated by Django 6.0.1 on 2026-03-27 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_seed', '0005_hsclassroom_shared_roster_group_and_more'),
        ('products', '0062_rename_edu_materials_service_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DTMissionAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='아침시간', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timer_minutes', models.PositiveSmallIntegerField(default=10)),
                ('mission_label', models.CharField(blank=True, default='', max_length=120)),
                ('mission_title', models.CharField(blank=True, default='', max_length=200)),
                ('mission_desc', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_mission_automations', to='happy_seed.hsclassroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dutyticker_mission_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
