# Generated by Django 6.0.1 on 2026-03-30 09:40

import datetime

from django.db import migrations, models
from django.db.models import F


def seed_morning_slot_and_backfill_automation_slot_codes(apps, schema_editor):
    DTTimeSlot = apps.get_model("products", "DTTimeSlot")
    DTMissionAutomation = apps.get_model("products", "DTMissionAutomation")

    DTTimeSlot.objects.exclude(slot_code="morning").update(slot_order=F("slot_order") + 1)

    scope_keys = set(DTTimeSlot.objects.values_list("user_id", "classroom_id").distinct())
    scope_keys.update(DTMissionAutomation.objects.values_list("user_id", "classroom_id").distinct())

    for user_id, classroom_id in scope_keys:
        exists = DTTimeSlot.objects.filter(
            user_id=user_id,
            classroom_id=classroom_id,
            slot_code="morning",
        ).exists()
        if exists:
            continue
        DTTimeSlot.objects.create(
            user_id=user_id,
            classroom_id=classroom_id,
            slot_code="morning",
            slot_kind="morning",
            slot_order=1,
            slot_label="아침시간",
            period_number=None,
            start_time=datetime.time(8, 0),
            end_time=datetime.time(9, 0),
        )

    slot_index = {}
    for slot in DTTimeSlot.objects.exclude(slot_kind="period").all():
        slot_index[(slot.user_id, slot.classroom_id, slot.start_time, slot.end_time)] = slot

    for automation in DTMissionAutomation.objects.all():
        slot = slot_index.get(
            (
                automation.user_id,
                automation.classroom_id,
                automation.start_time,
                automation.end_time,
            )
        )
        if not slot:
            continue
        automation.slot_code = slot.slot_code
        automation.name = slot.slot_label
        automation.save(update_fields=["slot_code", "name"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0063_dtmissionautomation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dtmissionautomation",
            name="slot_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="dttimeslot",
            name="slot_kind",
            field=models.CharField(
                choices=[
                    ("morning", "아침시간"),
                    ("period", "교시"),
                    ("break", "쉬는시간"),
                    ("lunch", "점심시간"),
                ],
                default="period",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            seed_morning_slot_and_backfill_automation_slot_codes,
            migrations.RunPython.noop,
        ),
    ]
